/** Reusable product autocomplete and catalog side panel. */
const CatalogPicker = {
  callback:null,products:[],
  async open(callback){this.callback=callback;this.products=await sariDB.getAll('products');let root=document.getElementById('catalog-picker-root');if(!root){root=document.createElement('div');root.id='catalog-picker-root';document.body.appendChild(root);}root.innerHTML=`<div class="catalog-backdrop" onclick="CatalogPicker.close()"></div><aside class="catalog-panel"><header><div><span class="text-[10px] text-sari-blue font-black uppercase">Catalogue SARI</span><h3 class="font-extrabold">Ajouter un produit</h3></div><button onclick="CatalogPicker.close()"><i data-lucide="x"></i></button></header><div class="p-3"><div class="relative"><input id="catalog-panel-search" class="doc-input pr-10" placeholder="Code, référence, nom, description…" oninput="CatalogPicker.filter(this.value)" autofocus><i data-lucide="search" class="absolute right-3 top-2.5 w-4 h-4 text-sari-blue"></i></div><p class="text-[10px] text-slate-400 mt-1">Supporte +, AND, /, OR et -terme</p></div><div id="catalog-panel-results" class="catalog-results"></div></aside>`;this.filter('');if(typeof lucide!=='undefined')lucide.createIcons();},
  filter(query){const result=document.getElementById('catalog-panel-results');if(!result)return;const rows=this.products.filter(p=>SariUtils.matchesAdvancedSearch(p,query,['referenceCode','sku','barcode','name','extendedDescription','category']));result.innerHTML=rows.map(p=>`<button onclick="CatalogPicker.choose('${p.id}')" class="catalog-result"><div><b>${SariUtils.escapeHtml(p.name)}</b><small>${SariUtils.escapeHtml(p.referenceCode||p.sku)} • ${SariUtils.escapeHtml(p.sku)}</small></div><span>${i18n.formatCurrency(p.sellingPrice)}</span></button>`).join('')||'<p class="p-8 text-center text-slate-400">Aucun produit</p>';},
  choose(id){const p=this.products.find(x=>x.id===id);if(p&&this.callback)this.callback(p);this.close();},close(){document.getElementById('catalog-picker-root')?.remove();this.callback=null;}
};window.CatalogPicker=CatalogPicker;

export {};
