/** Shared helpers for social-security, trade and corporate-governance modules. */
const ComplianceHelpers={
  t(key,fallback){return i18n.t(key,fallback);},
  docCount(documents,recordType,recordId){return documents.filter(document=>(document.links||[]).some(link=>link.recordType===recordType&&link.recordId===recordId)).length;},
  optionLabel(listKey,value){return OptionCatalog.label(listKey,value)||value||'—';},
  statusBadge(status){const colors={draft:'text-slate-600',submitted:'text-sari-blue',accepted:'text-green-600',paid:'text-green-700',closed:'text-slate-700'};return `<span class="sari-badge ${colors[status]||''}">${SariUtils.escapeHtml(this.optionLabel('complianceStatus',status))}</span>`;},
  paid(payments,declarationId){return payments.filter(payment=>payment.declarationId===declarationId).reduce((sum,payment)=>sum+Number(payment.amount||0),0);},
  paymentLabel(value){return this.t(value==='bank_transfer'?'bankTransfer':value==='check'?'checkPayment':value==='online'?'onlinePayment':value,value||'—');},
  financialCandidates(orders=[],purchases=[]){return [...orders.map(item=>({id:item.id,referenceCode:item.referenceCode||item.id,partnerName:item.customerName,status:item.status,documentType:item.documentType||'invoice',recordType:'order'})),...purchases.map(item=>({id:item.id,referenceCode:item.referenceCode||item.id,partnerName:item.supplierName,status:item.status,documentType:item.documentType||'purchase_invoice',recordType:'purchaseDocument'}))];},
  pickFinancialDocuments({orders=[],purchases=[],selected=[],title='',onSave}){const items=this.financialCandidates(orders,purchases);DocumentLinkPicker.open({title:title||this.t('linkRelatedDocuments','Lier les factures et documents associés'),items,selected,onSave});},
  linkedDocumentRows(ids=[],orders=[],purchases=[]){return ids.map(id=>{const item=[...orders,...purchases].find(row=>row.id===id);return item?{id,referenceCode:item.referenceCode||id,partner:item.customerName||item.supplierName||'',total:item.total||0,currency:item.currency||'DZD',type:item.documentType||'document'}:{id,referenceCode:id,partner:'',total:0,currency:'DZD',type:'document'};});},
  async manageOptions(listKey,title,{template=false,onChanged=null}={}){this.optionManager={listKey,title,template,onChanged};await OptionCatalog.init();this.renderOptions();},
  renderOptions(){const state=this.optionManager;if(!state)return;const rows=OptionCatalog.options(state.listKey),root=document.getElementById('sari-modal-root');root.innerHTML=`<div class="fixed inset-0 z-[130] sari-modal-backdrop grid place-items-center p-3"><section class="sari-tile w-full max-w-4xl max-h-[92vh] overflow-y-auto p-6"><header class="flex justify-between border-b pb-3"><div><span class="sari-badge">${this.t('configurableList','Liste configurable')}</span><h2 class="text-xl font-extrabold mt-2">${SariUtils.escapeHtml(state.title)}</h2></div><button onclick="app.closeModalRoot()"><i data-lucide="x"></i></button></header><button onclick="ComplianceHelpers.editOption()" class="sari-btn px-4 py-2 mt-4 bg-sari-blue text-white"><i data-lucide="plus"></i>${this.t('add','Ajouter')}</button><div class="space-y-2 mt-4">${rows.map(row=>`<article class="p-4 border rounded-xl flex flex-col md:flex-row justify-between gap-3"><div><b>${SariUtils.escapeHtml(row.name?.[i18n.currentLang]||row.name?.fr||row.value)}</b><p class="text-xs text-slate-500">${SariUtils.escapeHtml(row.code||row.value)}${(row.templateHtml||row.templateHtmlI18n)?` • ${this.t('htmlTemplate','Modèle HTML')}`:''}</p></div><div><button onclick="ComplianceHelpers.editOption('${row.id}')" class="doc-action">${this.t('edit','Modifier')}</button><button onclick="ComplianceHelpers.deleteOption('${row.id}')" class="doc-action text-red-600">${this.t('delete','Supprimer')}</button></div></article>`).join('')||`<p class="p-6 text-slate-400">${this.t('noConfiguredValue','Aucune valeur configurée.')}</p>`}</div></section></div>`;window.SariIcons?.hydrate();},
  async editOption(id=''){const state=this.optionManager,rows=OptionCatalog.options(state.listKey),old=rows.find(row=>row.id===id)||{},fields=[{name:'code',label:this.t('code','Code'),value:old.code||old.value||'',required:true},{name:'fr',label:'Français',value:old.name?.fr||'',required:true},{name:'ar',label:'العربية',value:old.name?.ar||'',required:true},{name:'en',label:'English',value:old.name?.en||'',required:true}];if(state.template)fields.push({name:'templateFr',label:`${this.t('htmlTemplate','Modèle HTML')} FR`,type:'textarea',value:old.templateHtmlI18n?.fr||old.templateHtml||'<h1>{title}</h1><p>{content}</p>'},{name:'templateAr',label:`${this.t('htmlTemplate','Modèle HTML')} AR`,type:'textarea',value:old.templateHtmlI18n?.ar||old.templateHtml||'<div dir="rtl"><h1>{title}</h1><p>{content}</p></div>'},{name:'templateEn',label:`${this.t('htmlTemplate','Modèle HTML')} EN`,type:'textarea',value:old.templateHtmlI18n?.en||old.templateHtml||'<h1>{title}</h1><p>{content}</p>'});const values=await DialogManager.form(id?this.t('editConfiguredValue','Modifier la valeur'):this.t('newConfiguredValue','Nouvelle valeur'),fields);if(!values)return;const code=values.code.trim(),value=old.value||code.toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');await sariDB.save('configurableOptions',{...old,id:id||`${state.listKey}-${crypto.randomUUID()}`,listKey:state.listKey,value,code,name:{fr:values.fr,ar:values.ar,en:values.en},templateHtml:state.template?RichTextEditor.sanitize(values.templateFr||''):'',templateHtmlI18n:state.template?{fr:RichTextEditor.sanitize(values.templateFr||''),ar:RichTextEditor.sanitize(values.templateAr||''),en:RichTextEditor.sanitize(values.templateEn||'')}:{},order:old.order||rows.length+1,isActive:true});await OptionCatalog.init();await state.onChanged?.();this.renderOptions();},
  async deleteOption(id){if(!await DialogManager.confirm(this.t('deleteConfiguredValueConfirm','Supprimer cette valeur configurable ?')))return;await sariDB.delete('configurableOptions',id);await OptionCatalog.init();await this.optionManager?.onChanged?.();this.renderOptions();}
};
window.ComplianceHelpers=ComplianceHelpers;
export {};
