/**
 * SARI Système - Configuration & Complete Trilingual Dictionary (FR / AR / EN)
 * Medical Equipment & Consumables Distribution Management System - Algeria
 */

const SARI_CONFIG = {
  COMPANY_NAME: "SARI SYSTÈMEs",
  COMPANY_FULL_NAME: "SARI Système - Médical & Distribution Algérie",
  COMPANY_ADDRESS: "Lotissement Medical, Bab Ezzouar, 16024 Alger, Algérie",
  COMPANY_PHONE: "+213 21 24 88 90 / +213 550 99 12 34",
  COMPANY_EMAIL: "contact@sarisysteme.dz",
  COMPANY_NIF: "001616098765432",
  COMPANY_RC: "16/00-0987654B19",
  COMPANY_AI: "1602409876",
  DEFAULT_TAX_RATE: 0.19, // 19% Algerian TVA
  
  BRAND_COLORS: {
    primary: '#009CC5',
    primaryDark: '#007D9E',
    lime: '#C6DA34',
    limeDark: '#9BB024',
    amber: '#EBB51A',
    amberDark: '#C69512',
    white: '#FFFFFF',
    darkBg: '#090E17',
    darkCard: '#131E2F',
    textDark: '#0F172A',
    textLight: '#F8FAFC'
  },

  CURRENCIES: {
    DZD: { code: 'DZD', symbol: 'DA', rate: 1, name: { fr: 'Dinar Algérien', ar: 'دينار جزائري', en: 'Algerian Dinar' } },
    EUR: { code: 'EUR', symbol: '€', rate: 145.50, name: { fr: 'Euro', ar: 'يورو', en: 'Euro' } },
    USD: { code: 'USD', symbol: '$', rate: 134.20, name: { fr: 'Dollar Américain', ar: 'دولار أمريكي', en: 'US Dollar' } },
    CNY: { code: 'CNY', symbol: '¥', rate: 18.60, name: { fr: 'Yuan Chinois', ar: 'يوان صيني', en: 'Chinese Yuan' } }
  },

  INCOTERMS: [
    { code: 'FOB', name: 'Free On Board (FOB)' },
    { code: 'CIF', name: 'Cost, Insurance and Freight (CIF)' },
    { code: 'EXW', name: 'Ex Works (EXW)' },
    { code: 'CFR', name: 'Cost and Freight (CFR)' },
    { code: 'DDP', name: 'Delivered Duty Paid (DDP)' },
    { code: 'FCA', name: 'Free Carrier (FCA)' }
  ],

  PRODUCT_CATEGORIES: [
    { id: 'diagnostic', fr: 'Équipement de Diagnostic', ar: 'معدات التشخيص', en: 'Diagnostic Equipment' },
    { id: 'consumables', fr: 'Consommables Médicaux', ar: 'المستلزمات الطبية المستهلكة', en: 'Medical Consumables' },
    { id: 'furniture', fr: 'Mobilier Hospitalier & Clinique', ar: 'أثاث المستشفيات والعيادات', en: 'Hospital & Clinic Furniture' },
    { id: 'sterilization', fr: 'Stérilisation & Laboratoire', ar: 'معدات التعقيم والمختبر', en: 'Sterilization & Laboratory' },
    { id: 'ppe', fr: 'Équipements de Protection (EPI)', ar: 'معدات الحماية الشخصية', en: 'Personal Protective Equipment (PPE)' },
    { id: 'surgical', fr: 'Accessoires Chirurgie & Pharm.', ar: 'الملحقات الجراحية والصيدلانية', en: 'Pharmaceutical & Surgical Accessories' }
  ],

  UNITS: [
    { id: 'piece', fr: 'Pièce (Pcs)', ar: 'قطعة (Pcs)', en: 'Piece (Pcs)' },
    { id: 'box', fr: 'Boîte (Bte)', ar: 'علبة (Bte)', en: 'Box (Bte)' },
    { id: 'carton', fr: 'Carton (Ctn)', ar: 'كرتون (Ctn)', en: 'Carton (Ctn)' },
    { id: 'pack', fr: 'Pack / Paquet', ar: 'حزمة (Pack)', en: 'Pack (Pck)' },
    { id: 'liter', fr: 'Litre (L)', ar: 'لتر (L)', en: 'Liter (L)' },
    { id: 'set', fr: 'Kit / Ensemble', ar: 'مجموعة / طقم', en: 'Set / Kit' }
  ],

  ALGERIAN_WILAYAS: [
    { code: '01', fr: '01 - Adrar', ar: '01 - أدرار', en: '01 - Adrar' },
    { code: '02', fr: '02 - Chlef', ar: '02 - الشلف', en: '02 - Chlef' },
    { code: '03', fr: '03 - Laghouat', ar: '03 - الأغواط', en: '03 - Laghouat' },
    { code: '04', fr: '04 - Oum El Bouaghi', ar: '04 - أم البواقي', en: '04 - Oum El Bouaghi' },
    { code: '05', fr: '05 - Batna', ar: '05 - باتنة', en: '05 - Batna' },
    { code: '06', fr: '06 - Béjaïa', ar: '06 - بجاية', en: '06 - Béjaïa' },
    { code: '07', fr: '07 - Biskra', ar: '07 - بسكرة', en: '07 - Biskra' },
    { code: '08', fr: '08 - Béchar', ar: '08 - بشار', en: '08 - Béchar' },
    { code: '09', fr: '09 - Blida', ar: '09 - البليدة', en: '09 - Blida' },
    { code: '10', fr: '10 - Bouira', ar: '10 - البويرة', en: '10 - Bouira' },
    { code: '13', fr: '13 - Tlemcen', ar: '13 - تلمسان', en: '13 - Tlemcen' },
    { code: '15', fr: '15 - Tizi Ouzou', ar: '15 - تيزي وزو', en: '15 - Tizi Ouzou' },
    { code: '16', fr: '16 - Alger (Algiers)', ar: '16 - الجزائر العاصمة', en: '16 - Algiers' },
    { code: '19', fr: '19 - Sétif', ar: '19 - سطيف', en: '19 - Sétif' },
    { code: '21', fr: '21 - Skikda', ar: '21 - سكيكدة', en: '21 - Skikda' },
    { code: '23', fr: '23 - Annaba', ar: '23 - عنابة', en: '23 - Annaba' },
    { code: '25', fr: '25 - Constantine', ar: '25 - قسنطينة', en: '25 - Constantine' },
    { code: '30', fr: '30 - Ouargla', ar: '30 - ورقلة', en: '30 - Ouargla' },
    { code: '31', fr: '31 - Oran', ar: '31 - وهران', en: '31 - Oran' },
    { code: '47', fr: '47 - Ghardaïa', ar: '47 - غرداية', en: '47 - Ghardaïa' }
  ],

  USER_ROLES: {
    admin: {
      id: 'admin',
      fr: 'Administrateur (Accès Total)',
      ar: 'المشرف العام (صلاحيات كاملة)',
      en: 'Administrator (Full Access)',
      badgeColor: '#009CC5'
    },
    inventory: {
      id: 'inventory',
      fr: 'Gestionnaire des Stocks',
      ar: 'مدير المخزون',
      en: 'Inventory Manager',
      badgeColor: '#C6DA34'
    },
    import_export: {
      id: 'import_export',
      fr: 'Responsable Import / Export',
      ar: 'مسؤول الاستيراد والتصدير',
      en: 'Import / Export Manager',
      badgeColor: '#EBB51A'
    },
    tenders: {
      id: 'tenders',
      fr: 'Responsable Appels d\'Offres',
      ar: 'مسؤول المناقصات والعقود',
      en: 'Tenders & Business Dev Manager',
      badgeColor: '#009CC5'
    },
    sales: {
      id: 'sales',
      fr: 'Employé Commercial (POS & B2B)',
      ar: 'موظف المبيعات (نقطة البيع والطلبيات)',
      en: 'Sales Employee (POS & B2B)',
      badgeColor: '#C6DA34'
    },
    readonly: {
      id: 'readonly',
      fr: 'Observateur (Lecture Seule)',
      ar: 'مراقب (قراءة فقط)',
      en: 'Read-Only Viewer',
      badgeColor: '#94A3B8'
    }
  }
};

// Comprehensive Trilingual Translation Dictionary (FR / AR / EN)
const TRANSLATIONS = {
  fr: {
    appName: "SARI SYSTÈME",
    appSubtitle: "Distribution Matériel Médical & Consommables • Algérie",
    dashboard: "Tableau de Bord",
    inventory: "Stock & Consommables",
    stockSubtitle: "Gestion des dispositifs médicaux, consommables, traçabilité des lots et conformité CE / MSPRH Algérie.",
    stockSearchLabel: "Recherche (SKU, nom, lot)", searchProducts: "Rechercher produits, références, lots ou fabricants…",
    allCategories: "Toutes les catégories", allWarehouses: "Tous les dépôts", expiryStatus: "Statut de péremption", allProducts: "Tous les produits",
    expiryAll: "Toutes les péremptions", expiryExpired: "Produits périmés", expiryNear: "Expiration proche (30 jours)", expiryValid: "Produits valides",
    skuReference: "SKU / Référence", productCompliance: "Produit & conformité", categoryHeader: "Catégorie", stockHeader: "Stock actuel", warehouseHeader: "Dépôt", purchasePriceHeader: "Prix d’achat", sellingPriceHeader: "Prix de vente", lotExpiryHeader: "Lot & péremption", actionsHeader: "Actions",
    menuOperations: "Opérations", menuCommerce: "Commerce", menuPeople: "Équipe", menuAnalytics: "Analyse & Documents", menuAdministration: "Administration", collapseMenu: "Réduire le menu",
    companyNifLabel: "NIF", companyAddressLabel: "Adresse", footerActivity: "Distribution de matériel médical et consommables en Algérie", footerTax: "TVA 19%", footerIncoterms: "Incoterms FOB/CIF", footerThemes: "4 thèmes natifs", footerSettingsLink: "Paramètres & connecteur DB →",
    suppliers: "Fournisseurs",
    importExport: "Import / Export",
    tenders: "Appels d'Offres",
    sales: "Ventes & POS (BL)",
    customers: "Clients & Institutions",
    reports: "Rapports & Stats",
    auditLogs: "Journal d'Audit",
    settings: "Paramètres & Doc",
    hr: "Ressources Humaines",
    tasks: "Tâches & Kanban",
    documents: "Gestion documentaire", gedDescription: "Archives téléversées et documents ERP classés par catégorie et tags.", gedTypesMenu: "Types", gedCategoriesMenu: "Catégories", gedModulesMenu: "Modules", gedTagsMenu: "Tags", gedAllTypes: "Tous les types GED", gedAllCategories: "Toutes les catégories", gedAllModules: "Tous les modules", gedAllTags: "Tous les tags", gedTypeLabel: "Type GED", gedTitleLabel: "Titre / nom du fichier", gedOtherType: "Autre document", inlineTranslationOn: "Mode traduction en ligne activé", inlineTranslationOff: "Mode traduction en ligne désactivé",
    checklist: "Checklist interactive",
    employeePortal: "Espace Collaborateur",
    purchases: "Achats & Réceptions",
    ged: "GED Centrale",
    taxes: "Fiscalité Algérienne",
    masterData: "Listes configurables",
    inventoryOps: "Lots & Inventaires",
    bulkImport: "Import de masse",
    api: "API & Intégrations",
    internalMessages: "Messagerie interne",
    vatRates: "Taux de TVA",
    documentNumbering: "Types & Numérotation",
    branding: "Gestion des logos",
    richDescription: "Description détaillée",
    helpDoc: "Architecture & Documentation",

    // Header & Navigation
    searchPlaceholder: "Rechercher produits, appels d'offres, expéditions... (Ctrl+K)",
    online: "En Ligne",
    offline: "Hors Ligne",
    syncPending: "Sync en Attente",
    syncNow: "Synchroniser",
    role: "Rôle",
    language: "Langue",
    theme: "Thème",
    lightMode: "Mode Clair",
    darkMode: "Mode Sombre",

    // Dashboard KPIs & Descriptions
    welcomeMessage: "Bienvenue sur le système ERP SARI Système. Surveillance du stock médical, des expéditions maritimes et des appels d'offres en Algérie.",
    totalProducts: "Total Produits",
    totalStockValue: "Valeur Totale Stock (DZD)",
    lowStockAlerts: "Alertes Stock Faible",
    todaySales: "Ventes / Commandes du Jour",
    monthlySales: "Ventes Mensuelles",
    activeShipments: "Expéditions Import en Cours",
    expiringProducts: "Péremptions Prochaines (< 30j)",
    activeTenders: "Appels d'Offres Actifs",
    globalRevenue: "Chiffre d'Affaires Global",
    outstandingReceivables: "Créances Clients en Attente",
    cumulativeImportCosts: "Coûts Importations Cumulés",
    stockMovementsChart: "Mouvements Stock (Entrées / Sorties)",
    revenueEvolutionChart: "Évolution Chiffre d'Affaires (DZD)",
    categoryDistChart: "Répartition par Catégorie Médicale",
    sourcingRatioChart: "Sourcing Import vs. Local Algérie",
    tenderPipelineChart: "Pipeline Appels d'Offres",
    activeTendersList: "Appels d'Offres en Cours & Échéances",
    recentAuditTimeline: "Journal des Activités Récentes",
    viewAll: "Voir tout",
    view: "Consulter",

    // Actions & Buttons
    addProduct: "+ Nouveau Produit",
    addSupplier: "+ Nouveau Fournisseur",
    addShipment: "+ Nouvelle Expédition",
    addTender: "+ Nouvel Appel d'Offres",
    newOrder: "+ Nouvelle Vente / Commande",
    addCustomer: "+ Nouveau Client",
    exportCSV: "Exporter CSV",
    exportExcel: "Exporter Excel",
    exportPDF: "Imprimer / PDF",
    importCSV: "Importer CSV/Excel",
    printBarcodes: "Imprimer Étiquettes Code-barres / QR",
    traceability: "Traçabilité Lot / Batch",
    sourcingCalc: "Comparateur Sourcing Local vs Import",
    landedCostCalc: "Calculateur Coût de Revient",
    bidCalculator: "Espace Préparation Offre (Devis)",
    scanBarcode: "Scanner Code-barres",
    save: "Enregistrer",
    cancel: "Annuler",
    close: "Fermer",
    edit: "Modifier",
    delete: "Supprimer",
    duplicate: "Dupliquer",
    printInvoice: "Facture",
    printBL: "Bon de Livraison (BL)",

    // Common Headers
    sku: "SKU / Réf",
    productName: "Produit & Conformité",
    category: "Catégorie",
    stock: "Stock Actuel",
    minStock: "Seuil Min",
    unitPrice: "Prix d'Achat (DA)",
    sellingPrice: "Prix Vente (DA)",
    warehouse: "Entrepôt / Dépôt",
    lotNumber: "N° Lot & Péremption",
    expirationDate: "Date de Péremption",
    status: "Statut",
    actions: "Actions",

    // Statuses
    inStock: "En Stock",
    lowStock: "Stock Faible",
    outOfStock: "Rupture de Stock",
    expired: "Périmé",
    nearExpiry: "Péremption Proche",
    watching: "Sous Surveillance",
    inPreparation: "En Préparation",
    submitted: "Soumission Déposée",
    underEvaluation: "En Évaluation",
    won: "Attribué (Gagné)",
    lost: "Non Retenu (Perdu)",
    cancelled: "Annulé",
    orderPlaced: "Commande Passée",
    inTransit: "En Transit / Expédié",
    customsClearance: "Dédouanement en Cours",
    received: "Réceptionné au Dépôt",
    quoted: "Devis Émis",
    confirmed: "Confirmé",
    delivered: "Livré (BL Émis)",
    invoiced: "Facturé",
    paid: "Payé",

    // Messages
    noDataFound: "Aucun enregistrement ne correspond à vos critères de recherche.",
    savedSuccessfully: "Enregistrement sauvegardé avec succès dans IndexedDB !",
    deletedSuccessfully: "Enregistrement supprimé avec succès.",
    syncSuccessMessage: "File d'attente hors-ligne synchronisée avec succès !",
    demoDataReset: "Réinitialiser & Charger Données Démo Algérie",
    demoDataSuccess: "Données de démonstration algériennes chargées avec succès !",
    readOnlyWarning: "Vous êtes en mode Observateur (Lecture Seule). L'édition est désactivée."
  },

  ar: {
    appName: "ساري سيستام (SARI SYSTÈMEs)",
    appSubtitle: "توزيع التجهيزات والمستلزمات الطبية • الجزائر",
    dashboard: "لوحة القيادة",
    inventory: "المخزون والمنتجات",
    stockSubtitle: "إدارة الأجهزة والمستهلكات الطبية وتتبع الحصص والمطابقة CE / MSPRH الجزائر.",
    stockSearchLabel: "البحث (SKU، الاسم، الحصة)", searchProducts: "البحث عن المنتجات أو المراجع أو الحصص أو المصنعين…",
    allCategories: "كل الفئات", allWarehouses: "كل المخازن", expiryStatus: "حالة الصلاحية", allProducts: "كل المنتجات",
    expiryAll: "كل تواريخ الصلاحية", expiryExpired: "منتجات منتهية", expiryNear: "انتهاء قريب (30 يوماً)", expiryValid: "منتجات صالحة",
    skuReference: "SKU / المرجع", productCompliance: "المنتج والمطابقة", categoryHeader: "الفئة", stockHeader: "المخزون الحالي", warehouseHeader: "المخزن", purchasePriceHeader: "سعر الشراء", sellingPriceHeader: "سعر البيع", lotExpiryHeader: "الحصة والصلاحية", actionsHeader: "الإجراءات",
    menuOperations: "العمليات", menuCommerce: "التجارة", menuPeople: "الفريق", menuAnalytics: "التحليل والوثائق", menuAdministration: "الإدارة", collapseMenu: "طي القائمة",
    companyNifLabel: "الرقم الجبائي", companyAddressLabel: "العنوان", footerActivity: "توزيع المعدات والمستهلكات الطبية في الجزائر", footerTax: "ضريبة القيمة المضافة 19%", footerIncoterms: "شروط FOB/CIF", footerThemes: "4 سمات أصلية", footerSettingsLink: "الإعدادات وموصل قاعدة البيانات ←",
    suppliers: "الموردون",
    importExport: "الاستيراد والتصدير",
    tenders: "المناقصات والاستشارات",
    sales: "المبيعات ونقطة البيع",
    customers: "العملاء والمستشفيات",
    reports: "التقارير والإحصائيات",
    auditLogs: "سجل الأنشطة والتدقيق",
    settings: "الإعدادات والوثائق",
    hr: "الموارد البشرية",
    tasks: "المهام ولوحة كانبان",
    documents: "إدارة الوثائق", gedDescription: "الأرشيفات المحمّلة ووثائق النظام مصنفة حسب الفئة والوسوم.", gedTypesMenu: "الأنواع", gedCategoriesMenu: "الفئات", gedModulesMenu: "الوحدات", gedTagsMenu: "الوسوم", gedAllTypes: "كل أنواع الوثائق", gedAllCategories: "كل الفئات", gedAllModules: "كل الوحدات", gedAllTags: "كل الوسوم", gedTypeLabel: "نوع الوثيقة", gedTitleLabel: "العنوان / اسم الملف", gedOtherType: "وثيقة أخرى", inlineTranslationOn: "تم تفعيل وضع الترجمة المباشرة", inlineTranslationOff: "تم تعطيل وضع الترجمة المباشرة",
    checklist: "قائمة تحقق تفاعلية",
    employeePortal: "فضاء الموظف",
    purchases: "المشتريات والاستلام",
    ged: "إدارة الوثائق المركزية",
    taxes: "الجباية الجزائرية",
    masterData: "القوائم القابلة للتخصيص",
    inventoryOps: "الحصص والجرد",
    bulkImport: "الاستيراد الجماعي",
    api: "واجهة API والتكامل",
    internalMessages: "الرسائل الداخلية",
    vatRates: "نسب الضريبة على القيمة المضافة",
    documentNumbering: "أنواع وترقيم الوثائق",
    branding: "إدارة الشعارات",
    richDescription: "الوصف المفصل",
    helpDoc: "البنية والوثائق الإرشادية",

    // Header & Navigation
    searchPlaceholder: "ابحث عن المنتجات، المناقصات، الشحنات، العملاء... (Ctrl+K)",
    online: "متصل بالإنترنت",
    offline: "وضع غير متصل",
    syncPending: "مزامنة معلقة",
    syncNow: "مزامنة الآن",
    role: "الصلاحية",
    language: "اللغة",
    theme: "المظهر",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",

    // Dashboard KPIs & Descriptions
    welcomeMessage: "مرحباً بك في نظام إدارة التوزيع ساري سيستام. متابعة المخزون الطبي والشحنات البحرية والمناقصات في جميع ولايات الجزائر.",
    totalProducts: "إجمالي المنتجات",
    totalStockValue: "القيمة الإجمالية للمخزون (د.ج)",
    lowStockAlerts: "تنبيهات نقص المخزون",
    todaySales: "مبيعات وطلبيات اليوم",
    monthlySales: "المبيعات الشهرية",
    activeShipments: "شحنات الاستيراد النشطة",
    expiringProducts: "منتجات قريبة الانتهاء (> 30 يوماً)",
    activeTenders: "المناقصات الجارية",
    globalRevenue: "إجمالي رقم الأعمال",
    outstandingReceivables: "ديون ومستحقات العملاء",
    cumulativeImportCosts: "التكلفة التراكمية للاستيراد",
    stockMovementsChart: "حركة المخزون (دخول / خروج)",
    revenueEvolutionChart: "تطور رقم الأعمال (د.ج)",
    categoryDistChart: "توزيع المخزون حسب الفئة الطبية",
    sourcingRatioChart: "مقارنة التوريد المحلي والاستيراد",
    tenderPipelineChart: "حالة عروض المناقصات",
    activeTendersList: "المناقصات الجارية ومواعيد الإيداع",
    recentAuditTimeline: "سجل الأنشطة والعمليات الأخيرة",
    viewAll: "عرض الكل",
    view: "عرض",

    // Actions & Buttons
    addProduct: "+ منتج جديد",
    addSupplier: "+ مورد جديد",
    addShipment: "+ شحنة جديدة",
    addTender: "+ مناقصة جديدة",
    newOrder: "+ طلبية أو بيع جديد",
    addCustomer: "+ عميل جديد",
    exportCSV: "تصدير CSV",
    exportExcel: "تصدير Excel",
    exportPDF: "طباعة / PDF",
    importCSV: "استيراد CSV/Excel",
    printBarcodes: "طباعة ملصقات الباركود و QR",
    traceability: "تتبع الحصص والتشغيلات (Lot)",
    sourcingCalc: "مقارنة الشراء المحلي والاستيراد",
    landedCostCalc: "حاسبة التكلفة الإجمالية الواصلة",
    bidCalculator: "فضاء تحضير عروض المناقصات (BPU)",
    scanBarcode: "ماسح الباركود",
    save: "حفظ التغييرات",
    cancel: "إلغاء",
    close: "إغلاق",
    edit: "تعديل",
    delete: "حذف",
    duplicate: "نسخ",
    printInvoice: "فاتورة",
    printBL: "وصل تسليم (BL)",

    // Common Headers
    sku: "الرمز / SKU",
    productName: "المنتج والمطابقة",
    category: "الفئة",
    stock: "المخزون المتوفر",
    minStock: "الحد الأدنى",
    unitPrice: "سعر الشراء (د.ج)",
    sellingPrice: "سعر البيع (د.ج)",
    warehouse: "المستودع / المخزن",
    lotNumber: "رقم الحصة والصلاحية",
    expirationDate: "تاريخ انتهاء الصلاحية",
    status: "الحالة",
    actions: "الإجراءات",

    // Statuses
    inStock: "متوفر بالمخزون",
    lowStock: "مخزون منخفض",
    outOfStock: "نفاد المخزون",
    expired: "منتهي الصلاحية",
    nearExpiry: "قريب الانتهاء",
    watching: "قيد المتابعة",
    inPreparation: "قيد التحضير",
    submitted: "تم إيداع العرض",
    underEvaluation: "قيد التقييم",
    won: "فوز بالعقد",
    lost: "غير فائز",
    cancelled: "ملغاة / غير مجدية",
    orderPlaced: "تم تقديم الطلب",
    inTransit: "في الشحن / الترانزيت",
    customsClearance: "التخليص الجمركي",
    received: "تم الاستلام في المخزن",
    quoted: "عرض سعر",
    confirmed: "مؤكد",
    delivered: "تم التسليم (BL)",
    invoiced: "تمت الفوترة",
    paid: "مدفوع",

    // Messages
    noDataFound: "لم يتم العثور على سجلات تطابق معايير البحث.",
    savedSuccessfully: "تم حفظ السجل بنجاح في قاعدة البيانات المحلية!",
    deletedSuccessfully: "تم الحذف بنجاح.",
    syncSuccessMessage: "تمت مزامنة البيانات المعلقة بنجاح!",
    demoDataReset: "إعادة تعيين وتحميل بيانات الجزائر النموذجية",
    demoDataSuccess: "تم تحميل البيانات التجريبية الجزائرية بنجاح!",
    readOnlyWarning: "أنت مسجل الدخول بصفة مراقب (قراءة فقط). التعديل مقيد."
  },

  en: {
    appName: "SARI SYSTÈMES",
    appSubtitle: "Medical Equipment & Consumables Distribution • Algeria",
    dashboard: "Dashboard",
    inventory: "Inventory & Consumables",
    stockSubtitle: "Manage medical devices, consumables, lot traceability and CE / MSPRH Algeria compliance.",
    stockSearchLabel: "Search (SKU, name, lot)", searchProducts: "Search products, references, lots or manufacturers…",
    allCategories: "All categories", allWarehouses: "All warehouses", expiryStatus: "Expiry status", allProducts: "All products",
    expiryAll: "All expiry statuses", expiryExpired: "Expired products", expiryNear: "Near expiry (30 days)", expiryValid: "Valid products",
    skuReference: "SKU / Reference", productCompliance: "Product & compliance", categoryHeader: "Category", stockHeader: "Current stock", warehouseHeader: "Warehouse", purchasePriceHeader: "Purchase price", sellingPriceHeader: "Selling price", lotExpiryHeader: "Lot & expiry", actionsHeader: "Actions",
    menuOperations: "Operations", menuCommerce: "Commerce", menuPeople: "Team", menuAnalytics: "Analytics & Documents", menuAdministration: "Administration", collapseMenu: "Collapse menu",
    companyNifLabel: "Tax ID (NIF)", companyAddressLabel: "Address", footerActivity: "Medical equipment and consumables distribution in Algeria", footerTax: "VAT 19%", footerIncoterms: "FOB/CIF Incoterms", footerThemes: "4 native themes", footerSettingsLink: "Settings & DB connector →",
    suppliers: "Suppliers",
    importExport: "Import / Export",
    tenders: "Tenders & Consultations",
    sales: "Sales & POS (BL)",
    customers: "Customers & Institutions",
    reports: "Reports & Analytics",
    auditLogs: "Audit Logs",
    settings: "Settings & Docs",
    hr: "Human Resources",
    tasks: "Tasks & Kanban",
    documents: "Document Management", gedDescription: "Uploaded archives and ERP documents classified by category and tags.", gedTypesMenu: "Types", gedCategoriesMenu: "Categories", gedModulesMenu: "Modules", gedTagsMenu: "Tags", gedAllTypes: "All GED types", gedAllCategories: "All categories", gedAllModules: "All modules", gedAllTags: "All tags", gedTypeLabel: "GED type", gedTitleLabel: "Title / file name", gedOtherType: "Other document", inlineTranslationOn: "Inline translation mode enabled", inlineTranslationOff: "Inline translation mode disabled",
    checklist: "Interactive Checklist",
    employeePortal: "Employee Portal",
    purchases: "Purchases & Receipts",
    ged: "Central Document Management",
    taxes: "Algerian Tax Management",
    masterData: "Configurable Lists",
    inventoryOps: "Lots & Inventory",
    bulkImport: "Bulk Import",
    api: "API & Integrations",
    internalMessages: "Internal Messaging",
    vatRates: "VAT Rates",
    documentNumbering: "Document Types & Numbering",
    branding: "Logo Management",
    richDescription: "Detailed Description",
    helpDoc: "Architecture & Documentation",

    // Header & Navigation
    searchPlaceholder: "Search products, tenders, shipments, clients... (Ctrl+K)",
    online: "Online",
    offline: "Offline",
    syncPending: "Sync Pending",
    syncNow: "Sync Now",
    role: "Role",
    language: "Language",
    theme: "Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",

    // Dashboard KPIs & Descriptions
    welcomeMessage: "Welcome to SARI Système ERP. Oversee medical inventory, maritime imports, and hospital tenders across Algeria.",
    totalProducts: "Total Products",
    totalStockValue: "Total Stock Value (DZD)",
    lowStockAlerts: "Low Stock Alerts",
    todaySales: "Today's Sales / Orders",
    monthlySales: "Monthly Sales",
    activeShipments: "Active Import Shipments",
    expiringProducts: "Upcoming Expirations (< 30d)",
    activeTenders: "Active Tenders & Deadlines",
    globalRevenue: "Total Revenue (DZD)",
    outstandingReceivables: "Outstanding Receivables",
    cumulativeImportCosts: "Cumulative Import Costs",
    stockMovementsChart: "Stock Movements (In / Out)",
    revenueEvolutionChart: "Monthly Revenue Evolution (DZD)",
    categoryDistChart: "Medical Category Distribution",
    sourcingRatioChart: "Import vs. Local Sourcing Ratio",
    tenderPipelineChart: "Tenders Pipeline Status",
    activeTendersList: "Active Tenders & Submission Deadlines",
    recentAuditTimeline: "Recent Activity Audit Timeline",
    viewAll: "View All",
    view: "View",

    // Actions & Buttons
    addProduct: "+ New Product",
    addSupplier: "+ New Supplier",
    addShipment: "+ New Shipment",
    addTender: "+ New Tender",
    newOrder: "+ New Sale / Order",
    addCustomer: "+ New Customer",
    exportCSV: "Export CSV",
    exportExcel: "Export Excel",
    exportPDF: "Print / PDF",
    importCSV: "Import CSV/Excel",
    printBarcodes: "Print Barcodes / QR Labels",
    traceability: "Lot / Batch Traceability",
    sourcingCalc: "Local vs. Import Sourcing Compare",
    landedCostCalc: "Landed Cost Calculator",
    bidCalculator: "Bid Preparation Workspace (BPU)",
    scanBarcode: "Scan Barcode",
    save: "Save Changes",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    delete: "Delete",
    duplicate: "Duplicate",
    printInvoice: "Invoice",
    printBL: "Delivery Note (BL)",

    // Common Headers
    sku: "SKU / Code",
    productName: "Product & Compliance",
    category: "Category",
    stock: "Current Stock",
    minStock: "Min Alert",
    unitPrice: "Purchase Price (DA)",
    sellingPrice: "Selling Price (DA)",
    warehouse: "Warehouse / Depot",
    lotNumber: "Lot # & Expiry",
    expirationDate: "Expiration Date",
    status: "Status",
    actions: "Actions",

    // Statuses
    inStock: "In Stock",
    lowStock: "Low Stock",
    outOfStock: "Out of Stock",
    expired: "Expired",
    nearExpiry: "Near Expiration",
    watching: "Watching",
    inPreparation: "In Preparation",
    submitted: "Submitted",
    underEvaluation: "Under Evaluation",
    won: "Won / Awarded",
    lost: "Lost / Not Awarded",
    cancelled: "Cancelled",
    orderPlaced: "Order Placed",
    inTransit: "In Transit / Shipped",
    customsClearance: "Customs Clearance",
    received: "Received in Warehouse",
    quoted: "Quoted",
    confirmed: "Confirmed",
    delivered: "Delivered (BL Issued)",
    invoiced: "Invoiced",
    paid: "Paid",

    // Messages
    noDataFound: "No records found matching your filter criteria.",
    savedSuccessfully: "Record saved successfully to local IndexedDB!",
    deletedSuccessfully: "Record deleted successfully.",
    syncSuccessMessage: "Offline sync queue processed successfully!",
    demoDataReset: "Reset & Load Algerian Demo Dataset",
    demoDataSuccess: "Algerian demo dataset loaded successfully!",
    readOnlyWarning: "You are logged in as a Read-Only Viewer. Editing actions are disabled."
  }
};

Object.assign(TRANSLATIONS.fr,{importDescription:"Suivi des expéditions maritimes/aériennes, dédouanement, coûts rendus et Incoterms.",tendersDescription:"Suivi des consultations, cahiers des charges et préparation des offres techniques et financières.",salesDescription:"Catalogue, panier, commandes B2B, factures et bons de livraison.",inventoryOpsDescription:"Stock par dépôt, lots, FEFO/FIFO, mouvements, ajustements et comptages physiques."});
Object.assign(TRANSLATIONS.ar,{importDescription:"متابعة الشحنات البحرية والجوية والتخليص والتكاليف النهائية وشروط التجارة.",tendersDescription:"متابعة الاستشارات ودفاتر الشروط وتحضير العروض التقنية والمالية.",salesDescription:"الكتالوج والسلة وطلبيات المؤسسات والفواتير ووصولات التسليم.",inventoryOpsDescription:"المخزون حسب المستودع والحصص وحركات FEFO/FIFO والتسويات والجرد."});
Object.assign(TRANSLATIONS.en,{importDescription:"Track sea/air shipments, customs clearance, landed costs and Incoterms.",tendersDescription:"Track consultations, specifications and technical/financial bid preparation.",salesDescription:"Catalog, cart, B2B orders, invoices and delivery notes.",inventoryOpsDescription:"Stock by warehouse, lots, FEFO/FIFO, movements, adjustments and physical counts."});
Object.assign(TRANSLATIONS.fr,{viewOrder:"Consulter la commande",files:"pièce(s)",participants:"participant(s)",daysRecorded:"jour(s) enregistré(s)",valuesConfigured:"valeur(s) configurée(s)",expectedColumns:"Colonnes attendues :",rowsImported:"ligne(s) importée(s)",isRequired:"est obligatoire",invalidNumber:"nombre invalide",rowLabel:"Ligne",paymentTransactions:"Transactions de paiement",newOperation:"Nouvelle opération"});
Object.assign(TRANSLATIONS.ar,{viewOrder:"عرض الطلبية",files:"ملف (ملفات)",participants:"مشارك (مشاركون)",daysRecorded:"يوم (أيام) مسجلة",valuesConfigured:"قيمة (قيم) مهيأة",expectedColumns:"الأعمدة المتوقعة:",rowsImported:"سطر (أسطر) مستوردة",isRequired:"إلزامي",invalidNumber:"رقم غير صالح",rowLabel:"سطر",paymentTransactions:"معاملات الدفع",newOperation:"عملية جديدة"});
Object.assign(TRANSLATIONS.en,{viewOrder:"View order",files:"file(s)",participants:"participant(s)",daysRecorded:"day(s) recorded",valuesConfigured:"configured value(s)",expectedColumns:"Expected columns:",rowsImported:"row(s) imported",isRequired:"is required",invalidNumber:"invalid number",rowLabel:"Row",paymentTransactions:"Payment Transactions",newOperation:"New Operation"});

// Reports page (section 203) + report customization (section 200) + misc UI
const reportKeysFr={reportsDescription:"Évaluations des stocks, analyses de chiffre d'affaires par wilaya, coûts importations et profitabilité.",customizeReport:"Personnaliser le rapport",customizeReportHelp:"En-tête et lignes du rapport, avec champs dynamiques {reference}, {label}, {status}, {amount}, {type}, {company}, {title}, {date}.",reportHeaderTemplate:"En-tête du rapport",reportRowTemplate:"Ligne du rapport",detailedReport:"Rapport détaillé",printPDF:"Imprimer / PDF",reportTab_inventory:"Stock & Péremptions",reportTab_sales:"Ventes & Créances",reportTab_costs:"Coûts",reportTab_imports:"Importations",reportTab_tenders:"Appels d'Offres",reportTab_finance:"Rentabilité & Finances",reportTab_partners:"Clients & Fournisseurs",costFreight:"Fret / transport",costInsurance:"Assurance",costCustoms:"Douanes",costTotal:"Total logistique",costShipment:"Expédition",costSupplier:"Fournisseur",costPurchases:"Total achats locaux"};
const reportKeysAr={reportsDescription:"تقييم المخزون وتحليلات رقم الأعمال حسب الولاية وتكاليف الاستيراد والربحية.",customizeReport:"تخصيص التقرير",customizeReportHelp:"رأس التقرير وسطوره مع حقول ديناميكية {reference}، {label}، {status}، {amount}، {type}، {company}، {title}، {date}.",reportHeaderTemplate:"رأس التقرير",reportRowTemplate:"سطر التقرير",detailedReport:"تقرير مفصل",printPDF:"طباعة / PDF",reportTab_inventory:"المخزون والصلاحيات",reportTab_sales:"المبيعات والذمم",reportTab_costs:"التكاليف",reportTab_imports:"الواردات",reportTab_tenders:"المناقصات",reportTab_finance:"الربحية والمالية",reportTab_partners:"العملاء والموردون",costFreight:"الشحن / النقل",costInsurance:"التأمين",costCustoms:"الجمارك",costTotal:"الإجمالي اللوجستي",costShipment:"الشحنة",costSupplier:"المورد",costPurchases:"إجمالي المشتريات المحلية"};
const reportKeysEn={reportsDescription:"Stock assessments, sales analysis by wilaya, import costs and profitability.",customizeReport:"Customize Report",customizeReportHelp:"Report header and rows with dynamic fields {reference}, {label}, {status}, {amount}, {type}, {company}, {title}, {date}.",reportHeaderTemplate:"Report Header",reportRowTemplate:"Report Row",detailedReport:"Detailed Report",printPDF:"Print / PDF",reportTab_inventory:"Stock & Expirations",reportTab_sales:"Sales & Receivables",reportTab_costs:"Costs",reportTab_imports:"Imports",reportTab_tenders:"Tenders",reportTab_finance:"Profitability & Finance",reportTab_partners:"Clients & Suppliers",costFreight:"Freight / Transport",costInsurance:"Insurance",costCustoms:"Customs",costTotal:"Total Logistics",costShipment:"Shipment",costSupplier:"Supplier",costPurchases:"Total local purchases"};
Object.assign(TRANSLATIONS.fr,reportKeysFr);Object.assign(TRANSLATIONS.ar,reportKeysAr);Object.assign(TRANSLATIONS.en,reportKeysEn);

// Compatibility bridge for scripts progressively converted from classic
// globals to isolated ES modules. Domain modules still consume these stable
// names while their imports are migrated incrementally.
globalThis.SARI_CONFIG = SARI_CONFIG;
globalThis.TRANSLATIONS = TRANSLATIONS;

export { SARI_CONFIG, TRANSLATIONS };
