/** Promise-based themed dialogs replacing native alert/confirm/prompt. */
const DialogManager = {
  open({ title = 'SARI Système', message = '', fields = [], confirmText = 'Valider', cancelText = 'Annuler', danger = false, icon = 'sparkles' } = {}) {
    return new Promise(resolve => {
      let root = document.getElementById('sari-dialog-root');
      if (!root) { root = document.createElement('div'); root.id = 'sari-dialog-root'; document.body.appendChild(root); }
      root.innerHTML = `<div class="sari-dialog-backdrop" role="dialog" aria-modal="true" aria-labelledby="sari-dialog-title"><form id="sari-dialog-form" class="sari-dialog-card sari-grid-pattern"><header><div class="sari-dialog-icon ${danger ? 'danger' : ''}"><i data-lucide="${danger ? 'triangle-alert' : icon}"></i></div><div><h3 id="sari-dialog-title">${SariUtils.escapeHtml(title)}</h3>${message ? `<p>${SariUtils.escapeHtml(message)}</p>` : ''}</div></header><div class="sari-dialog-fields">${fields.map(field => `<label class="doc-label">${SariUtils.escapeHtml(field.label || field.name)}${field.type === 'image' ? ImageDropzone.html(`dialog-${field.name}`,field.value||'',field.label||field.name) : field.type === 'textarea' ? `<textarea name="${field.name}" class="doc-input" ${field.required ? 'required' : ''}>${SariUtils.escapeHtml(field.value || '')}</textarea>` : field.type === 'autocomplete' ? (()=>{const options=field.options||[],selected=options.find(option=>String(typeof option==='object'?option.value:option)===String(field.value)),display=selected?(typeof selected==='object'?selected.label:selected):'';return `<input name="${field.name}__display" list="dialog-list-${field.name}" value="${SariUtils.escapeHtml(display)}" class="doc-input" autocomplete="off" ${field.required?'required':''} oninput="DialogManager.resolveAutocomplete(this,'${field.name}')"><input type="hidden" name="${field.name}" value="${SariUtils.escapeHtml(String(field.value||''))}"><datalist id="dialog-list-${field.name}">${options.map(option=>{const value=typeof option==='object'?option.value:option,label=typeof option==='object'?option.label:option;return `<option value="${SariUtils.escapeHtml(label)}" data-code="${SariUtils.escapeHtml(value)}"></option>`}).join('')}</datalist>`})() : field.type === 'select' ? `<select name="${field.name}" class="doc-input">${(field.options || []).map(option => { const value=typeof option==='object'?option.value:option,label=typeof option==='object'?option.label:option;return `<option value="${SariUtils.escapeHtml(value)}" ${String(value)===String(field.value)?'selected':''}>${SariUtils.escapeHtml(label)}</option>`; }).join('')}</select>` : `<input name="${field.name}" type="${field.type || 'text'}" value="${SariUtils.escapeHtml(String(field.value ?? ''))}" class="doc-input" ${field.required ? 'required' : ''} ${field.step ? `step="${field.step}"` : ''}>`}</label>`).join('')}</div><footer><button type="button" data-dialog-cancel class="sari-btn px-4 py-2 bg-slate-200 dark:bg-slate-700">${SariUtils.escapeHtml(cancelText)}</button><button class="sari-btn px-5 py-2 ${danger ? 'bg-red-600' : 'bg-sari-blue'} text-white">${SariUtils.escapeHtml(confirmText)}</button></footer></form></div>`;
      const close = value => { root.querySelector('.sari-dialog-card')?.classList.add('closing'); setTimeout(() => { root.remove(); resolve(value); }, 150); };
      root.querySelector('[data-dialog-cancel]').onclick = () => close(null);
      root.querySelector('.sari-dialog-backdrop').addEventListener('click', event => { if (event.target.classList.contains('sari-dialog-backdrop')) close(null); });
      root.querySelector('form').onsubmit = event => { event.preventDefault(); const values=Object.fromEntries(new FormData(event.currentTarget));fields.filter(f=>f.type==='image').forEach(f=>values[f.name]=ImageDropzone.value(`dialog-${f.name}`,f.value||'')); close(fields.length ? values : true); };
      document.addEventListener('keydown', function esc(event) { if(event.key==='Escape'){document.removeEventListener('keydown',esc);close(null);} }, { once: true });
      if (typeof lucide !== 'undefined') lucide.createIcons(); setTimeout(() => root.querySelector('input,textarea,select')?.focus(), 50);
    });
  },
  resolveAutocomplete(input,name){const list=document.getElementById(input.getAttribute('list')),option=[...(list?.options||[])].find(x=>x.value===input.value),hidden=input.form?.elements[name];if(hidden)hidden.value=option?.dataset.code||'';input.setCustomValidity(option?'':'Sélectionnez une valeur dans la liste.');},
  confirm(message, options = {}) { return this.open({ title: options.title || 'Confirmation', message, confirmText: options.confirmText || 'Confirmer', danger: options.danger !== false, icon: 'help-circle' }); },
  alert(message, options = {}) { return this.open({ title: options.title || 'Information', message, fields: [], confirmText: 'Fermer', cancelText: 'Fermer', icon: options.icon || 'info' }); },
  form(title, fields, options = {}) { return this.open({ title, fields, message: options.message || '', confirmText: options.confirmText || 'Enregistrer', danger: options.danger || false }); }
};
window.DialogManager = DialogManager;
