/** Modern partner statistics and linked-document explorer. */
const Partner360 = {
  async open(type, id) {
    const isCustomer=type==='customer',store=isCustomer?'customers':'suppliers';
    const partner=await sariDB.getById(store,id);
    if(!partner)return app.showToast('Partenaire introuvable.','error');
    const docs=isCustomer?(await sariDB.getAll('orders')).filter(item=>item.customerId===id):(await sariDB.getAll('purchaseDocuments')).filter(item=>item.supplierId===id);
    const payments=(await sariDB.getAll('paymentTransactions')).filter(item=>item.partnerId===id);
    const total=docs.reduce((sum,doc)=>sum+Number(doc.total||0),0),outstanding=docs.filter(doc=>!['paid','closed'].includes(doc.status)).reduce((sum,doc)=>sum+Number(doc.total||0),0);
    const root=document.getElementById('sari-modal-root');
    root.innerHTML=`<div class="fixed inset-0 z-50 sari-modal-backdrop flex items-center justify-center p-3"><div class="sari-tile w-full max-w-6xl max-h-[94vh] overflow-y-auto p-6"><header class="flex justify-between border-b pb-3"><div class="flex gap-3 items-center">${partner.logo?`<img src="${partner.logo}" class="w-14 h-14 object-contain rounded-xl">`:''}<div><span class="sari-badge">${isCustomer?'CLIENT':'FOURNISSEUR'} 360°</span><h3 class="text-xl font-extrabold mt-1">${SariUtils.escapeHtml(partner.name)}</h3><p class="text-xs text-slate-500">${partner.referenceCode||partner.id}</p></div></div><button onclick="app.closeModalRoot()"><i data-lucide="x"></i></button></header>
      <div class="grid md:grid-cols-3 gap-3 mt-4 text-xs"><div class="p-3 border rounded"><span class="text-slate-400">${i18n.t('country','Pays')} / Wilaya</span><b class="block">${SariUtils.escapeHtml(partner.country||(partner.wilaya?i18n.getWilayaName(partner.wilaya):'—'))}</b></div><div class="p-3 border rounded"><span class="text-slate-400">Contact</span><b class="block">${SariUtils.escapeHtml(partner.contactInfo||partner.phone||'—')}</b></div><div class="p-3 border rounded"><span class="text-slate-400">Fiscalité / Certifications</span><b class="block">${SariUtils.escapeHtml(partner.taxId||partner.certifications||'—')}</b></div></div>
      <div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 my-5"><div class="sari-tile p-4"><small>Volume total</small><b class="block text-xl text-sari-blue">${i18n.formatCurrency(total)}</b></div><div class="sari-tile p-4"><small>Encours</small><b class="block text-xl text-sari-amber">${i18n.formatCurrency(outstanding)}</b></div><div class="sari-tile p-4"><small>Documents</small><b class="block text-xl">${docs.length}</b></div><div class="sari-tile p-4"><small>Valeur moyenne</small><b class="block text-xl text-sari-lime-dark">${i18n.formatCurrency(docs.length?total/docs.length:0)}</b></div></div>
      <section class="grid lg:grid-cols-[1fr_320px] gap-4"><div class="overflow-x-auto"><table class="w-full sari-table text-sm"><thead><tr><th class="p-2 text-left">Référence</th><th>Type</th><th>Statut</th><th>Total</th><th></th></tr></thead><tbody>${docs.map(doc=>`<tr class="border-t"><td class="p-2 font-mono-tech text-sari-blue">${doc.referenceCode||doc.id}</td><td>${SariUtils.escapeHtml(doc.documentType||'order')}</td><td>${OptionCatalog.label('documentStatus',doc.status)}</td><td>${i18n.formatCurrency(doc.total,doc.currency||'DZD')}</td><td><button onclick="app.closeModalRoot();DocumentDetailModule.open('${isCustomer?'order':'purchaseDocument'}','${doc.id}',{type:'${type}',id:'${id}',label:'${SariUtils.escapeHtml(partner.name)}'})" class="doc-action">Ouvrir →</button></td></tr>`).join('')}</tbody></table><h4 class="font-extrabold mt-5">${i18n.t('paymentTransactions','Transactions de paiement')} (${payments.length})</h4><table class="w-full text-xs mt-2"><tbody>${payments.map(payment=>`<tr class="border-t"><td class="p-2 font-mono-tech text-sari-blue">${payment.referenceCode}</td><td>${i18n.formatDate(payment.transactionDate)}</td><td>${payment.direction}</td><td class="font-bold">${i18n.formatCurrency(payment.amount,payment.currency)}</td><td><button onclick="DocumentDetailModule.viewPayment('${payment.id}')" class="doc-action">Voir</button></td></tr>`).join('')||'<tr><td class="p-3 text-slate-400">Aucun paiement</td></tr>'}</tbody></table></div>
      <aside class="space-y-3"><section class="p-4 border rounded-xl"><h4 class="font-extrabold">Documents de référence</h4><p class="text-xs text-slate-500 my-2">RC, NIF, certifications et pièces GED.</p><button onclick="DocumentManager.open('${type}','${id}','${SariUtils.escapeHtml(partner.name)}')" class="sari-btn w-full py-2 bg-sari-blue text-white">Ouvrir la GED</button><div class="rich-content text-xs mt-4">${RichTextEditor.sanitize(partner.richDetails||'')}</div></section><section class="p-4 border rounded-xl bg-sari-blue/5"><h4 class="font-extrabold flex items-center gap-2"><i data-lucide="notebook-pen" class="w-4 h-4 text-sari-blue"></i>${i18n.t('notes','Notes')}</h4><p class="text-sm whitespace-pre-wrap mt-3 text-slate-700 dark:text-slate-300">${SariUtils.escapeHtml(partner.notes||'—')}</p></section></aside></section>
      </div></div>`;
    window.SariIcons?.hydrate();
  }
};
window.Partner360=Partner360;

export {};
