/** Lightweight dependency-free rich text editor compatible with offline PWA mode. */
const RichTextEditor = {
  selections: new Map(),
  html(id, value = '', label = 'Description détaillée') {
    return `<div class="rich-editor-wrap"><label class="doc-label">${label}</label><div class="rich-editor-toolbar" role="toolbar" aria-label="Mise en forme"><button type="button" onmousedown="RichTextEditor.rememberSelection('${id}')" onclick="RichTextEditor.command('${id}','bold')" title="Gras"><b>B</b></button><button type="button" onmousedown="RichTextEditor.rememberSelection('${id}')" onclick="RichTextEditor.command('${id}','italic')" title="Italique"><i>I</i></button><button type="button" onmousedown="RichTextEditor.rememberSelection('${id}')" onclick="RichTextEditor.command('${id}','underline')" title="Souligné"><u>U</u></button><label class="rich-color-control" title="Couleur du texte"><span>A</span><input type="color" value="#0f172a" onmousedown="RichTextEditor.rememberSelection('${id}')" oninput="RichTextEditor.applyColor('${id}','foreColor',this.value)"></label><label class="rich-color-control rich-highlight-control" title="Couleur de surlignage"><span>A</span><input type="color" value="#fff59d" onmousedown="RichTextEditor.rememberSelection('${id}')" oninput="RichTextEditor.applyColor('${id}','hiliteColor',this.value)"></label><button type="button" onmousedown="RichTextEditor.rememberSelection('${id}')" onclick="RichTextEditor.command('${id}','insertUnorderedList')">• Liste</button><button type="button" onmousedown="RichTextEditor.rememberSelection('${id}')" onclick="RichTextEditor.command('${id}','formatBlock','h3')">Titre</button><button type="button" onmousedown="RichTextEditor.rememberSelection('${id}')" onclick="RichTextEditor.createLink('${id}')">Lien</button></div><div id="${id}" class="rich-editor" contenteditable="true" role="textbox" aria-multiline="true" onmouseup="RichTextEditor.rememberSelection('${id}')" onkeyup="RichTextEditor.rememberSelection('${id}')">${this.sanitize(value)}</div></div>`;
  },
  advancedHtml(id,value='',label='Contenu HTML',placeholders=[]){return `<div class="advanced-html-editor" data-advanced-editor="${id}"><header class="advanced-html-header"><label class="doc-label">${SariUtils.escapeHtml(label)}</label><div class="flex flex-wrap gap-1"><button type="button" data-editor-mode="visual" onclick="RichTextEditor.setAdvancedMode('${id}','visual')" class="doc-action active">${i18n.t('visualEditor','Éditeur visuel')}</button><button type="button" data-editor-mode="source" onclick="RichTextEditor.setAdvancedMode('${id}','source')" class="doc-action">${i18n.t('htmlSource','Source HTML')}</button><button type="button" data-editor-mode="preview" onclick="RichTextEditor.setAdvancedMode('${id}','preview')" class="doc-action">${i18n.t('preview','Aperçu')}</button></div></header><div class="advanced-placeholder-bar"><span>${i18n.t('insertPlaceholder','Insérer un attribut')}:</span>${placeholders.map(token=>`<button type="button" onclick="RichTextEditor.insertPlaceholder('${id}','${SariUtils.escapeHtml(token)}')"><code>${SariUtils.escapeHtml(token)}</code></button>`).join('')}</div><div data-editor-panel="visual">${this.html(id,value,'')}</div><textarea id="${id}-source" data-editor-panel="source" class="advanced-html-source hidden" spellcheck="false">${SariUtils.escapeHtml(this.sanitize(value))}</textarea><iframe id="${id}-preview" data-editor-panel="preview" class="advanced-html-preview hidden" sandbox=""></iframe></div>`;},
  setAdvancedMode(id,mode){const wrap=document.querySelector(`[data-advanced-editor="${id}"]`),editor=document.getElementById(id),source=document.getElementById(`${id}-source`),preview=document.getElementById(`${id}-preview`);if(!wrap||!editor||!source||!preview)return;if(mode==='source'&&!source.dataset.dirty)source.value=this.value(id);if(mode==='visual'&&!source.classList.contains('hidden')){editor.innerHTML=this.sanitize(source.value);source.dataset.dirty='';}if(mode==='preview'){const html=source.classList.contains('hidden')?this.value(id):this.sanitize(source.value);preview.srcdoc=`<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;padding:18px;color:#0f172a}img{max-width:100%}</style></head><body>${html}</body></html>`;}wrap.querySelectorAll('[data-editor-panel]').forEach(panel=>panel.classList.toggle('hidden',panel.dataset.editorPanel!==mode));wrap.querySelectorAll('[data-editor-mode]').forEach(button=>button.classList.toggle('active',button.dataset.editorMode===mode));if(mode==='source'){source.oninput=()=>{source.dataset.dirty='true';};source.focus();}else if(mode==='visual')editor.focus();},
  advancedValue(id){const source=document.getElementById(`${id}-source`);return source&&(!source.classList.contains('hidden')||source.dataset.dirty==='true')?this.sanitize(source.value):this.value(id);},
  insertPlaceholder(id,token){const source=document.getElementById(`${id}-source`);if(source&&!source.classList.contains('hidden')){const start=source.selectionStart,end=source.selectionEnd;source.setRangeText(token,start,end,'end');source.dataset.dirty='true';source.focus();return;}const editor=document.getElementById(id);if(editor){editor.focus();this.command(id,'insertText',token);}},
  rememberSelection(id) {
    const editor=document.getElementById(id),selection=window.getSelection();
    if(!editor||!selection?.rangeCount)return;
    const range=selection.getRangeAt(0);
    if(editor.contains(range.commonAncestorContainer))this.selections.set(id,range.cloneRange());
  },
  restoreSelection(id) {
    const range=this.selections.get(id),selection=window.getSelection();
    if(!range||!selection)return;
    selection.removeAllRanges();selection.addRange(range);
  },
  async createLink(id){this.rememberSelection(id);const v=await DialogManager.form('Insérer un lien',[{name:'url',label:'Adresse URL',type:'url',required:true}]);if(v)this.command(id,'createLink',v.url);},
  command(id, command, value = null) { const el=document.getElementById(id);if(!el)return false;el.focus();this.restoreSelection(id);const applied=document.execCommand(command,false,value);this.rememberSelection(id);return applied;},
  applyColor(id,command,value){this.restoreSelection(id);const applied=this.command(id,command,value);if(command==='hiliteColor'&&!applied)this.command(id,'backColor',value);},
  value(id) { return this.sanitize(document.getElementById(id)?.innerHTML || ''); },
  sanitize(html='') { const template=document.createElement('template');template.innerHTML=String(html);template.content.querySelectorAll('script,style,iframe,object,embed').forEach(el=>el.remove());template.content.querySelectorAll('*').forEach(el=>[...el.attributes].forEach(a=>{if(a.name.startsWith('on')||/javascript:/i.test(a.value))el.removeAttribute(a.name);}));return template.innerHTML; }
};
window.RichTextEditor=RichTextEditor;

export {};
