/** Mobile/tablet camera QR & barcode scanner with contextual ERP routing. */
const SariScanner={
  available:false,reader:null,controls:null,pendingRaw:'',context:'lookup',torch:false,product:null,
  t(key,fallback){return i18n?.t?.(key,fallback)||fallback;},
  contexts(){const rows=[
    ['sales','shopping-cart',this.t('scanSales','Vente — ajouter au document'),'sales'],['purchase','receipt-text',this.t('scanPurchase','Achat — ajouter au document'),'purchases'],['inventory_count','clipboard-list',this.t('scanInventoryCount','Comptage inventaire'),'inventoryOps'],['pos','scan-line',this.t('scanPos','POS / vente rapide'),'sales'],['lookup','search',this.t('scanLookup','Recherche produit'),'inventory'],['verify','badge-check',this.t('scanVerify','Vérification document'),'always']
  ];return rows.filter(([, , ,permission])=>permission==='always'||!window.auth||window.auth.can(app.permissionForModule(permission),'view'));},
  async init(){const adaptive=matchMedia('(max-width:1023px)').matches||matchMedia('(pointer:coarse)').matches;if(!adaptive||!navigator.mediaDevices?.getUserMedia){this.available=false;return false;}try{const devices=await navigator.mediaDevices.enumerateDevices();this.available=devices.some(device=>device.kind==='videoinput')||Boolean(navigator.mediaDevices.getSupportedConstraints().facingMode);}catch(_){this.available=false;}if(this.available)this.ensureLaunchButton();window.app?.renderMobileBottomNav?.();return this.available;},
  ensureLaunchButton(){let button=document.getElementById('sari-scanner-fab');if(!button){button=document.createElement('button');button.id='sari-scanner-fab';button.type='button';button.className='scanner-fab no-print';button.onclick=()=>this.open();button.innerHTML='<i data-lucide="scan-line"></i><span>Scan</span>';document.body.appendChild(button);}button.classList.toggle('hidden',!this.available);window.SariIcons?.hydrate();},
  suggestedContext(){return app.activeModule==='sales'?'sales':app.activeModule==='purchases'?'purchase':app.activeModule==='inventoryOps'?'inventory_count':app.activeModule==='inventory'?'lookup':'lookup';},
  open(context=''){this.context=context||this.suggestedContext();let root=document.getElementById('sari-scanner-root');if(!root){root=document.createElement('div');root.id='sari-scanner-root';document.body.appendChild(root);}root.innerHTML=`<div class="scanner-screen"><header><div><span class="sari-badge bg-white/15 text-white">${this.t('smartScanner','Scanner intelligent')}</span><h2>${this.t('scannerTitle','QR code & code-barres')}</h2></div><button type="button" onclick="SariScanner.close()"><i data-lucide="x"></i></button></header><section id="scanner-setup" class="scanner-setup"><label>${this.t('scanContext','Que voulez-vous scanner ?')}<select id="scanner-context" class="doc-input">${this.contexts().map(([value,,label])=>`<option value="${value}" ${this.context===value?'selected':''}>${SariUtils.escapeHtml(label)}</option>`).join('')}</select></label><button type="button" onclick="SariScanner.start()" class="sari-btn scanner-start"><i data-lucide="camera"></i>${this.t('startCamera','Démarrer la caméra')}</button><div class="scanner-manual"><label>${this.t('manualCode','Saisie manuelle')}<input id="scanner-manual-code" class="doc-input" placeholder="EAN, SKU, URL QR…"></label><button type="button" onclick="SariScanner.submitManual()" class="sari-btn"><i data-lucide="check"></i>${this.t('confirm','Confirmer')}</button></div></section><section id="scanner-camera" class="scanner-camera hidden"><video id="scanner-video" autoplay muted playsinline></video><div class="scanner-target"><span></span></div><div class="scanner-camera-actions"><button id="scanner-torch" type="button" class="hidden" onclick="SariScanner.toggleTorch()"><i data-lucide="flashlight"></i>${this.t('torch','Lampe')}</button><button type="button" onclick="SariScanner.stopCamera();document.getElementById('scanner-camera').classList.add('hidden');document.getElementById('scanner-setup').classList.remove('hidden')"><i data-lucide="keyboard"></i>${this.t('manualEntry','Saisie manuelle')}</button></div></section><section id="scanner-result" class="scanner-result hidden"></section></div>`;window.SariIcons?.hydrate();},
  async ensureSalesLocation(context){if(!['sales','pos'].includes(context))return true;let warehouseId=sessionStorage.getItem('sari_scan_warehouse')||window.SalesModule?.state?.selectedWarehouseId||'';if(warehouseId)return true;const warehouses=await sariDB.getAll('warehouses'),values=await DialogManager.form(this.t('selectScanLocation','Sélectionner la caisse / dépôt'),[{name:'warehouseId',label:this.t('warehouse','Dépôt / caisse'),type:'select',options:warehouses.map(item=>({value:item.id,label:item.name}))}]);if(!values)return false;sessionStorage.setItem('sari_scan_warehouse',values.warehouseId);if(window.SalesModule)SalesModule.state.selectedWarehouseId=values.warehouseId;return true;},
  async start(){this.context=document.getElementById('scanner-context')?.value||'lookup';if(!await this.ensureSalesLocation(this.context))return;document.getElementById('scanner-setup')?.classList.add('hidden');document.getElementById('scanner-camera')?.classList.remove('hidden');try{const {BrowserMultiFormatReader}=await import('@zxing/browser');this.reader=new BrowserMultiFormatReader();const video=document.getElementById('scanner-video');this.controls=await this.reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}},video,(result)=>{if(result&&!this.pendingRaw)this.onDetected(result.getText());});setTimeout(()=>this.setupTorch(),500);}catch(error){console.error('[Scanner camera]',error);this.showMessage('warning',this.t('cameraUnavailable','Caméra indisponible. Utilisez la saisie manuelle.'),error.message);this.stopCamera();}},
  setupTorch(){const video=document.getElementById('scanner-video'),track=video?.srcObject?.getVideoTracks?.()[0],capabilities=track?.getCapabilities?.()||{},button=document.getElementById('scanner-torch');this.track=track;if(button)button.classList.toggle('hidden',!capabilities.torch);},
  async toggleTorch(){if(!this.track)return;this.torch=!this.torch;try{await this.track.applyConstraints({advanced:[{torch:this.torch}]});document.getElementById('scanner-torch')?.classList.toggle('active',this.torch);}catch(_){this.torch=false;}},
  stopCamera(){try{this.controls?.stop?.();}catch(_){}try{this.reader?.reset?.();}catch(_){}this.controls=null;this.reader=null;this.track=null;this.torch=false;},
  onDetected(raw){this.pendingRaw=String(raw||'').trim();this.stopCamera();const box=document.getElementById('scanner-result');if(!box)return;document.getElementById('scanner-camera')?.classList.add('hidden');box.classList.remove('hidden');box.innerHTML=`<div class="scanner-last-result"><span>${this.t('lastScanned','Dernier résultat scanné')}</span><strong>${SariUtils.escapeHtml(this.pendingRaw)}</strong></div><div class="flex gap-2"><button type="button" onclick="SariScanner.confirmResult()" class="sari-btn bg-sari-lime text-slate-900"><i data-lucide="check-circle-2"></i>${this.t('confirmAction','Confirmer l’action')}</button><button type="button" onclick="SariScanner.retry()" class="sari-btn bg-slate-200"><i data-lucide="refresh-cw"></i>${this.t('scanAgain','Scanner à nouveau')}</button></div>`;window.SariIcons?.hydrate();},
  submitManual(){const value=document.getElementById('scanner-manual-code')?.value.trim();if(value)this.onDetected(value);},retry(){this.pendingRaw='';document.getElementById('scanner-result')?.classList.add('hidden');document.getElementById('scanner-setup')?.classList.remove('hidden');},
  async confirmResult(){const raw=this.pendingRaw;if(!raw)return;const verification=this.parseVerification(raw),products=await sariDB.getAll('products'),candidate=verification?.code||raw,normalized=String(candidate).toLowerCase(),product=products.find(item=>[item.barcode,item.sku,item.referenceCode,item.id].some(value=>String(value||'').toLowerCase()===normalized));if(this.context==='verify')return this.verifyDocument(raw,verification);if(product)return this.routeProduct(product);if(verification)return this.verifyDocument(raw,verification);return this.showUnknown(raw);},
  parseVerification(raw){try{const url=new URL(raw,location.origin);if(!/verification/i.test(url.pathname))return null;const parts=url.pathname.split('/').filter(Boolean),hash=parts.at(-1)||'',code=decodeURIComponent(parts.at(-2)||'');return{url:url.href,code,hash};}catch(_){return null;}},
  async routeProduct(product){const context=this.context;if(['sales','pos'].includes(context)){await app.navigate('sales');if(sessionStorage.getItem('sari_scan_warehouse'))SalesModule.state.selectedWarehouseId=sessionStorage.getItem('sari_scan_warehouse');SalesModule.addToCart(product.id);this.close();return;}if(context==='purchase'){await app.navigate('purchases');if(!PurchasesModule.state.editing)await PurchasesModule.openEditor('','purchase_order');PurchasesModule.addProduct(product);this.close();return;}if(context==='inventory_count'){await app.navigate('inventoryOps');const count=InventoryOpsModule.state.editingCount,line=count?.lines?.find(item=>item.productId===product.id);if(line){line.counted=Number(line.counted||0)+1;line.variance=line.counted-Number(line.expected||0);InventoryOpsModule.renderCountEditor();app.showToast(`+1 ${product.name}`,'success');this.close();}else this.showMessage('warning',this.t('openInventoryCountFirst','Ouvrez d’abord un comptage contenant ce produit.'),product.name);return;}await app.navigate('inventory');await InventoryModule.openDetail(product.id);this.close();},
  async verificationRecord(code){const stores=['orders','purchaseDocuments','payslips','employmentContracts','workCertificates','documents'];for(const store of stores){const rows=await sariDB.getAll(store),record=rows.find(item=>[item.referenceCode,item.id].includes(code));if(record)return{store,record};}return null;},
  async verifyDocument(raw,parsed=this.parseVerification(raw)){if(!parsed)return this.showUnknown(raw);try{const response=await fetch(`/api/verification?code=${encodeURIComponent(parsed.code)}&hash=${encodeURIComponent(parsed.hash)}`,{cache:'no-store'}),result=await response.json(),local=await this.verificationRecord(parsed.code);this.showVerification({...result,url:parsed.url,local});}catch(error){this.showVerification({valid:false,reason:this.t('verificationServerUnavailable','Serveur de vérification inaccessible'),url:parsed.url,error:error.message});}},
  showVerification(result){this.pendingLink=result.url||'';const box=document.getElementById('scanner-result');if(!box)return;const record=result.local?.record||{},valid=Boolean(result.valid);box.classList.remove('hidden');box.innerHTML=`<article class="verification-result ${valid?'valid':'invalid'}"><i data-lucide="${valid?'badge-check':'shield-x'}"></i><h2>${valid?this.t('authenticDocument','Document authentique'):this.t('invalidDocument','Document invalide / introuvable')}</h2><p>${SariUtils.escapeHtml(result.reason||'')}</p>${valid?`<dl><dt>${this.t('documentType','Type')}</dt><dd>${SariUtils.escapeHtml(result.documentType||result.local?.store||'Document')}</dd><dt>${this.t('reference','Référence')}</dt><dd>${SariUtils.escapeHtml(result.code||record.referenceCode||record.id||'')}</dd><dt>${this.t('issuingCompany','Société émettrice')}</dt><dd>${SariUtils.escapeHtml(result.company||'SARI Système')}</dd><dt>${this.t('date','Date')}</dt><dd>${i18n.formatDate(record.createdAt||record.signedAt||record.paymentDate)}</dd><dt>${this.t('summary','Résumé')}</dt><dd>${SariUtils.escapeHtml(record.title||record.employeeName||record.customerName||record.supplierName||'Document vérifié')}</dd></dl>`:''}<div class="flex flex-wrap gap-2"><button type="button" onclick="SariScanner.copyValue(SariScanner.pendingLink)" class="sari-btn"><i data-lucide="copy"></i>${this.t('copyLink','Copier le lien')}</button>${result.url?`<a href="${SariUtils.escapeHtml(result.url)}" target="_blank" rel="noopener" class="sari-btn"><i data-lucide="external-link"></i>${this.t('openLink','Ouvrir le lien')}</a>`:''}</div></article>`;window.SariIcons?.hydrate();},
  showUnknown(raw){const isUrl=(()=>{try{return Boolean(new URL(raw));}catch(_){return false;}})(),box=document.getElementById('scanner-result');box.classList.remove('hidden');box.innerHTML=`<article class="scanner-unknown"><i data-lucide="circle-help"></i><h3>${this.t('unknownCode','Code inconnu ou externe')}</h3><pre>${SariUtils.escapeHtml(raw)}</pre><div class="flex gap-2"><button type="button" onclick="SariScanner.copyValue(SariScanner.pendingRaw)" class="sari-btn"><i data-lucide="copy"></i>${this.t('copy','Copier')}</button>${isUrl?`<a href="${SariUtils.escapeHtml(raw)}" target="_blank" rel="noopener" class="sari-btn"><i data-lucide="external-link"></i>${this.t('openUrl','Ouvrir l’URL')}</a>`:''}</div></article>`;window.SariIcons?.hydrate();},
  async copyValue(value){try{await navigator.clipboard.writeText(String(value||''));app.showToast(this.t('copied','Copié'),'success');}catch(_){app.showToast(this.t('copyFailed','Copie impossible'),'warning');}},
  showMessage(type,title,message=''){const box=document.getElementById('scanner-result');if(!box)return;document.getElementById('scanner-camera')?.classList.add('hidden');box.classList.remove('hidden');box.innerHTML=`<article class="scanner-message ${type}"><i data-lucide="triangle-alert"></i><h3>${SariUtils.escapeHtml(title)}</h3><p>${SariUtils.escapeHtml(message)}</p><button onclick="SariScanner.retry()" class="sari-btn">${this.t('back','Retour')}</button></article>`;window.SariIcons?.hydrate();},
  close(){this.stopCamera();document.getElementById('sari-scanner-root')?.remove();this.pendingRaw='';}
};
window.SariScanner=SariScanner;
export {};
