'use strict';

const fs=require('fs');const path=require('path');const crypto=require('crypto');
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return{salt,hash:crypto.scryptSync(String(password),salt,64).toString('hex')};}
function secureToken(){return crypto.randomBytes(32).toString('base64url');}function tokenHash(token){return crypto.createHash('sha256').update(String(token)).digest('hex');}
function securePassword(length=18){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';let out='';for(let i=0;i<length;i++)out+=chars[crypto.randomInt(chars.length)];return out;}
class AuthVault{
  constructor(root){this.file=path.join(root,'.runtime','auth-vault.json');this.bootstrapFile=path.join(root,'secure','auth-bootstrap.json');this.bootstrap=JSON.parse(fs.readFileSync(this.bootstrapFile,'utf8'));this.data=this.load();}
  defaults(){return{version:1,settings:{showDemoAccounts:true,demoAccountsEnabled:true,activationQrSize:190},users:this.bootstrap.users.map(user=>({...user,isActive:true,email:'',employeeId:'',permissionOverrides:[],createdAt:new Date().toISOString()})),requests:[],tokens:[]};}
  load(){try{const defaults=this.defaults(),stored=JSON.parse(fs.readFileSync(this.file,'utf8'));return{...defaults,...stored,settings:{...defaults.settings,...(stored.settings||{})}};}catch(_){const value=this.defaults();this.persist(value);return value;}}
  persist(value=this.data){fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=`${this.file}.${process.pid}.tmp`;fs.writeFileSync(tmp,JSON.stringify(value,null,2),{mode:0o600});fs.renameSync(tmp,this.file);try{fs.chmodSync(this.file,0o600);}catch(_){}this.data=value;}
  public(user){if(!user)return null;const{salt,hash,...safe}=user;return safe;}
  list(){return this.data.users.map(user=>this.public(user));}find(value){return this.data.users.find(user=>user.id===value||user.username===String(value).toLowerCase()||user.email&&user.email.toLowerCase()===String(value).toLowerCase());}
  verify(username,password){const user=this.find(String(username).toLowerCase());if(!user||!user.isActive||(user.isDemo&&!this.data.settings.demoAccountsEnabled))return null;const candidate=crypto.scryptSync(String(password),user.salt,64),expected=Buffer.from(user.hash,'hex');return candidate.length===expected.length&&crypto.timingSafeEqual(candidate,expected)?user:null;}
  create(input){if(this.find(input.username))throw Error('Username already exists');const password=input.password||securePassword(),credentials=hashPassword(password),user={id:`usr-${crypto.randomUUID()}`,username:String(input.username).trim().toLowerCase(),name:String(input.name||input.username),email:String(input.email||''),description:String(input.description||''),role:input.role||'readonly',employeeId:input.employeeId||'',permissionOverrides:input.permissionOverrides||[],isDemo:false,isActive:input.isActive!==false,activationRequired:Boolean(input.activationRequired),...credentials,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};this.data.users.push(user);this.persist();return{user:this.public(user),temporaryPassword:password};}
  update(id,input){const user=this.find(id);if(!user)throw Error('User not found');for(const field of ['name','email','description','role','employeeId','permissionOverrides','isActive'])if(input[field]!==undefined)user[field]=input[field];if(input.username&&input.username!==user.username){if(this.find(input.username))throw Error('Username already exists');user.username=String(input.username).toLowerCase();}if(input.password)Object.assign(user,hashPassword(input.password));user.updatedAt=new Date().toISOString();this.persist();return this.public(user);}
  delete(id){const user=this.find(id);if(!user)throw Error('User not found');if(user.username==='admin')throw Error('The primary Administrator cannot be deleted');this.data.users=this.data.users.filter(item=>item.id!==user.id);this.persist();return{deleted:true,id:user.id};}
  touchLogin(id){const user=this.find(id);if(user){user.lastLoginAt=new Date().toISOString();this.persist();}}
  settings(input){if(input){Object.assign(this.data.settings,input);this.persist();}return{...this.data.settings};}
  requestReset(identifier,requestMeta={}){const user=this.find(identifier),existing=this.data.requests.find(item=>item.status==='pending'&&((user&&item.userId===user.id)||(!user&&item.username===String(identifier))));if(existing)return{id:existing.id,status:'pending'};const request={id:`reset-${crypto.randomUUID()}`,userId:user?.id||'',username:user?.username||String(identifier),email:user?.email||'',status:'pending',requestedAt:new Date().toISOString(),requestMeta};this.data.requests.push(request);this.persist();return{id:request.id,status:'pending'};}
  requests(){return this.data.requests.map(request=>({...request}));}
  issueToken(userId,purpose='reset'){const raw=secureToken(),entry={id:`token-${crypto.randomUUID()}`,userId,purpose,hash:tokenHash(raw),createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+24*60*60*1000).toISOString(),usedAt:null};this.data.tokens.push(entry);this.persist();return{raw,entry};}
  rejectRequest(id){const request=this.data.requests.find(item=>item.id===id);if(!request)throw Error('Request not found');request.status='rejected';request.processedAt=new Date().toISOString();request.processedBy='admin';this.persist();return{...request};}
  approveRequest(id,baseUrl){const request=this.data.requests.find(item=>item.id===id);if(!request)throw Error('Request not found');if(!request.userId)throw Error('No user matches this request');const issued=this.issueToken(request.userId,'reset');request.status='approved';request.processedAt=new Date().toISOString();request.processedBy='admin';this.persist();return{request:{...request},link:`${baseUrl}/?reset=${encodeURIComponent(issued.raw)}`};}
  issueActivation(userId,baseUrl){const issued=this.issueToken(userId,'activation');return{link:`${baseUrl}/?activation=${encodeURIComponent(issued.raw)}`};}
  validateToken(raw){const hash=tokenHash(raw),entry=this.data.tokens.find(item=>item.hash===hash&&!item.usedAt&&new Date(item.expiresAt)>new Date());return entry?{valid:true,purpose:entry.purpose,userId:entry.userId,expiresAt:entry.expiresAt}:{valid:false};}
  consumeToken(raw,password){const status=this.validateToken(raw);if(!status.valid)throw Error('Invalid or expired activation/reset link');const entry=this.data.tokens.find(item=>item.hash===tokenHash(raw));const user=this.find(entry.userId);Object.assign(user,hashPassword(password),{isActive:true,activationRequired:false,updatedAt:new Date().toISOString()});entry.usedAt=new Date().toISOString();this.persist();return this.public(user);}
}
module.exports={AuthVault,hashPassword,securePassword,tokenHash};
