import { afterEach, describe, expect, it } from 'vitest';
import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);const{AuthVault}=require('../auth-vault.js');const{resetAdministrator}=require('../scripts/reset-admin-password.js');const roots:string[]=[];
function createRoot(){const root=mkdtempSync(join(tmpdir(),'sari-auth-'));roots.push(root);mkdirSync(join(root,'secure'));cpSync(join(process.cwd(),'secure','auth-bootstrap.json'),join(root,'secure','auth-bootstrap.json'));return root;}
afterEach(()=>roots.splice(0).forEach(root=>rmSync(root,{recursive:true,force:true})));
describe('private authentication vault',()=>{
 it('stores only password hashes in a mode-protected runtime file',()=>{const root=createRoot(),vault=new AuthVault(root),raw=readFileSync(join(root,'.runtime','auth-vault.json'),'utf8');expect(raw).not.toContain('Sari@2026');expect(vault.verify('admin','Sari@2026')?.role).toBe('admin');});
 it('supports administrator-created users, activation tokens and manual reset queue',()=>{const root=createRoot(),vault=new AuthVault(root),created=vault.create({username:'newuser',name:'New User',description:'Institutional sales account',role:'sales',employeeId:'emp-1'});expect(created.user.description).toBe('Institutional sales account');expect(created.temporaryPassword).toHaveLength(18);const activation=vault.issueActivation(created.user.id,'http://localhost:3000');const token=new URL(activation.link).searchParams.get('activation')!;expect(vault.validateToken(token).valid).toBe(true);vault.consumeToken(token,'NewSecure!2026');expect(vault.verify('newuser','NewSecure!2026')).toBeTruthy();expect(vault.requestReset('newuser').status).toBe('pending');});
 it('can hide and deactivate all demo accounts without disabling the primary admin',()=>{const root=createRoot(),vault=new AuthVault(root);vault.settings({showDemoAccounts:false,demoAccountsEnabled:false});expect(vault.verify('sales','Sari@2026')).toBeNull();expect(vault.verify('admin','Sari@2026')).toBeTruthy();});
 it('resets only the Administrator password and live servers reload the changed vault',()=>{const root=createRoot(),liveVault=new AuthVault(root),before=liveVault.list().length,result=resetAdministrator(root,'RecoveryPassword!2026'),vault=new AuthVault(root),raw=readFileSync(join(root,'.runtime','auth-vault.json'),'utf8');expect(result.generated).toBe(false);expect(vault.verify('admin','RecoveryPassword!2026')).toBeTruthy();expect(liveVault.verify('admin','RecoveryPassword!2026')).toBeTruthy();expect(vault.verify('sales','Sari@2026')).toBeTruthy();expect(vault.list()).toHaveLength(before);expect(raw).not.toContain('RecoveryPassword!2026');});
});
