import {describe,expect,it} from 'vitest';
import {readFileSync} from 'node:fs';import {join} from 'node:path';
const source=(file:string)=>readFileSync(join(process.cwd(),file),'utf8');
describe('dynamic uploaded application logo branding',()=>{
  it('uses the uploaded site logo on login and the application shell',()=>{const html=source('index.html');expect(html).toContain('id="sari-login-logo"');expect(html.match(/data-sari-site-logo/g)?.length).toBeGreaterThanOrEqual(2);expect(html.match(/data-sari-default-logo/g)?.length).toBeGreaterThanOrEqual(2);expect(html).toContain('id="login-company-name"');});
  it('updates favicon and apple touch icon from the same uploaded logo',()=>{const html=source('index.html'),app=source('js/app.js');expect(html).toContain('id="sari-favicon"');expect(html).toContain('id="sari-apple-touch-icon"');expect(app).toContain("favicon.href=logo||defaultIcon");expect(app).toContain("apple.href=logo||defaultIcon");expect(app).toContain("localStorage.setItem('sari_site_logo',logo)");});
  it('loads branding before authentication and delegates settings updates',()=>{const auth=source('js/auth.js'),settings=source('js/modules/settings.js');expect(auth).toContain('loadLoginBranding');expect(auth).toContain("getById('settings','app-settings')");expect(auth.indexOf('await this.loadLoginBranding()')).toBeLessThan(auth.indexOf('await this.loadPublicAuthSettings()'));expect(settings).toContain('window.app?.applyBranding?.(settings)');});
  it('uses configured company name and subtitle on login and ERP header',()=>{const html=source('index.html'),app=source('js/app.js'),settings=source('js/modules/settings.js');for(const id of ['login-company-name','login-company-subtitle','header-company-name','header-company-subtitle'])expect(html).toContain(`id="${id}"`);expect(app).toContain("has('companySubtitle')&&settings.companySubtitle");expect(app).toContain("'header-company-name':companyName");expect(app).toContain("'header-company-subtitle':companySubtitle");expect(app).toContain("'login-company-subtitle':companySubtitle");expect(settings).toContain('this.applyBranding(newSettings)');});
  it('keeps the configured legal company name authoritative over portable defaults',()=>{const app=source('js/app.js'),settings=source('js/modules/settings.js');expect(app).toContain('this.applyBranding({ ...portableSettings, ...(brandingSettings || {}) })');expect(app).toContain("'header-company-name':companyName");expect(app).toContain("'login-company-name':companyName");expect(settings).toContain("companyName: document.getElementById('cfg-name').value.trim()");expect(source('index.html')).not.toContain('id="header-company-name" class="text-base font-black text-slate-900 dark:text-white tracking-tight" data-i18n');});
  it('hydrates cached company identity before async authentication and IndexedDB work',()=>{const app=source('js/app.js'),auth=source('js/auth.js');expect(app).toContain('cachedBranding()');expect(app).toContain("localStorage.getItem('sari_branding_identity')");expect(app).toContain("localStorage.setItem('sari_branding_identity'");expect(app).toContain('app.applyCachedBranding();');expect(app.indexOf('app.applyCachedBranding();')).toBeLessThan(app.indexOf("window.addEventListener('DOMContentLoaded'"));expect(auth).toContain('window.app?.applyCachedBranding?.()');});
});
