import {describe,expect,it} from 'vitest';
import {readFileSync} from 'node:fs';import {join} from 'node:path';
const source=(file:string)=>readFileSync(join(process.cwd(),file),'utf8');
describe('GED local disk storage',()=>{
  it('writes document bytes under GED/document-type and returns metadata paths',()=>{const server=source('server.js');expect(server).toContain("const GED_ROOT=path.join(__dirname,'GED')");expect(server).toContain("pathname==='/api/ged/files'");expect(server).toContain("documentType='autre'");expect(server).toContain('fs.writeFileSync(target,buffer)');expect(server).toContain('diskPath');expect(source('.gitignore')).toContain('GED/');});
  it('stores only disk metadata in IndexedDB when the server is available',()=>{const db=source('js/db.js');expect(db).toContain('persistDocumentToDisk');expect(db).toContain("data:''");expect(db).toContain("storageMode:'disk'");expect(db).toContain('migrateGedDocumentsToDisk');expect(source('js/app.js')).toContain('migrateGedDocumentsToDisk');});
  it('previews, downloads and deletes disk-backed documents',()=>{const documents=source('js/documents.js'),db=source('js/db.js'),ged=source('js/modules/ged.js');expect(documents).toContain('doc?.storagePath');expect(documents).toContain("!doc?.data&&!doc?.storagePath");expect(db).toContain('removeDocumentFromDisk');expect(ged).toContain('(doc.data||doc.storagePath)');});
  it('keeps an explicit IndexedDB fallback only while offline',()=>{const db=source('js/db.js');expect(db).toContain("storageMode:'indexeddb-fallback'");expect(db).toContain('Disk storage unavailable');});
  it('names and renames physical files as CODE-UNIQUE_ID.extension while syncing DB metadata',()=>{const server=source('server.js'),db=source('js/db.js'),documents=source('js/documents.js');expect(server).toContain("code=safeGedPart(fileCode||base||'GED').toUpperCase()");expect(server).toContain('file=`${code}-${suffix}${extension}`');expect(server).toContain("req.method==='PATCH'");expect(server).toContain('fs.renameSync');expect(db).toContain('syncDocumentDiskMetadata');expect(db).toContain('fileNamingVersion:2');expect(db).toContain('fileName:result.fileName');expect(documents).toContain('ged-edit-file-code');expect(documents).toContain('doc.fileName||doc.name');});
});
