import {describe,expect,it} from 'vitest';import {readFileSync} from 'node:fs';import {join} from 'node:path';
const source=(file:string)=>readFileSync(join(process.cwd(),file),'utf8');
describe('Section 350 stable responsive topbar',()=>{
  it('marks the header into stable brand and action zones',()=>{const html=source('index.html');for(const cls of ['sari-topbar','topbar-brand-zone','topbar-brand','topbar-logo-shell','topbar-actions','topbar-profile','topbar-overflow-wrap'])expect(html).toContain(cls);expect(html).toContain('id="topbar-hamburger"');});
  it('locks logo hamburger and icon proportions against flex shrinking',()=>{const css=source('css/styles.css');expect(css).toContain('.topbar-brand-zone,.topbar-brand,.topbar-logo-shell,.topbar-hamburger,.topbar-actions');expect(css).toContain('flex-shrink:0');expect(css).toContain('min-width:44px');expect(css).toContain('min-height:44px');expect(css).toContain('object-fit:contain');});
  it('repositions or hides secondary controls instead of squishing',()=>{const css=source('css/styles.css'),app=source('js/app.js'),html=source('index.html');expect(css).toContain('@media(max-width:1180px)');expect(css).toContain('.topbar-secondary,[data-topbar-secondary]{display:none!important}');expect(css).toContain("grid-template-areas:'brand primary' 'actions actions'");expect(html).toContain('id="topbar-overflow-menu"');expect(app).toContain('toggleTopbarOverflow');expect(app).toContain('closeTopbarOverflow');});
  it('uses readable minimum typography and fluid headings',()=>{const css=source('css/styles.css');expect(css).toContain('body{font-size:max(14px,1rem)}');expect(css).toContain('.sari-btn,.doc-action,.sari-sidebar-item,.sari-nav-label{font-size:max(13px');expect(css).toContain('h1{font-size:clamp(');expect(css).toContain('body{font-size:16px}');});
  it('contains explicit breakpoint regression coverage',()=>{const e2e=source('e2e/responsive.spec.ts');for(const width of [320,375,768,1024,1280])expect(e2e).toContain(String(width));expect(e2e).toContain('topbar keeps fixed proportions');expect(e2e).toContain('overflow at ${width}px');});
});
