import {describe,expect,it} from 'vitest';
import {readFileSync} from 'node:fs';import {join} from 'node:path';
const source=(file:string)=>readFileSync(join(process.cwd(),file),'utf8');
describe('advanced HR document layouts, templates and multi-RC fiscal sources',()=>{
  it('ships drag/drop advanced contract articles with placeholders and notes',()=>{const editor=source('js/hr-template-editors.js'),contracts=source('js/modules/contracts.js');expect(editor).toContain('draggable="true"');expect(editor).toContain('Haut du contenu');expect(editor).toContain('Notes et clauses particulières');expect(editor).toContain('{{employee.birthDate}}');expect(editor).toContain('{{position.tasks}}');expect(contracts).toContain('mergeHrVariables');expect(contracts).toContain('employee.dateOfBirth');expect(contracts).toContain('employee.postalAddress');expect(editor).toContain('automaticContractArticles');expect(editor).toContain('Générer les clauses légales');expect(editor).toContain('Ordre ${i+1}');});
  it('supports structured declaration steps/questions/commitments and all requested controls',()=>{const editor=source('js/hr-template-editors.js'),contracts=source('js/modules/contracts.js');for(const type of ['text','checkbox','radio','textarea','html'])expect(editor).toContain(`'${type}'`);expect(editor).toContain('expectedResult');expect(editor).toContain("sortBlock('steps'");expect(editor).toContain("sortBlock('commitments'");expect(contracts).toContain('renderDeclarationTemplateQuestion');});
  it('renders modern RTL/LTR HR headers with employee identity and safe spacing',()=>{const contracts=source('js/modules/contracts.js'),css=source('src/styles.css'),db=source('js/db.js');expect(contracts).toContain('modernHrHeader');expect(contracts).toContain("i18n.currentLang==='ar'");expect(css).toContain('.modern-hr-header[dir="rtl"]');expect(css).toContain('padding-bottom:30mm');expect(db).toContain('{{employeeHeader}}');expect(db).toContain('{{documentDirection}}');});
  it('manages one principal/default RC and document-level fiscal source selection',()=>{const commerce=source('js/modules/commerce-direction.js'),settings=source('js/modules/settings.js'),contracts=source('js/modules/contracts.js');expect(commerce).toContain("registerKind==='principal'");expect(commerce).toContain('item.registerKind=\'annexe\'');expect(commerce).toContain('item.isDefault=false');expect(settings).toContain('cfg-rc-autocomplete');expect(settings).toContain('applyTradeRegister');expect(contracts).toContain('ctt-fiscal-source');expect(contracts).toContain('fiscalContext');expect(contracts).toContain('showFiscalInfo');expect(source('js/modules/payslips.js')).toContain('payslip-rc');});
  it('adds translated employee payslip filters and configurable fiscal visibility',()=>{const portal=source('js/modules/portal.js'),payslips=source('js/modules/payslips.js'),settings=source('js/modules/settings.js');expect(portal).toContain('portalPayslipsHtml');expect(portal).toContain('payslipFrom');expect(portal).toContain('payslipTo');expect(payslips).toContain('payslip-show-fiscal');expect(payslips).toContain('registerFor(record)');expect(settings).toContain('cfg-show-fiscal-hr');for(const lang of ['fr','en','ar']){const pack=JSON.parse(source(`content/translations/${lang}.json`));expect(pack.portalMyPayslips).toBeTruthy();expect(pack.portalMyDocuments).toBeTruthy();}});
  it('provides full employee consultations and professional advanced HTML controls',()=>{const portal=source('js/modules/portal.js'),editor=source('js/rich-editor.js'),utils=source('js/utils.js');expect(portal).toContain('PayslipsModule.view(id)');expect(portal).toContain('viewMyCertificate');expect(portal).toContain('styledConsultation');for(const command of ['insertOrderedList','justifyCenter','insertImage','resizeSelectedImage','insertTable','insertCustomPlaceholder'])expect(editor).toContain(command);expect(editor).toContain('image-plus');expect(editor).toContain('fontSize');expect(utils).toContain('headerGap=12,footerGap=14');});
  it('manages personalized contract/certificate designs and non-overlapping optional pagination',()=>{const editor=source('js/hr-template-editors.js'),contracts=source('js/modules/contracts.js'),utils=source('js/utils.js');for(const field of ['ctpl-header','ctpl-footer','ctpl-accent','ctpl-font','ctpl-pagination','atpl-header','atpl-body','atpl-footer','atpl-pagination'])expect(editor).toContain(field);expect(contracts).toContain('duplicateHrTemplate');expect(contracts).toContain('data-show-pagination');expect(contracts).toContain('custom-hr-template-footer');expect(utils).toContain("element.dataset.showPagination!=='false'");expect(utils).toContain('Page ${page} sur ${totalPages}');expect(utils).toContain("align:'center'");});
  it('opens the exact standard payslip consultation and keeps compact consultation print on one page',()=>{const portal=source('js/modules/portal.js'),payslips=source('js/modules/payslips.js'),db=source('js/db.js'),utils=source('js/utils.js');expect(portal).toContain("SariModuleLoader?.load('payslips')");expect(portal).toContain('PayslipsModule.loadData()');expect(portal).toContain('PayslipsModule.view(id)');expect(payslips).toContain('async loadData()');expect(db).toContain('consultationStyleVersion:6');for(const field of ['baseSalaryCard','grossSalaryCard','totalDeductionsCard','netPayableCard','workedDaysCard','workedHoursCard','leaveBalanceCard','paymentCard'])expect(payslips).toContain(field);expect(db).toContain('compactLayoutVersion=2');expect(utils).toContain('bottomMargin=26');});
  it('renders the requested framed payslip v4 with a dark title and one-page footer',()=>{const db=source('js/db.js'),css=source('src/styles.css');expect(db).toContain('consultation-v4-company');expect(db).toContain('consultation-v4-title');expect(db).toContain('FICHE DE PAIE');expect(db).toContain('{{companyFiscal}}');expect(db).toContain('{{employeePeriodHeader}}');expect(css).toContain('background:#222;color:#fff');expect(css).toContain('height:270mm');expect(css).toContain('margin-top:auto');});
  it('adds employee address, detailed pay-period bounds, notice date and optional notes',()=>{const payslips=source('js/modules/payslips.js'),db=source('js/db.js');expect(payslips).toContain('employee.postalAddress');expect(payslips).toContain('periodBounds');expect(payslips).toContain('payslip-notice-date');expect(payslips).toContain('noticeDateValue');expect(payslips).toContain('payslipNotes');expect(db).toContain('{{payPeriodRange}}');expect(db).toContain('{{noticeDateValue}}');expect(db).toContain('{{payslipNotes}}');expect(db).toContain('consultationStyleVersion:6');});
  it('loads every professional-editor icon and applies compact IBM PDF typography',()=>{const icons=source('src/icon-set.ts'),editor=source('js/rich-editor.js'),css=source('src/styles.css');for(const icon of ['Undo2','Redo2','Bold','Italic','Underline','Strikethrough','Highlighter','ListOrdered','AlignCenter','IndentIncrease','ImagePlus','Table2','Eraser'])expect(icons).toContain(icon);expect(editor).toContain('queueHydrate');expect(css).toContain('IBM Plex Mono');expect(css).toContain('margin-top:2mm!important');});
  it('normalizes and enlarges generated payslip table values and row heights',()=>{const css=source('src/styles.css');expect(css).toContain('table-layout:fixed');expect(css).toContain('height:6.6mm');expect(css).toContain('font-size:10.5px!important');expect(css).toContain('font-variant-numeric:tabular-nums');expect(css).toContain('vertical-align:middle!important');});
  it('configures fonts independently inside contract, certificate and payslip sections',()=>{const contracts=source('js/modules/contracts.js'),payslips=source('js/modules/payslips.js'),settings=source('js/modules/settings.js');expect(contracts).toContain('id="ctt-font"');expect(contracts).toContain('onContractTemplateChange');expect(contracts).toContain("name:'fontFamily'");expect(contracts).toContain('contractDefaultFont');expect(contracts).toContain('certificateDefaultFont');expect(contracts).toContain('Police par défaut des contrats');expect(contracts).toContain('Police par défaut des attestations');expect(payslips).toContain('payslipDefaultFont');expect(payslips).toContain('Police par défaut des fiches de paie');expect(settings).not.toContain('id="cfg-default-hr-font"');});
});
