import {describe,expect,it} from 'vitest';import {readFileSync} from 'node:fs';import {join} from 'node:path';
const source=(file:string)=>readFileSync(join(process.cwd(),file),'utf8');
describe('Sections 348–349 adaptive mobile layer and smart scanner',()=>{
  it('provides desktop/tablet/mobile context-aware navigation',()=>{const app=source('js/app.js'),html=source('index.html'),css=source('css/styles.css');expect(app).toContain("form=width<=640?'mobile':width<=1023?'tablet':'desktop'");expect(app).toContain('mobileShortcutCandidates');expect(app).toContain('window.auth.can');expect(html).toContain('id="sari-mobile-bottom-nav"');expect(css).toContain('.mobile-bottom-nav');expect(css).toContain('body[data-form-factor="tablet"] .sari-sidebar');});
  it('detects mobile cameras and hides scanner controls when unavailable',()=>{const scanner=source('js/scanner.js');expect(scanner).toContain("enumerateDevices()");expect(scanner).toContain("device.kind==='videoinput'");expect(scanner).toContain("if(this.available)this.ensureLaunchButton()");expect(scanner).toContain("classList.toggle('hidden',!this.available)");expect(source('server.js')).toContain("camera=(self)");});
  it('supports all requested scanner contexts and product routes',()=>{const scanner=source('js/scanner.js');for(const context of ['sales','purchase','inventory_count','pos','lookup','verify'])expect(scanner).toContain(`['${context}'`);expect(scanner).toContain('SalesModule.addToCart');expect(scanner).toContain('PurchasesModule.addProduct');expect(scanner).toContain('line.counted=Number(line.counted||0)+1');expect(scanner).toContain('InventoryModule.openDetail');expect(scanner).toContain("[item.barcode,item.sku,item.referenceCode,item.id]");});
  it('uses ZXing multi-format camera scanning, torch and manual fallback',()=>{const scanner=source('js/scanner.js'),pkg=JSON.parse(source('package.json'));expect(pkg.dependencies['@zxing/browser']).toBeTruthy();expect(scanner).toContain("import('@zxing/browser')");expect(scanner).toContain('BrowserMultiFormatReader');expect(scanner).toContain("facingMode:{ideal:'environment'}");expect(scanner).toContain('capabilities.torch');expect(scanner).toContain('applyConstraints');expect(scanner).toContain('scanner-manual-code');});
  it('classifies verification and unknown QR codes into styled results',()=>{const scanner=source('js/scanner.js'),server=source('server.js');expect(scanner).toContain('parseVerification');expect(scanner).toContain("fetch(`/api/verification?code=");expect(scanner).toContain('verification-result');expect(scanner).toContain('showUnknown');expect(scanner).toContain('navigator.clipboard.writeText');expect(server).toContain("pathname==='/api/verification'");expect(server).toContain('verificationHash(code)');});
  it('ships complete trilingual scanner strings',()=>{const keys=['scan','smartScanner','scannerTitle','scanContext','scanSales','scanPurchase','scanInventoryCount','scanPos','scanLookup','scanVerify','startCamera','manualCode','torch','authenticDocument','invalidDocument','unknownCode'];for(const lang of ['fr','en','ar']){const pack=JSON.parse(source(`content/translations/${lang}.json`));for(const key of keys)expect(pack[key],`${lang}:${key}`).toBeTruthy();}});
  it('configures installable Android/iOS PWA branding and splash colors',()=>{for(const file of ['manifest.json','public/manifest.json']){const manifest=JSON.parse(source(file));expect(manifest.display).toBe('standalone');expect(manifest.background_color).toBe('#009CC5');expect(manifest.theme_color).toBe('#009CC5');expect(manifest.orientation).toBe('any');expect(manifest.icons.some((icon:any)=>icon.sizes==='192x192'&&icon.purpose.includes('maskable'))).toBe(true);expect(manifest.icons.some((icon:any)=>icon.sizes==='512x512')).toBe(true);}const html=source('index.html'),css=source('css/styles.css');expect(html).toContain('apple-mobile-web-app-capable');expect(css).toContain('#c6da34');expect(css).toContain('#ebb51a');});
});
