import {describe,expect,it} from 'vitest';
import {readFileSync} from 'node:fs';import {join} from 'node:path';
const source=(file:string)=>readFileSync(join(process.cwd(),file),'utf8');
describe('mobile/tablet responsive containment and autocomplete search',()=>{
  it('contains the shell and dynamic modules within the device width',()=>{const css=source('css/styles.css');expect(css).toContain('html,body{width:100%;max-width:100%;overflow-x:clip}');expect(css).toContain('#sari-app-layout,#main-content,#sari-main-view');expect(css).toContain('max-width:calc(100vw - .7rem)!important');expect(css).toContain('img,svg,canvas,video,object,iframe{max-width:100%}');});
  it('uses phone/tablet breakpoints and adaptive font sizes',()=>{const css=source('css/styles.css');expect(css).toContain('@media(max-width:1023px)');expect(css).toContain('@media(max-width:640px)');expect(css).toContain('@media(max-width:380px)');expect(css).toContain('font-size:clamp(.78rem,3.35vw,.92rem)');expect(css).toContain('font-size:16px');});
  it('keeps section tabs visible through touch horizontal scrolling',()=>{const css=source('css/styles.css');expect(css).toContain('#sari-main-view nav');expect(css).toContain('overflow-x:auto');expect(css).toContain('flex-wrap:nowrap!important');expect(css).toContain('scroll-snap-type:x proximity');});
  it('adds a mobile-only search button to managed and dialog autocompletes',()=>{const managed=source('js/managed-autocomplete.js'),dialogs=source('js/dialogs.js'),mobile=source('js/mobile-autocomplete.js'),main=source('src/main.ts'),css=source('css/styles.css');expect(managed).toContain('mobile-autocomplete-search-button');expect(dialogs).toContain('mobile-autocomplete-search-button');expect(main).toContain("import '../js/mobile-autocomplete.js'");expect(mobile).toContain('MobileAutocompleteSearch');expect(mobile).toContain('mobile-autocomplete-query');expect(mobile).toContain("dispatchEvent(new Event('input'");expect(css).toContain('.mobile-autocomplete-backdrop');});
  it('makes the full sidebar independently scrollable on short devices',()=>{expect(source('css/styles.css')).toContain('.sari-sidebar{overflow-y:auto;overscroll-behavior:contain}');});
});
