import {describe,expect,it} from 'vitest';
import {readFileSync} from 'node:fs';import {join} from 'node:path';import {createRequire} from 'node:module';
const source=(file:string)=>readFileSync(join(process.cwd(),file),'utf8');
const require=createRequire(import.meta.url);
describe('standards-compliant URL verification QR codes',()=>{
  it('uses the standards QR encoder and not the former QR-like matrix',()=>{const runtime=source('js/qr-code.js'),utils=source('js/utils.js'),main=source('src/main.ts');expect(runtime).toContain("from 'qrcode'");expect(main.indexOf("import '../js/qr-code.js'")).toBeLessThan(main.indexOf("import '../js/utils.js'"));expect(utils).toContain("encoder.create(value,{errorCorrectionLevel:'M'})");expect(utils).toContain("canvasEl.dataset.qrType='URL'");expect(utils).not.toContain('seed^=seed<<13');expect(utils).toContain('qrSvgDataUrl');expect(utils).toContain('image/svg+xml');expect(utils).toContain('shape-rendering="crispEdges"');});
  it('produces a real QR matrix for an HTTPS verification URL',()=>{const QRCode=require('qrcode');const url='https://sari.example/verification/SARI-PAY-001-A1B2';const qr=QRCode.create(url,{errorCorrectionLevel:'M'});expect(qr.modules.size).toBeGreaterThanOrEqual(21);expect(qr.modules.data.length).toBe(qr.modules.size*qr.modules.size);expect([...qr.modules.data].some(Boolean)).toBe(true);});
  it('normalizes and binds document identity into configured verification URLs',()=>{const utils=source('js/utils.js'),security=source('js/document-security.js'),settings=source('js/modules/settings.js');expect(utils).toContain('normalizeVerificationUrl');expect(utils).toContain('verificationHash');expect(utils).toContain('configured.replace(tokenPattern');expect(utils).toContain("http://sarisysteme.com/verification/{code}/{hash}");expect(security).toContain('SariUtils.buildVerificationUrl');expect(settings).toContain('barcode-qr-pattern');});
  it('marks HR QR blocks as URL links to verification',()=>{for(const file of ['js/modules/contracts.js','js/modules/payslips.js']){const text=source(file);expect(text).toContain('data-qr-type="URL"');expect(text).toContain('Ouvrir la vérification');expect(text).toContain('target="_blank"');}});
  it('uses the centrally configured URL pattern and an automatic hash derived from the exact code',()=>{const utils=source('js/utils.js'),security=source('js/document-security.js');expect(utils).toContain("const code=String(data.code");expect(utils).toContain('hash=this.verificationHash(code)');expect(utils).toContain("replace(tokenPattern,(_,key)=>encodeURIComponent(map[key]??''))");expect(security).toContain('SariUtils.verificationHash(referenceCode)');expect(utils).not.toContain("map['{hash}']||map['{id}']");});
});
