-- Section 254: business order is independent from immutable technical id.
ALTER TABLE `products` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `suppliers` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `banks` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `bank_accounts` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `customers` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `shipments` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `tenders` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `orders` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `purchase_documents` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `job_postings` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `employees` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `missions` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `document_templates` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `tax_records` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `stock_movements` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `inventory_counts` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `payment_transactions` ADD COLUMN IF NOT EXISTS `display_order` BIGINT UNSIGNED NULL;
ALTER TABLE `inventory_counts` ADD COLUMN IF NOT EXISTS `reference_code` VARCHAR(150) NULL UNIQUE;
ALTER TABLE `inventory_counts` ADD COLUMN IF NOT EXISTS `operator_id` VARCHAR(255) NULL;
ALTER TABLE `inventory_counts` ADD COLUMN IF NOT EXISTS `operator_name` VARCHAR(180) NULL;
ALTER TABLE `inventory_counts` ADD COLUMN IF NOT EXISTS `notes` TEXT NULL;
ALTER TABLE `inventory_counts` ADD COLUMN IF NOT EXISTS `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `inventory_counts` ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `stock_movements` ADD COLUMN IF NOT EXISTS `reference_code` VARCHAR(150) NULL UNIQUE;
ALTER TABLE `stock_movements` ADD COLUMN IF NOT EXISTS `user_id` VARCHAR(255) NULL;
ALTER TABLE `stock_movements` ADD COLUMN IF NOT EXISTS `user_name` VARCHAR(180) NULL;
ALTER TABLE `stock_movements` ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE `products` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `suppliers` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `banks` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `bank_accounts` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `customers` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `shipments` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `tenders` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `orders` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `purchase_documents` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `job_postings` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `employees` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `missions` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `document_templates` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `tax_records` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `stock_movements` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `inventory_counts` SET `display_order`=`id` WHERE `display_order` IS NULL;
UPDATE `payment_transactions` SET `display_order`=`id` WHERE `display_order` IS NULL;
