/**
 * SARI Système — Detailed article-by-article Work Rules and General Terms
 * templates (Section 314), drafted for a medical-equipment distribution
 * company operating in Algeria. These are editable model texts to be
 * reviewed and adjusted before adoption as the official company policy.
 */

export interface PolicyArticle {
  n: number;
  title: { fr: string; ar: string; en: string };
  body: { fr: string; ar: string; en: string };
}

export interface PolicyDocument {
  kind: 'rules' | 'terms';
  title: { fr: string; ar: string; en: string };
  preamble: { fr: string; ar: string; en: string };
  articles: PolicyArticle[];
}

const L = (fr: string, ar: string, en: string) => ({ fr, ar, en });

export const workRulesPolicy: PolicyDocument = {
  kind: 'rules',
  title: L('Règlement intérieur — SARI SYSTÈME', 'النظام الداخلي — SARI SYSTÈME', 'Internal Work Rules — SARI SYSTÈME'),
  preamble: L(
    'Le présent règlement intérieur fixe, conformément à la loi algérienne n° 90-11 du 21 avril 1990 relative aux relations de travail, les règles permanentes relatives à l’organisation du travail, à l’hygiène, à la sécurité et à la discipline applicables à l’ensemble du personnel de SARI SYSTÈME, société de distribution de matériel médical et de consommables. Chaque salarié est réputé en avoir pris connaissance et s’engage à le respecter.',
    'يحدد هذا النظام الداخلي، وفقًا للقانون الجزائري رقم 90-11 المؤرخ في 21 أبريل 1990 المتعلق بعلاقات العمل، القواعد الدائمة المتعلقة بتنظيم العمل والنظافة والأمن والانضباط المطبقة على جميع موظفي SARI SYSTÈME، شركة توزيع المعدات والمستهلكات الطبية. يعتبر كل موظف على علم به ويلتزم باحترامه.',
    'These internal work rules set, in accordance with Algerian law n° 90-11 of 21 April 1990 on labour relations, the permanent rules for work organisation, hygiene, safety and discipline applying to all SARI SYSTÈME staff, a medical equipment and consumables distribution company. Every employee is deemed to have read them and commits to complying with them.',
  ),
  articles: [
    { n: 1, title: L('Objet et champ d’application', 'الموضوع ونطاق التطبيق', 'Purpose and scope'), body: L('Le présent règlement s’applique à l’ensemble des salariés, quel que soit leur contrat (CDI, CDD, apprentissage) ou leur poste, y compris aux travailleurs occasionnels présents dans les locaux. Toute disposition contraire d’un contrat individuel est inopposable à l’entreprise.', 'يسري هذا النظام على جميع الموظفين مهما كان عقدهم (CDI، CDD، تلمذة) أو منصبهم، بما في ذلك العمال العرضيين المتواجدين بالمقر. أي بند مخالف في عقد فردي لا يحتج به تجاه الشركة.', 'These rules apply to all employees regardless of their contract (permanent, fixed-term, apprenticeship) or position, including occasional workers on the premises. Any contrary provision in an individual contract is unenforceable against the company.') },
    { n: 2, title: L('Horaires de travail et pointage', 'أوقات العمل والتسجيل', 'Working hours and time tracking'), body: L('Les horaires de travail sont définis dans la configuration RH (jours ouvrés et heures quotidiennes). Chaque salarié doit pointer ses heures d’entrée et de sortie via le système SARI. Le non-pointage répété est assimilé à une absence non justifiée.', 'تُحدد أوقات العمل في إعدادات الموارد البشرية (أيام العمل والساعات اليومية). على كل موظف تسجيل أوقات دخوله وخروجه عبر نظام SARI. يعتبر التغاضي المتكرر عن التسجيل غيابًا غير مبرر.', 'Working hours are defined in the HR configuration (working days and daily hours). Every employee must record their clock-in and clock-out through the SARI system. Repeated failure to clock is treated as an unjustified absence.') },
    { n: 3, title: L('Jours ouvrés, week-end et jours fériés', 'أيام العمل ونهاية الأسبوع والعطل الرسمية', 'Working days, weekend and public holidays'), body: L('La semaine de travail algérienne s’étend du dimanche au jeudi ; le vendredi et le samedi constituent le repos hebdomadaire. La liste des jours fériés applicables figure dans le calendrier des jours fériés SARI, ajusté chaque année, notamment pour les fêtes religieuses à dates variables. Le travail un jour férié donne lieu à la majoration prévue par la configuration RH.', 'يمتد أسبوع العمل الجزائري من الأحد إلى الخميس؛ ويشكل الجمعة والسبت الراحة الأسبوعية. تظهر قائمة العطل الرسمية المطبقة في تقويم العطل الرسمية SARI، وتُعدل كل سنة خاصة للأعياد الدينية ذات التواريخ المتغيرة. يستحق العمل يوم عطلة رسمية التعويض المنصوص عليه في إعدادات الموارد البشرية.', 'The Algerian working week runs from Sunday to Thursday; Friday and Saturday are the weekly rest. The list of applicable public holidays appears in the SARI holiday calendar, adjusted every year, especially for religious holidays with variable dates. Working on a public holiday gives entitlement to the premium set in the HR configuration.') },
    { n: 4, title: L('Congés annuels et absences', 'الإجازات السنوية والغيابات', 'Annual leave and absences'), body: L('Le droit aux congés, les soldes par type de congé et les justificatifs requis sont gérés dans le module Congés. Toute absence doit être demandée et validée à l’avance ; les congés sans solde donnent lieu aux retenues calculées automatiquement sur la fiche de paie.', 'تُدار استحقاقات الإجازات وأرصدتها والمبررات المطلوبة في وحدة الإجازات. يجب طلب أي غياب والمصادقة عليه مسبقًا؛ وتترتب على الإجازات بدون أجر الاقتطاعات المحسوبة تلقائيًا في قسيمة الراتب.', 'Leave entitlements, per-type balances and required justifications are managed in the Leave module. Any absence must be requested and validated in advance; unpaid leave gives rise to the deductions calculated automatically on the payslip.') },
    { n: 5, title: L('Retards et absences injustifiées', 'التأخر والغيابات غير المبررة', 'Lateness and unjustified absences'), body: L('Tout retard ou absence non justifié est consigné au dossier du salarié. Trois retards non justifiés sur un mois peuvent entraîner un avertissement écrit. L’absence injustifiée est déduite de la rémunération conformément au diviseur mensuel configuré.', 'يُسجل كل تأخر أو غياب غير مبرر في ملف الموظف. قد يترتب على ثلاثة تأخرات غير مبررة خلال شهر إنذار كتابي. يُخصم الغياب غير المبرر من الأجر وفق المقسوم الشهري المحدد.', 'Any unjustified lateness or absence is recorded in the employee’s file. Three unjustified latenesses in a month may lead to a written warning. Unjustified absence is deducted from pay according to the configured monthly divisor.') },
    { n: 6, title: L('Conduite professionnelle et respect mutuel', 'السلوك المهني والاحترام المتبادل', 'Professional conduct and mutual respect'), body: L('Chaque salarié adopte une attitude professionnelle, loyale et respectueuse envers ses collègues, les clients, les fournisseurs et les institutions de santé. Tout acte de violence, de menace ou de dénigrement est interdit.', 'يلتزم كل موظف بسلوك مهني ومخلص ومحترم تجاه زملائه والعملاء والموردين والمؤسسات الصحية. يُمنع كل عمل عنيف أو تهديد أو تشهير.', 'Every employee maintains a professional, loyal and respectful attitude towards colleagues, clients, suppliers and health institutions. Any act of violence, threat or defamation is prohibited.') },
    { n: 7, title: L('Confidentialité et secret professionnel', 'السرية والمهنة', 'Confidentiality and professional secrecy'), body: L('Les informations relatives aux clients (hôpitaux, cliniques, pharmacies), aux prix, aux appels d’offres, aux fournisseurs et à la stratégie de l’entreprise sont strictement confidentielles. Cette obligation subsiste après la cessation de la relation de travail. Toute divulgation expose son auteur à des sanctions disciplinaires et aux poursuites prévues par la loi.', 'تعد المعلومات المتعلقة بالعملاء (المستشفيات والعيادات والصيدليات) والأسعار والمناقصات والموردين واستراتيجية الشركة سرية تمامًا. يبقى هذا الالتزام قائمًا بعد انتهاء علاقة العمل. يعرض كل إفشاء صاحبه لعقوبات تأديبية ومتابعات قانونية.', 'Information about clients (hospitals, clinics, pharmacies), prices, tenders, suppliers and company strategy is strictly confidential. This obligation survives the end of the employment relationship. Any disclosure exposes its author to disciplinary sanctions and legal proceedings.') },
    { n: 8, title: L('Protection des données personnelles et dossiers', 'حماية المعطيات الشخصية والملفات', 'Protection of personal data and files'), body: L('Les données à caractère personnel des salariés, clients et patients ne peuvent être consultées ou traitées qu’en cas de nécessité professionnelle, dans le respect de la loi n° 18-07 du 10 juin 2018 relative à la protection des données à caractère personnel.', 'لا يمكن الاطلاع على المعطيات الشخصية للموظفين والعملاء والمرضى أو معالجتها إلا عند الضرورة المهنية، مع احترام القانون رقم 18-07 المؤرخ في 10 جوان 2018 المتعلق بحماية المعطيات ذات الطابع الشخصي.', 'Personal data of employees, clients and patients may only be consulted or processed when professionally necessary, in compliance with law n° 18-07 of 10 June 2018 on the protection of personal data.') },
    { n: 9, title: L('Usage des ressources informatiques', 'استخدام الموارد المعلوماتية', 'Use of IT resources'), body: L('Les équipements informatiques, logiciels et accès SARI sont des outils de travail réservés à l’activité professionnelle. L’installation de logiciels non autorisés, la modification des configurations et l’usage abusif d’Internet sont interdits.', 'المعدات المعلوماتية والبرامج وولوج نظام SARI أدوات عمل مخصصة للنشاط المهني. يُمنع تثبيت برامج غير مرخصة أو تعديل الإعدادات أو الاستخدام المفرط للإنترنت.', 'IT equipment, software and SARI access are work tools reserved for professional activity. Installing unauthorised software, changing configurations and abusing Internet access are prohibited.') },
    { n: 10, title: L('Messagerie et communications internes', 'المراسلة والاتصالات الداخلية', 'Messaging and internal communications'), body: L('La messagerie interne SARI est réservée aux échanges professionnels. Le compte personnel de chaque salarié est strictement individuel ; les identifiants ne doivent jamais être partagés. Les échanges restent accessibles à la direction dans le cadre de la continuité de service.', 'تُخصص المراسلة الداخلية SARI للتواصل المهني. الحساب الشخصي لكل موظف فردي تمامًا؛ ولا يجوز مشاركة بيانات الدخول إطلاقًا. تبقى المراسلات في متناول الإدارة في إطار استمرارية الخدمة.', 'SARI internal messaging is reserved for professional exchanges. Each employee’s personal account is strictly individual; credentials must never be shared. Exchanges remain accessible to management for service continuity.') },
    { n: 11, title: L('Matériel, équipements et locaux', 'المعدات والتجهيزات والمقرات', 'Equipment, assets and premises'), body: L('Chaque salarié veille à la bonne conservation du matériel médical, des équipements et des locaux. Toute détérioration volontaire engage la responsabilité de son auteur. Le matériel ne peut être sorti des locaux qu’avec une autorisation écrite.', 'يسهر كل موظف على حسن حفظ المعدات الطبية والتجهيزات والمقرات. كل إتلاف عمدي يُحمل صاحبه المسؤولية. لا يمكن إخراج المعدات من المقر إلا بترخيص كتابي.', 'Every employee takes care of medical equipment, assets and premises. Any wilful damage engages its author’s responsibility. Equipment may only leave the premises with written authorisation.') },
    { n: 12, title: L('Traçabilité et conformité des dispositifs médicaux', 'تتبع الأجهزة الطبية ومطابقتها', 'Traceability and compliance of medical devices'), body: L('La distribution de dispositifs médicaux impose une traçabilité rigoureuse : chaque mouvement de stock, numéro de lot et date de péremption doit être enregistré dans SARI sans délai. Toute falsification ou omission d’enregistrement constitue une faute grave.', 'يفرض توزيع الأجهزة الطبية تتبعًا صارمًا: يجب تسجيل كل حركة مخزون ورقم حصة وتاريخ صلاحية في SARI دون تأخير. يعد كل تزوير أو إغفال للتسجيل خطأ جسيمًا.', 'Distributing medical devices requires rigorous traceability: every stock movement, lot number and expiry date must be recorded in SARI without delay. Any falsification or omission of a record constitutes serious misconduct.') },
    { n: 13, title: L('Hygiène, santé et sécurité au travail', 'النظافة والصحة والسلامة في العمل', 'Hygiene, health and safety at work'), body: L('Le personnel respecte les consignes d’hygiène et de sécurité, notamment en entrepôt (chaîne du froid, EPI, manutention). Les incidents et situations dangereuses doivent être signalés immédiatement au supérieur hiérarchique. L’usage de substances illicites et la consommation d’alcool sur le lieu de travail sont strictement interdits.', 'يلتزم الموظفون بتعليمات النظافة والسلامة خاصة في المستودع (سلسلة التبريد، معدات الحماية، المناولة). يجب الإبلاغ فورًا عن الحوادث والحالات الخطرة إلى الرئيس المباشر. يُمنع منعًا باتًا تعاطي مواد غير مشروعة وشرب الكحول في مكان العمل.', 'Staff comply with hygiene and safety instructions, especially in the warehouse (cold chain, PPE, handling). Incidents and hazardous situations must be reported immediately to the line manager. Use of illicit substances and alcohol consumption in the workplace are strictly prohibited.') },
    { n: 14, title: L('Prévention des risques et situations d’urgence', 'الوقاية من المخاطر وحالات الطوارئ', 'Risk prevention and emergencies'), body: L('Les consignes d’évacuation et de secours affichées dans les locaux doivent être connues de tous. Chaque salarié participe aux exercices et formations de sécurité organisés par l’entreprise.', 'يجب أن تكون تعليمات الإخلاء والإسعاف المعلقة في المقر معروفة من الجميع. يشارك كل موظف في التمارين والتكوينات الأمنية التي تنظمها الشركة.', 'The evacuation and first-aid instructions posted on the premises must be known by all. Every employee participates in the safety drills and training organised by the company.') },
    { n: 15, title: L('Cadeaux, avantages et conflits d’intérêts', 'الهدايا والامتيازات وتضارب المصالح', 'Gifts, benefits and conflicts of interest'), body: L('Aucun salarié ne peut accepter de cadeau, commission ou avantage de nature à influencer une décision d’achat, de vente ou d’appel d’offres. Tout emploi ou engagement externe doit être déclaré via la déclaration de conflits d’intérêts (Section 304.3).', 'لا يجوز لأي موظف قبول هدية أو عمولة أو امتياز من شأنه التأثير على قرار شراء أو بيع أو مناقصة. يجب التصريح بأي عمل أو التزام خارجي عبر تصريح تضارب المصالح (القسم 304.3).', 'No employee may accept gifts, commissions or benefits liable to influence a purchase, sale or tender decision. Any external job or engagement must be declared through the conflict-of-interest declaration (Section 304.3).') },
    { n: 16, title: L('Non-discrimination et harcèlement', 'عدم التمييز والمضايقة', 'Non-discrimination and harassment'), body: L('Toute discrimination fondée sur le sexe, l’âge, la religion, l’origine, le handicap ou l’opinion est interdite, de même que toute forme de harcèlement moral ou sexuel. L’entreprise garantit un traitement équitable et un recours confidentiel à la direction.', 'يُمنع كل تمييز على أساس الجنس أو السن أو الدين أو الأصل أو الإعاقة أو الرأي، وكذلك كل أشكال المضايقة المعنوية أو الجنسية. تضمن الشركة معاملة منصفة وسبيلًا سريًا للجوء إلى الإدارة.', 'Any discrimination based on sex, age, religion, origin, disability or opinion is prohibited, as is any form of moral or sexual harassment. The company guarantees fair treatment and a confidential recourse to management.') },
    { n: 17, title: L('Échelle des sanctions disciplinaires', 'سلم العقوبات التأديبية', 'Scale of disciplinary sanctions'), body: L('Les sanctions applicables, graduées selon la gravité de la faute, sont : l’avertissement écrit, le blâme, la mise à pied disciplinaire (1 à 8 jours, sans rémunération) et, pour les fautes graves ou répétées, le licenciement disciplinaire. Aucune sanction pécuniaire directe n’est appliquée en dehors des retenues légales.', 'العقوبات المطبقة، مرتبة حسب خطورة الخطأ: الإنذار الكتابي، التوبيخ، التوقيف التأديبي (من 1 إلى 8 أيام بدون أجر)، وفي حال الأخطاء الجسيمة أو المتكررة، الفصل التأديبي. لا تطبق أي عقوبة مالية مباشرة خارج الاقتطاعات القانونية.', 'The sanctions applicable, graduated according to the seriousness of the fault, are: written warning, reprimand, disciplinary suspension (1 to 8 days without pay) and, for serious or repeated misconduct, disciplinary dismissal. No direct financial penalty is applied beyond the legal deductions.') },
    { n: 18, title: L('Procédure disciplinaire et droits du salarié', 'الإجراء التأديبي وحقوق الموظف', 'Disciplinary procedure and employee rights'), body: L('Aucune sanction ne peut être prononcée sans que le salarié ait été informé des faits reprochés et mis en mesure de présenter ses explications. La sanction est notifiée par écrit, motivée et versée au dossier individuel.', 'لا يمكن توقيع أي عقوبة دون إعلام الموظف بالأفعال المنسوبة إليه وتمكينه من تقديم إيضاحاته. تُبلغ العقوبة كتابيًا ومعللة وتودع في الملف الفردي.', 'No sanction may be imposed without the employee being informed of the alleged facts and given the opportunity to present explanations. The sanction is notified in writing, justified and filed in the individual record.') },
    { n: 19, title: L('Rupture du contrat : démission, licenciement et préavis', 'إنهاء العقد: الاستقالة والفصل والإخطار المسبق', 'Termination: resignation, dismissal and notice'), body: L('En cas de démission, le salarié respecte le préavis contractuel ou légal. Le licenciement, quelle qu’en soit la cause, est notifié par écrit dans les formes légales. À la cessation des fonctions, le salarié restitue les équipements, badges et documents de l’entreprise, et demeure tenu à l’obligation de confidentialité.', 'عند الاستقالة، يحترم الموظف فترة الإخطار التعاقدية أو القانونية. يُبلغ الفصل مهما كان سببه كتابيًا وفق الأشكال القانونية. عند انتهاء المهام، يعيد الموظف المعدات والشارات والوثائق، ويبقى ملزمًا بواجب السرية.', 'In case of resignation, the employee respects the contractual or legal notice period. Dismissal, whatever the cause, is notified in writing in the legal forms. On termination, the employee returns company equipment, badges and documents, and remains bound by confidentiality.') },
    { n: 20, title: L('Entrée en vigueur, diffusion et mise à jour', 'دخول حيز التنفيذ والنشر والتحيين', 'Entry into force, publication and updates'), body: L('Le présent règlement entre en vigueur après sa publication dans l’espace collaborateur et sa signature électronique par le salarié. Toute version nouvelle est notifiée à l’ensemble du personnel ; l’acceptation de la nouvelle version est requise pour accéder à l’intégralité de l’espace personnel.', 'يدخل هذا النظام حيز التنفيذ بعد نشره في الفضاء التعاوني وتوقيعه إلكترونيًا من الموظف. يُبلغ كل نسخة جديدة إلى جميع الموظفين؛ ويُشترط قبول النسخة الجديدة للوصول إلى كامل الفضاء الشخصي.', 'These rules enter into force after publication in the employee portal and the employee’s electronic signature. Any new version is notified to all staff; accepting the new version is required to access the full personal workspace.') },
  ],
};

export const generalTermsPolicy: PolicyDocument = {
  kind: 'terms',
  title: L('Conditions générales d’utilisation des outils SARI', 'الشروط العامة لاستخدام أدوات SARI', 'General Terms of Use for SARI Tools'),
  preamble: L(
    'Les présentes conditions générales encadrent l’accès et l’usage de l’ERP SARI SYSTÈME, de la messagerie interne et des documents mis à disposition dans l’espace collaborateur. L’utilisation des outils vaut acceptation sans réserve des présentes conditions.',
    'تؤطر هذه الشروط العامة الوصول إلى نظام ERP الخاص بـ SARI SYSTÈME والمراسلة الداخلية والوثائق المتاحة في الفضاء التعاوني واستخدامها. يعتبر استخدام الأدوات قبولًا دون تحفظ لهذه الشروط.',
    'These general terms govern access to and use of the SARI SYSTÈME ERP, the internal messaging and the documents available in the employee portal. Using the tools constitutes unreserved acceptance of these terms.',
  ),
  articles: [
    { n: 1, title: L('Objet et acceptation', 'الموضوع والقبول', 'Purpose and acceptance'), body: L('Les présentes conditions définissent les droits et obligations de l’utilisateur des outils SARI. L’acceptation est matérialisée par la signature électronique dans le parcours d’intégration (Section 304.4).', 'تحدد هذه الشروط حقوق والتزامات مستخدم أدوات SARI. يثبت القبول بالتوقيع الإلكتروني في مسار الاندماج (القسم 304.4).', 'These terms define the rights and obligations of the SARI tools user. Acceptance is evidenced by the electronic signature in the onboarding process (Section 304.4).') },
    { n: 2, title: L('Comptes et identifiants personnels', 'الحسابات ومعرفات الدخول الشخصية', 'Personal accounts and credentials'), body: L('Chaque compte est strictement personnel et incessible. L’utilisateur est responsable de la confidentialité de ses identifiants et doit signaler immédiatement toute perte, vol ou utilisation suspecte à l’Administrateur.', 'كل حساب شخصي تمامًا وغير قابل للتنازل. يتحمل المستخدم مسؤولية سرية معرفاته ويجب أن يبلغ فورًا عن أي فقدان أو سرقة أو استخدام مشبوه للمشرف.', 'Each account is strictly personal and non-transferable. The user is responsible for the confidentiality of their credentials and must immediately report any loss, theft or suspicious use to the Administrator.') },
    { n: 3, title: L('Usage professionnel des outils', 'الاستخدام المهني للأدوات', 'Professional use of the tools'), body: L('Les outils SARI sont mis à disposition pour l’exercice des missions professionnelles uniquement. Tout usage à des fins personnelles, commerciales parallèles ou contraires à la loi est interdit.', 'تُوضع أدوات SARI تحت تصرف المستخدم لأداء المهام المهنية فقط. يُمنع أي استخدام لأغراض شخصية أو تجارية موازية أو مخالف للقانون.', 'The SARI tools are provided solely for performing professional duties. Any use for personal, parallel commercial or unlawful purposes is prohibited.') },
    { n: 4, title: L('Données professionnelles et confidentialité', 'البيانات المهنية والسرية', 'Professional data and confidentiality'), body: L('Les données consultées ou saisies (stocks, prix, clients, documents) demeurent la propriété exclusive de SARI SYSTÈME. Leur copie, export ou transmission hors du cadre professionnel est interdit, sauf autorisation écrite de la direction.', 'تبقى البيانات المطالع عليها أو المدخلة (المخزون والأسعار والعملاء والوثائق) ملكًا حصريًا لـ SARI SYSTÈME. يُمنع نسخها أو تصديرها أو نقلها خارج الإطار المهني إلا بترخيص كتابي من الإدارة.', 'Data consulted or entered (stock, prices, clients, documents) remain the exclusive property of SARI SYSTÈME. Copying, exporting or transmitting them outside the professional context is prohibited without written management authorisation.') },
    { n: 5, title: L('Sécurité informatique', 'الأمن المعلوماتي', 'IT security'), body: L('L’utilisateur s’engage à ne pas contourner les mécanismes de sécurité, à ne pas introduire de logiciels malveillants et à verrouiller sa session en quittant son poste. Les mots de passe doivent respecter la politique de robustesse définie par l’Administrateur.', 'يلتزم المستخدم بعدم تجاوز آليات الأمان وعدم إدخال برامج خبيثة وقفل جلسته عند مغادرة مكتبه. يجب أن تحترم كلمات المرور سياسة القوة المحددة من المشرف.', 'The user undertakes not to bypass security mechanisms, not to introduce malicious software, and to lock their session when leaving their workstation. Passwords must comply with the strength policy defined by the Administrator.') },
    { n: 6, title: L('Messagerie interne', 'المراسلة الداخلية', 'Internal messaging'), body: L('La messagerie est un outil de coordination professionnelle. Les échanges doivent rester courtois et utiles à l’activité ; les contenus offensants, discriminatoires ou hors sujet peuvent donner lieu à sanctions disciplinaires.', 'المراسلة أداة تنسيق مهنية. يجب أن تبقى التبادلات مهذبة ومفيدة للنشاط؛ وقد تترتب عقوبات تأديبية على المحتويات المسيئة أو التمييزية أو الخارجة عن الموضوع.', 'Messaging is a professional coordination tool. Exchanges must remain courteous and useful to the activity; offensive, discriminatory or off-topic content may lead to disciplinary sanctions.') },
    { n: 7, title: L('Propriété intellectuelle', 'الملكية الفكرية', 'Intellectual property'), body: L('Les logiciels, modèles de documents, masques de référence et contenus SARI sont protégés. Aucune reproduction ou diffusion extérieure n’est autorisée sans accord écrit préalable de l’entreprise.', 'برامج SARI ونماذج الوثائق وأقنعة المراجع والمحتويات محمية. لا يجوز أي نسخ أو نشر خارجي دون موافقة كتابية مسبقة من الشركة.', 'The SARI software, document templates, reference masks and content are protected. No reproduction or external distribution is allowed without prior written company consent.') },
    { n: 8, title: L('Responsabilités', 'المسؤوليات', 'Liability'), body: L('L’utilisateur est responsable des opérations effectuées sous son compte. L’entreprise décline toute responsabilité pour les dommages résultant d’un usage non autorisé des outils ou du non-respect des présentes conditions.', 'المستخدم مسؤول عن العمليات المنفذة بحسابه. تخلي الشركة مسؤوليتها عن الأضرار الناجمة عن استخدام غير مرخص للأدوات أو عدم احترام هذه الشروط.', 'The user is responsible for the operations performed under their account. The company declines liability for damage resulting from unauthorised use of the tools or failure to comply with these terms.') },
    { n: 9, title: L('Suspension et retrait d’accès', 'تعليق وسحب الوصول', 'Suspension and withdrawal of access'), body: L('L’accès peut être suspendu en cas de suspicion d’incident de sécurité, et retiré à la cessation de la relation de travail. Certains modules peuvent rester bloqués tant que le parcours d’intégration (lecture, acceptation et signature) n’est pas terminé.', 'يمكن تعليق الوصول عند الاشتباه في حادث أمني، ويُسحب عند انتهاء علاقة العمل. قد تبقى بعض الوحدات محجوبة حتى إتمام مسار الاندماج (قراءة وقبول وتوقيع).', 'Access may be suspended on suspicion of a security incident and withdrawn upon termination of employment. Some modules may remain blocked until the onboarding process (reading, acceptance and signature) is completed.') },
    { n: 10, title: L('Évolution des présentes conditions', 'تطور هذه الشروط', 'Changes to these terms'), body: L('Les conditions générales peuvent être mises à jour. Chaque nouvelle version est publiée dans l’espace collaborateur avec son numéro de version ; l’utilisateur est invité à la relire, l’accepter et la signer à nouveau.', 'يمكن تحيين الشروط العامة. تُنشر كل نسخة جديدة في الفضاء التعاوني مع رقم نسختها؛ ويُدعى المستخدم إلى إعادة قراءتها وقبولها وتوقيعها.', 'The general terms may be updated. Each new version is published in the employee portal with its version number; the user is invited to read, accept and sign it again.') },
  ],
};

const pick = (value: { fr: string; ar: string; en: string }, lang: string): string => value[lang as 'fr' | 'ar' | 'en'] || value.fr;

/** Renders a policy document as numbered-article HTML for the given language. */
export function policyHtml(policy: PolicyDocument, lang = 'fr'): string {
  const dir = lang === 'ar' ? ' dir="rtl"' : '';
  const articles = policy.articles.map((article) => `<article class="policy-article"><h4${dir}>${lang === 'ar' ? `المادة ${article.n}` : lang === 'en' ? `Article ${article.n}` : `Article ${article.n}`} — ${pick(article.title, lang)}</h4><p${dir}>${pick(article.body, lang)}</p></article>`).join('');
  return `<div${dir}><h2${dir}>${pick(policy.title, lang)}</h2><p class="policy-preamble"${dir}>${pick(policy.preamble, lang)}</p>${articles}</div>`;
}

export const hrPolicies = { workRulesPolicy, generalTermsPolicy, policyHtml };
