/** Unified full-page consultation for linked sales, purchase, shipment and tax documents. */
const DocumentDetailModule = {
  state:{recordType:'',recordId:'',back:null},
  async open(recordType,recordId,back=null){this.state={recordType,recordId,back};await app.navigate('documentDetail');},
  store(){return this.state.recordType==='order'?'orders':this.state.recordType==='purchaseDocument'?'purchaseDocuments':this.state.recordType==='shipment'?'shipments':'taxRecords';},
  lineTotals(item){const gross=Number(item.qty||0)*Number(item.unitPrice||0),discount=SariUtils.parseDiscount(item.discountExpression??(item.discountPercent?item.discountPercent+'%':'0'),gross).amount,ht=Number.isFinite(Number(item.total))?Number(item.total):gross-discount,vat=ht*Number(item.vatRate??.19);return{ht,vat,ttc:ht+vat};},
  async render(containerId='sari-main-view'){
    const c=document.getElementById(containerId),store=this.store(),d=await sariDB.getById(store,this.state.recordId);if(!d){c.innerHTML='<div class="sari-tile p-8">Document introuvable.</div>';return;}
    const items=d.items||[],isPurchase=this.state.recordType==='purchaseDocument',links=(await sariDB.getAll('documentLinks')).filter(link=>link.sourceId===d.id||link.targetId===d.id),payments=(await sariDB.getAll('paymentTransactions')).filter(payment=>payment.documentId===d.id);
    c.innerHTML=`<div class="space-y-5"><button onclick="DocumentDetailModule.back()" class="doc-action"><i data-lucide="arrow-left" class="w-4 h-4"></i> Retour à ${this.state.back?.label||'la liste'}</button><section class="sari-tile p-6"><header class="flex flex-col md:flex-row justify-between gap-3 border-b pb-4"><div><span class="sari-badge">${d.documentType||d.type||this.state.recordType}</span><h1 class="text-2xl font-extrabold mt-2">${d.referenceCode||d.id}</h1>${isPurchase?`<button onclick="DocumentDetailModule.openSupplier('${d.supplierId}')" class="doc-action mt-1">${SariUtils.escapeHtml(d.supplierName||'')} →</button>`:`<p class="text-sm text-slate-500">${SariUtils.escapeHtml(d.customerName||d.partnerName||d.issuingOrganization||'')}</p>`}</div><div class="flex flex-wrap gap-2"><button onclick="DocumentLifecycle.open('${this.state.recordType}','${d.id}')" class="sari-btn px-4 bg-violet-100 text-violet-700"><i data-lucide="history"></i>${i18n.t('documentLifecycle','Cycle de vie')}</button><button onclick="DocumentTranslationManager.open('${this.state.recordType}','${d.id}')" class="sari-btn px-4 bg-sari-lime text-slate-900">Traduire</button><button onclick="DocumentManager.open('${this.state.recordType}','${d.id}','${d.referenceCode||d.id}')" class="sari-btn px-4 bg-slate-800 text-white">GED</button><button onclick="DocumentDetailModule.print()" class="sari-btn px-4 bg-sari-blue text-white">Imprimer / PDF</button></div></header>
      <div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 my-5"><div class="p-3 border rounded-xl"><small>Date</small><b class="block">${i18n.formatDate(d.createdAt||d.expectedArrival)}</b></div><div class="p-3 border rounded-xl"><small>Statut</small><b class="block">${OptionCatalog.label('documentStatus',d.status)||d.status||'—'}</b></div><div class="p-3 border rounded-xl"><small>Devise</small><b class="block">${d.currency||'DZD'}</b></div><div class="p-3 border rounded-xl"><small>Total</small><b class="block text-sari-blue text-lg">${i18n.formatCurrency(d.total||d.totalLandedCostDZD||d.amountDue||0,d.currency||'DZD')}</b></div></div>
      ${items.length?`<div class="overflow-x-auto"><table class="w-full sari-table text-sm"><thead><tr><th class="p-3 text-left">Désignation</th><th>Qté</th><th>Prix unitaire</th><th>Remise</th><th>TVA</th><th>Total HT</th>${isPurchase?'<th>Total TVA</th><th>Total TTC</th>':''}</tr></thead><tbody>${items.map(item=>{const totals=this.lineTotals(item);return`<tr class="border-t"><td class="p-3" ${DynamicI18n.attributes(item.productId?'products':this.state.recordType,item.productId||d.id,item.productId?'name':'lineName',item.name)}>${SariUtils.escapeHtml(DynamicI18n.get(item.productId?'products':this.state.recordType,item.productId||d.id,item.productId?'name':'lineName',item.name))}</td><td>${item.qty}</td><td>${i18n.formatCurrency(item.unitPrice,d.currency||'DZD')}</td><td>${item.discountExpression||`${item.discountPercent||0}%`}</td><td>${Number(item.vatRate??.19)*100}%</td><td class="font-bold">${i18n.formatCurrency(totals.ht,d.currency||'DZD')}</td>${isPurchase?`<td>${i18n.formatCurrency(totals.vat,d.currency||'DZD')}</td><td class="font-bold text-sari-blue">${i18n.formatCurrency(totals.ttc,d.currency||'DZD')}</td>`:''}</tr>`;}).join('')}</tbody></table></div>`:''}
      <div class="grid md:grid-cols-3 gap-4 mt-5"><section class="p-4 border rounded-xl"><h3 class="font-extrabold">Totaux</h3><p class="flex justify-between"><span>Sous-total</span><b>${i18n.formatCurrency(d.subtotal||0,d.currency||'DZD')}</b></p><p class="flex justify-between"><span>Remise</span><b>-${i18n.formatCurrency(d.discountAmount||0,d.currency||'DZD')}</b></p><p class="flex justify-between"><span>Transport</span><b>${i18n.formatCurrency(d.shippingFee||d.freightCost||0,d.currency||'DZD')}</b></p><p class="flex justify-between"><span>TVA</span><b>${i18n.formatCurrency(d.taxAmount||0,d.currency||'DZD')}</b></p></section><section class="p-4 border rounded-xl"><h3 class="font-extrabold">Paiements (${payments.length})</h3>${payments.map(payment=>`<button onclick="DocumentDetailModule.viewPayment('${payment.id}')" class="block w-full text-left text-xs py-2 border-b"><b>${payment.referenceCode}</b> • ${i18n.formatCurrency(payment.amount,payment.currency)} • ${payment.status}</button>`).join('')||'<p class="text-xs text-slate-400">Aucun paiement</p>'}</section><section class="p-4 border rounded-xl"><h3 class="font-extrabold">Documents liés (${links.length})</h3>${links.map(link=>`<p class="text-xs py-1">${link.sourceType}:${link.sourceId} → ${link.targetType}:${link.targetId}</p>`).join('')||'<p class="text-xs text-slate-400">Aucun lien</p>'}</section></div><section class="mt-5 p-4 border rounded-xl"><h3 class="font-extrabold">${i18n.t('notes','Notes')}</h3><p class="mt-2 text-sm whitespace-pre-wrap" ${DynamicI18n.attributes(this.state.recordType,d.id,'notes',d.documentNote||d.notes||'')}>${SariUtils.escapeHtml(DynamicI18n.get(this.state.recordType,d.id,'notes',d.documentNote||d.notes||'—'))}</p></section></section></div>`;
    window.SariIcons?.hydrate();
  },
  async openSupplier(id){await app.navigate('suppliers');await Partner360.open('supplier',id);},
  async viewPayment(id){const payment=await sariDB.getById('paymentTransactions',id);await DialogManager.alert(`${payment.referenceCode} • ${payment.direction==='in'?'Encaissement':'Décaissement'} • ${i18n.formatCurrency(payment.amount,payment.currency)} • ${payment.paymentMethod} • ${i18n.formatDate(payment.transactionDate)} • ${payment.status} • ${payment.notes||''}`,{title:'Détail du paiement'});},
  back(){const back=this.state.back;if(back?.type&&back?.id){app.navigate(back.type==='customer'?'customers':'suppliers');setTimeout(()=>Partner360.open(back.type,back.id),100);}else app.navigate(this.state.recordType==='purchaseDocument'?'purchases':'sales');},
  print(){if(this.state.recordType==='order')return SalesModule.openPrintModal(this.state.recordId,'facture');if(this.state.recordType==='purchaseDocument')return PurchasesModule.openPrint(this.state.recordId);window.print();return Promise.resolve();}
};
window.DocumentDetailModule=DocumentDetailModule;

export {};
