/** SARI Human Resources: employees, missions and recruitment. */
const HRModule = {
  state: { tab: 'employees', employees: [], missions: [], jobs: [], candidates: [], documents: [] },
  async render(containerId = 'sari-main-view') {
    const container = document.getElementById(containerId); if (!container) return;
    [this.state.employees, this.state.missions, this.state.jobs, this.state.candidates, this.state.documents] = await Promise.all(['employees','missions','jobPostings','candidates','documents'].map(s => sariDB.getAll(s)));
    const canWrite = auth.can('hr', 'edit');
    container.innerHTML = `<div class="space-y-5">
      <section class="sari-tile p-5 sari-grid-pattern flex flex-col md:flex-row justify-between gap-4"><div><span class="sari-badge bg-sari-blue/10 text-sari-blue">Capital humain</span><h2 class="text-2xl font-extrabold text-slate-900 dark:text-white mt-2 flex items-center gap-2"><i data-lucide="users-round" class="text-sari-blue"></i>Ressources Humaines</h2><p class="text-sm text-slate-500">Dossiers employés, missions, recrutement et documents RH centralisés.</p></div><div class="grid grid-cols-3 gap-2 text-center"><div class="p-3 bg-white/80 dark:bg-slate-800 rounded-xl border"><b class="text-xl text-sari-blue">${this.state.employees.filter(e=>e.status==='active').length}</b><small class="block">Actifs</small></div><div class="p-3 bg-white/80 dark:bg-slate-800 rounded-xl border"><b class="text-xl text-sari-amber">${this.state.missions.length}</b><small class="block">Missions</small></div><div class="p-3 bg-white/80 dark:bg-slate-800 rounded-xl border"><b class="text-xl text-sari-lime-dark">${this.state.candidates.length}</b><small class="block">Candidats</small></div></div></section>
      <nav class="sari-tile p-2 flex flex-wrap gap-2">${[['employees','users','Employés'],['missions','plane','Missions'],['recruitment','user-search','Recrutement']].map(x=>`<button onclick="HRModule.setTab('${x[0]}')" class="sari-btn px-4 py-2 text-xs ${this.state.tab===x[0]?'bg-sari-blue text-white':'text-slate-600 hover:bg-slate-100 dark:hover:bg-slate-800'}"><i data-lucide="${x[1]}" class="w-4 h-4"></i>${x[2]}</button>`).join('')}</nav>
      ${this.state.tab === 'employees' ? this.employeesHtml(canWrite) : this.state.tab === 'missions' ? this.missionsHtml(canWrite) : this.recruitmentHtml(canWrite)}
      <div id="hr-modal"></div></div>`;
    if (typeof lucide !== 'undefined') lucide.createIcons();
  },
  setTab(tab) { this.state.tab = tab; this.render(); },
  docCount(type,id) { return this.state.documents.filter(d => (d.links||[]).some(l=>l.recordType===type&&l.recordId===id)).length; },
  employeesHtml(canWrite) { return `<section class="sari-tile p-5"><header class="flex justify-between items-center mb-4"><div><h3 class="font-extrabold text-lg">Équipe SARI</h3><p class="text-xs text-slate-500">Profils, contrats, rémunération et pièces administratives</p></div>${canWrite?`<button onclick="HRModule.openEmployee()" class="sari-btn px-4 py-2 bg-sari-blue text-white text-xs"><i data-lucide="user-plus" class="w-4 h-4"></i>Nouvel employé</button>`:''}</header><div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">${this.state.employees.map(e=>`<article class="p-4 rounded-xl border bg-slate-50 dark:bg-slate-800/60 relative overflow-hidden"><span class="sari-corner-accent"></span><div class="flex gap-3"><div class="w-12 h-12 rounded-xl bg-sari-blue text-white grid place-items-center font-black">${SariUtils.escapeHtml((e.firstName?.[0]||'')+(e.lastName?.[0]||''))}</div><div><h4 class="font-extrabold">${SariUtils.escapeHtml(e.firstName)} ${SariUtils.escapeHtml(e.lastName)}</h4><p class="text-xs text-sari-blue font-bold">${SariUtils.escapeHtml(e.position)}</p><p class="text-[9px] font-mono-tech text-slate-400">${e.referenceCode||e.id}</p><p class="text-[10px] text-slate-500">${SariUtils.escapeHtml(e.department)} • ${e.contractType}</p></div></div><div class="grid grid-cols-2 gap-2 mt-4 text-xs"><div><span class="text-slate-400 block">Embauche</span>${i18n.formatDate(e.hireDate)}</div><div><span class="text-slate-400 block">Statut</span><b class="text-emerald-600">${e.status}</b></div><div><span class="text-slate-400 block">Email</span><span class="truncate block">${SariUtils.escapeHtml(e.email)}</span></div><div><span class="text-slate-400 block">Salaire</span><b>${i18n.formatCurrency(e.salary)}</b></div></div><footer class="flex gap-2 mt-4 pt-3 border-t"><button onclick="DocumentManager.open('employee','${e.id}','${SariUtils.escapeHtml(e.firstName+' '+e.lastName)}')" class="doc-action"><i data-lucide="paperclip" class="w-4 h-4"></i>${this.docCount('employee',e.id)} docs</button>${canWrite?`<button onclick="HRModule.openEmployee('${e.id}')" class="doc-action ml-auto"><i data-lucide="pencil" class="w-4 h-4"></i>Modifier</button><button onclick="HRModule.remove('employees','${e.id}')" class="doc-action text-red-600"><i data-lucide="trash-2" class="w-4 h-4"></i></button>`:''}</footer></article>`).join('')}</div></section>`; },
  missionsHtml(canWrite) { return `<section class="sari-tile p-5"><header class="flex justify-between mb-4"><div><h3 class="font-extrabold text-lg">Ordres de mission</h3><p class="text-xs text-slate-500">Déplacements, frais et validations</p></div>${canWrite?`<button onclick="HRModule.openMission()" class="sari-btn px-4 py-2 bg-sari-blue text-white text-xs"><i data-lucide="plus" class="w-4 h-4"></i>Nouvelle mission</button>`:''}</header><div class="overflow-x-auto"><table class="w-full sari-table text-sm"><thead><tr class="text-xs uppercase text-slate-500 border-b"><th class="p-3">Collaborateur</th><th>Destination</th><th>Période</th><th>Objet</th><th>Frais</th><th>Statut</th><th>Documents</th></tr></thead><tbody>${this.state.missions.map(m=>{const e=this.state.employees.find(x=>x.id===m.employeeId);return `<tr class="border-b"><td class="p-3 font-bold">${e?e.firstName+' '+e.lastName:'—'}</td><td><b class="font-mono-tech text-sari-blue text-xs">${m.referenceCode||m.id}</b><div>${SariUtils.escapeHtml(m.destination)}</div></td><td class="font-mono-tech text-xs">${i18n.formatDate(m.startDate)} → ${i18n.formatDate(m.endDate)}</td><td>${SariUtils.escapeHtml(m.purpose)}</td><td class="font-bold">${i18n.formatCurrency(m.expenses)}</td><td><span class="sari-badge bg-sari-blue/10 text-sari-blue">${m.status}</span></td><td><button onclick="DocumentManager.open('mission','${m.id}','Mission ${SariUtils.escapeHtml(m.destination)}')" class="doc-action"><i data-lucide="paperclip" class="w-4 h-4"></i>${this.docCount('mission',m.id)}</button></td></tr>`}).join('')}</tbody></table></div></section>`; },
  recruitmentHtml(canWrite) { const stages=['applied','interviewing','offer','hired','rejected']; return `<div class="space-y-4"><section class="sari-tile p-5"><header class="flex justify-between"><div><h3 class="font-extrabold text-lg">Postes ouverts</h3><p class="text-xs text-slate-500">Campagnes de recrutement</p></div>${canWrite?`<button onclick="HRModule.openJob()" class="sari-btn px-4 py-2 bg-sari-blue text-white text-xs">Publier un poste</button>`:''}</header><div class="grid md:grid-cols-3 gap-3 mt-4">${this.state.jobs.map(j=>`<div class="p-4 border rounded-xl"><span class="sari-badge bg-emerald-100 text-emerald-700">${j.status}</span><h4 class="font-bold mt-2">${SariUtils.escapeHtml(j.title)}</h4><p class="text-xs text-slate-500">${j.department} • ${j.location}</p></div>`).join('')}</div></section><section class="sari-tile p-5"><div class="flex justify-between"><h3 class="font-extrabold">Pipeline candidats</h3>${canWrite?`<button onclick="HRModule.openCandidate()" class="sari-btn px-3 py-1.5 bg-sari-lime text-slate-900 text-xs">Ajouter candidat</button>`:''}</div><div class="flex gap-3 overflow-x-auto mt-4 pb-2">${stages.map(stage=>`<div class="kanban-column p-3"><h4 class="font-bold text-xs uppercase mb-3">${stage} <span class="float-right sari-badge">${this.state.candidates.filter(c=>c.stage===stage).length}</span></h4>${this.state.candidates.filter(c=>c.stage===stage).map(c=>`<div class="kanban-card p-3 bg-white dark:bg-slate-900 rounded-lg border mb-2"><b class="text-sm">${SariUtils.escapeHtml(c.name)}</b><p class="text-xs text-slate-500">${SariUtils.escapeHtml(c.email)}</p><select onchange="HRModule.moveCandidate('${c.id}',this.value)" class="doc-input mt-2" ${canWrite?'':'disabled'}>${stages.map(s=>`<option ${s===c.stage?'selected':''}>${s}</option>`).join('')}</select><button onclick="DocumentManager.open('candidate','${c.id}','${SariUtils.escapeHtml(c.name)}')" class="doc-action mt-2"><i data-lucide="paperclip" class="w-3 h-3"></i>${this.docCount('candidate',c.id)} docs</button></div>`).join('')}</div>`).join('')}</div></section></div>`; },
  modal(title, body, submit) { document.getElementById('hr-modal').innerHTML=`<div class="fixed inset-0 z-50 sari-modal-backdrop flex items-center justify-center p-4"><form onsubmit="${submit}" class="sari-tile bg-white dark:bg-slate-900 p-6 w-full max-w-5xl max-h-[94vh] overflow-y-auto"><div class="flex justify-between border-b pb-3 mb-4"><h3 class="font-extrabold text-lg">${title}</h3><button type="button" onclick="HRModule.closeModal()"><i data-lucide="x"></i></button></div>${body}<div class="flex justify-end gap-2 mt-5 pt-4 border-t"><button type="button" onclick="HRModule.closeModal()" class="sari-btn px-4 py-2 bg-slate-200">Annuler</button><button class="sari-btn px-5 py-2 bg-sari-blue text-white">Enregistrer</button></div></form></div>`; if(typeof lucide!=='undefined')lucide.createIcons(); },
  async openEmployee(id='') { const e=this.state.employees.find(x=>x.id===id)||{}; this.modal(id?'Modifier employé':'Nouvel employé',`<input type="hidden" id="hr-id" value="${e.id||''}"><div class="grid md:grid-cols-2 gap-3">${[['firstName','Prénom',e.firstName],['lastName','Nom',e.lastName],['email','Email',e.email],['phone','Téléphone',e.phone],['position','Poste',e.position],['department','Département',e.department],['contractType','Type contrat',e.contractType||'CDI'],['salary','Salaire DZD',e.salary||0],['hireDate','Date embauche',e.hireDate||''],['status','Statut',e.status||'active'],['permissionOverrides','Permissions individuelles (séparées par virgule)',(e.permissionOverrides||[]).join(',')]].map(f=>`<label class="doc-label">${f[1]}<input id="hr-${f[0]}" ${f[0]==='hireDate'?'type="date"':f[0]==='salary'?'type="number"':'type="text"'} value="${SariUtils.escapeHtml(String(f[2]||''))}" class="doc-input mt-1" required></label>`).join('')}</div>`,`HRModule.saveEmployee(event)`); },
  async saveEmployee(e){e.preventDefault(); const id=document.getElementById('hr-id').value||`emp-${crypto.randomUUID()}`; const fields=['firstName','lastName','email','phone','position','department','contractType','salary','hireDate','status','permissionOverrides']; const old=this.state.employees.find(x=>x.id===id)||{}; const record={...old,id}; fields.forEach(f=>record[f]=document.getElementById(`hr-${f}`).value); record.referenceCode=old.referenceCode||await ReferenceCodeManager.generate('EMP',{date:record.hireDate}); record.salary=Number(record.salary); record.permissionOverrides=String(record.permissionOverrides||'').split(',').map(x=>x.trim()).filter(Boolean); await sariDB.save('employees',record); this.closeModal(); this.render();},
  openMission(){this.modal('Nouvel ordre de mission',`<div class="grid md:grid-cols-2 gap-3"><label class="doc-label">Employé<select id="mis-employee" class="doc-input mt-1">${this.state.employees.map(e=>`<option value="${e.id}">${e.firstName} ${e.lastName}</option>`).join('')}</select></label><label class="doc-label">Destination<input id="mis-destination" class="doc-input mt-1" required></label><label class="doc-label">Début<input id="mis-start" type="date" class="doc-input mt-1" required></label><label class="doc-label">Fin<input id="mis-end" type="date" class="doc-input mt-1" required></label><label class="doc-label md:col-span-2">Objet<input id="mis-purpose" class="doc-input mt-1" required></label><label class="doc-label">Frais DZD<input id="mis-expenses" type="number" class="doc-input mt-1" value="0"></label><label class="doc-label">Statut<select id="mis-status" class="doc-input mt-1"><option>planned</option><option>approved</option><option>in_progress</option><option>completed</option></select></label></div>`,`HRModule.saveMission(event)`);},
  async saveMission(e){e.preventDefault(); const m={id:`mission-${crypto.randomUUID()}`,referenceCode:await ReferenceCodeManager.generate('MIS',{date:document.getElementById('mis-start').value}),employeeId:document.getElementById('mis-employee').value,destination:document.getElementById('mis-destination').value,startDate:document.getElementById('mis-start').value,endDate:document.getElementById('mis-end').value,purpose:document.getElementById('mis-purpose').value,expenses:Number(document.getElementById('mis-expenses').value),status:document.getElementById('mis-status').value}; await sariDB.save('missions',m);this.closeModal();this.render();},
  openJob(){this.modal('Publier un poste',`<div class="grid gap-3"><label class="doc-label">Intitulé<input id="job-title" class="doc-input mt-1" required></label><label class="doc-label">Département<input id="job-dept" class="doc-input mt-1" required></label><label class="doc-label">Lieu<input id="job-location" class="doc-input mt-1" value="Alger" required></label></div>`,`HRModule.saveJob(event)`);},
  async saveJob(e){e.preventDefault();await sariDB.save('jobPostings',{id:`job-${crypto.randomUUID()}`,title:document.getElementById('job-title').value,department:document.getElementById('job-dept').value,location:document.getElementById('job-location').value,status:'open',publishedAt:new Date().toISOString()});this.closeModal();this.render();},
  openCandidate(){this.modal('Nouveau candidat',`<div class="grid gap-3"><label class="doc-label">Poste<select id="cand-job" class="doc-input mt-1">${this.state.jobs.map(j=>`<option value="${j.id}">${j.title}</option>`).join('')}</select></label><label class="doc-label">Nom complet<input id="cand-name" class="doc-input mt-1" required></label><label class="doc-label">Email<input id="cand-email" type="email" class="doc-input mt-1" required></label></div>`,`HRModule.saveCandidate(event)`);},
  async saveCandidate(e){e.preventDefault();await sariDB.save('candidates',{id:`cand-${crypto.randomUUID()}`,jobPostingId:document.getElementById('cand-job').value,name:document.getElementById('cand-name').value,email:document.getElementById('cand-email').value,stage:'applied',notes:''});this.closeModal();this.render();},
  async moveCandidate(id,stage){const c=await sariDB.getById('candidates',id);c.stage=stage;await sariDB.save('candidates',c);this.render();},
  async remove(store,id){if(confirm('Supprimer cet enregistrement ?')){await sariDB.delete(store,id);this.render();}}, closeModal(){document.getElementById('hr-modal').innerHTML='';}
};
window.HRModule=HRModule;
