/** Employee task and order tracking with offline Kanban planning views. */
const TasksModule = {
  state: { tasks: [], stages: [], employees: [], orders: [], period: 'week', scope: 'mine' },
  async render(containerId='sari-main-view') {
    const container=document.getElementById(containerId); if(!container)return;
    [this.state.tasks,this.state.stages,this.state.employees,this.state.orders]=await Promise.all(['tasks','taskStages','employees','orders'].map(s=>sariDB.getAll(s)));
    this.state.stages.sort((a,b)=>a.order-b.order);
    const mine=auth.employee?.id; const manager=auth.currentRole==='admin'||this.state.employees.some(e=>e.managerId===mine); this.state.canManage=auth.can('tasks','edit')||auth.can('tasks','create');
    const tasks=this.filteredTasks(manager); const done=tasks.filter(t=>t.stageId==='done').length;
    container.innerHTML=`<div class="space-y-5"><section class="sari-tile p-5 sari-grid-pattern flex flex-col lg:flex-row justify-between gap-4"><div><span class="sari-badge bg-sari-lime/20 text-sari-lime-dark">Productivité équipe</span><h2 class="text-2xl font-extrabold mt-2 flex items-center gap-2"><i data-lucide="square-kanban" class="text-sari-blue"></i>Tâches & suivi des commandes</h2><p class="text-sm text-slate-500">Planification personnelle et supervision des activités liées aux dossiers ERP.</p></div><div class="flex flex-wrap gap-2 items-end"><label class="doc-label">Vue temporelle<select onchange="TasksModule.setPeriod(this.value)" class="doc-input mt-1">${['day','week','month','year'].map(p=>`<option value="${p}" ${p===this.state.period?'selected':''}>${{day:'Jour',week:'Semaine',month:'Mois',year:'Année'}[p]}</option>`).join('')}</select></label>${manager?`<label class="doc-label">Périmètre<select onchange="TasksModule.setScope(this.value)" class="doc-input mt-1"><option value="mine" ${this.state.scope==='mine'?'selected':''}>Mes tâches</option><option value="team" ${this.state.scope==='team'?'selected':''}>Mon équipe</option></select></label>`:''}${this.state.canManage?`<button onclick="TasksModule.openTask()" class="sari-btn px-4 py-2 bg-sari-blue text-white text-xs"><i data-lucide="plus" class="w-4 h-4"></i>Nouvelle tâche</button>`:''}${auth.currentRole==='admin'?`<button onclick="TasksModule.addStage()" class="sari-btn px-3 py-2 bg-slate-800 text-white text-xs">+ Étape</button>`:''}</div></section>
      <div class="grid grid-cols-2 md:grid-cols-4 gap-3"><div class="sari-tile p-4"><small class="text-slate-500">Tâches visibles</small><b class="block text-2xl">${tasks.length}</b></div><div class="sari-tile p-4"><small class="text-slate-500">Terminées</small><b class="block text-2xl text-sari-lime-dark">${done}</b></div><div class="sari-tile p-4"><small class="text-slate-500">Urgentes</small><b class="block text-2xl text-red-500">${tasks.filter(t=>t.priority==='urgent').length}</b></div><div class="sari-tile p-4"><small class="text-slate-500">Progression</small><b class="block text-2xl text-sari-blue">${tasks.length?Math.round(done/tasks.length*100):0}%</b></div></div>
      <section class="overflow-x-auto pb-3"><div class="flex gap-4 min-w-max">${this.state.stages.map(stage=>this.column(stage,tasks)).join('')}</div></section>
      ${this.ordersHtml(manager)}<div id="task-modal"></div></div>`;
    if(typeof lucide!=='undefined')lucide.createIcons();
  },
  filteredTasks(manager){const now=new Date(); const end=new Date(now); if(this.state.period==='day')end.setDate(end.getDate()+1);if(this.state.period==='week')end.setDate(end.getDate()+7);if(this.state.period==='month')end.setMonth(end.getMonth()+1);if(this.state.period==='year')end.setFullYear(end.getFullYear()+1);let list=this.state.tasks.filter(t=>!t.dueDate||new Date(t.dueDate)<=end);if(!manager||this.state.scope==='mine') list=list.filter(t=>t.assigneeId===auth.employee?.id || (!auth.employee&&auth.currentRole==='admin')); else {const team=new Set(this.state.employees.filter(e=>e.managerId===auth.employee?.id).map(e=>e.id));if(auth.employee)team.add(auth.employee.id);if(auth.currentRole!=='admin')list=list.filter(t=>team.has(t.assigneeId));}return list;},
  column(stage,tasks){const lang=i18n.currentLang||'fr'; const list=tasks.filter(t=>t.stageId===stage.id);return `<div class="kanban-column w-72 p-3" ondragover="event.preventDefault()" ondrop="TasksModule.drop(event,'${stage.id}')"><header class="flex items-center justify-between mb-3 pb-2 border-b"><span class="font-extrabold text-xs uppercase flex items-center gap-2"><i data-lucide="circle" class="w-3 h-3" style="color:${stage.color};fill:${stage.color}"></i>${stage.label?.[lang]||stage.label?.fr||stage.id}</span><span class="sari-badge">${list.length}</span></header><div class="space-y-2 min-h-32">${list.map(t=>this.card(t)).join('')}</div></div>`;},
  card(t){const e=this.state.employees.find(x=>x.id===t.assigneeId);const colors={urgent:'border-red-500',high:'border-sari-amber',normal:'border-sari-blue',low:'border-slate-400'};return `<article draggable="true" ondragstart="event.dataTransfer.setData('text/plain','${t.id}')" class="kanban-card ${colors[t.priority]||colors.normal} p-3 bg-white dark:bg-slate-900 rounded-lg border shadow-sm"><div class="flex justify-between gap-2"><span class="text-[9px] font-black uppercase ${t.priority==='urgent'?'text-red-500':'text-slate-400'}">${t.priority}</span>${this.state.canManage?`<button onclick="TasksModule.openTask('${t.id}')"><i data-lucide="more-horizontal" class="w-4 h-4"></i></button>`:''}</div><h4 class="font-bold text-sm mt-1">${SariUtils.escapeHtml(t.title)}</h4><p class="text-xs text-slate-500 line-clamp-2 mt-1">${SariUtils.escapeHtml(t.description||'')}</p>${t.relatedId?`<span class="inline-flex mt-2 text-[10px] font-bold text-sari-blue bg-sari-blue/10 px-2 py-1 rounded"><i data-lucide="link" class="w-3 h-3 mr-1"></i>${t.relatedType}: ${SariUtils.escapeHtml(t.relatedId)}</span>`:''}<footer class="flex justify-between items-center mt-3 pt-2 border-t text-[10px]"><span class="font-bold">${e?e.firstName+' '+e.lastName:'Non assignée'}</span><time class="${new Date(t.dueDate)<new Date()&&t.stageId!=='done'?'text-red-500 font-bold':'text-slate-500'}">${t.dueDate?i18n.formatDate(t.dueDate):'—'}</time></footer></article>`;},
  ordersHtml(manager){let orders=this.state.orders;if(!manager||this.state.scope==='mine')orders=orders.filter(o=>o.assignedEmployeeId===auth.employee?.id);return `<section class="sari-tile p-5"><header><h3 class="font-extrabold flex items-center gap-2"><i data-lucide="clipboard-list" class="text-sari-blue"></i>Commandes affectées</h3><p class="text-xs text-slate-500">Suivi opérationnel personnel / équipe</p></header><div class="grid md:grid-cols-3 gap-3 mt-4">${orders.length?orders.slice(0,6).map(o=>{const e=this.state.employees.find(x=>x.id===o.assignedEmployeeId);return `<div class="p-3 border rounded-xl"><div class="flex justify-between"><b class="font-mono-tech text-sari-blue">${o.id}</b><span class="sari-badge">${o.status}</span></div><p class="font-bold text-sm mt-2">${SariUtils.escapeHtml(o.customerName)}</p><p class="text-xs text-slate-500">${e?'Responsable: '+e.firstName+' '+e.lastName:'Non affectée'}</p></div>`}).join(''):`<p class="text-sm text-slate-400 md:col-span-3 py-4">Aucune commande affectée dans cette vue.</p>`}</div></section>`;},
  setPeriod(v){this.state.period=v;this.render();},setScope(v){this.state.scope=v;this.render();},
  async drop(event,stageId){if(!this.state.canManage)return;const id=event.dataTransfer.getData('text/plain');const task=await sariDB.getById('tasks',id);if(task){task.stageId=stageId;task.updatedAt=new Date().toISOString();await sariDB.save('tasks',task);this.render();}},
  openTask(id=''){const t=this.state.tasks.find(x=>x.id===id)||{priority:'normal',stageId:this.state.stages[0]?.id||'todo',assigneeId:auth.employee?.id||this.state.employees[0]?.id||'',relatedType:'',relatedId:''};document.getElementById('task-modal').innerHTML=`<div class="fixed inset-0 z-50 sari-modal-backdrop flex items-center justify-center p-4"><form onsubmit="TasksModule.saveTask(event)" class="sari-tile bg-white dark:bg-slate-900 p-6 w-full max-w-xl"><input id="task-id" type="hidden" value="${t.id||''}"><div class="flex justify-between border-b pb-3 mb-4"><h3 class="font-extrabold">${id?'Modifier':'Créer'} une tâche</h3><button type="button" onclick="TasksModule.closeModal()"><i data-lucide="x"></i></button></div><div class="grid md:grid-cols-2 gap-3"><label class="doc-label md:col-span-2">Titre<input id="task-title" class="doc-input mt-1" value="${SariUtils.escapeHtml(t.title||'')}" required></label><label class="doc-label md:col-span-2">Description<textarea id="task-description" class="doc-input mt-1">${SariUtils.escapeHtml(t.description||'')}</textarea></label><label class="doc-label">Responsable<select id="task-assignee" class="doc-input mt-1">${this.state.employees.map(e=>`<option value="${e.id}" ${e.id===t.assigneeId?'selected':''}>${e.firstName} ${e.lastName}</option>`).join('')}</select></label><label class="doc-label">Échéance<input id="task-due" type="date" class="doc-input mt-1" value="${t.dueDate||''}"></label><label class="doc-label">Priorité<select id="task-priority" class="doc-input mt-1">${['low','normal','high','urgent'].map(p=>`<option ${p===t.priority?'selected':''}>${p}</option>`).join('')}</select></label><label class="doc-label">Étape<select id="task-stage" class="doc-input mt-1">${this.state.stages.map(s=>`<option value="${s.id}" ${s.id===t.stageId?'selected':''}>${s.label.fr}</option>`).join('')}</select></label><label class="doc-label">Type lié<select id="task-related-type" class="doc-input mt-1"><option value="">Aucun</option>${['order','tender','mission','product'].map(x=>`<option ${x===t.relatedType?'selected':''}>${x}</option>`).join('')}</select></label><label class="doc-label">Référence liée<input id="task-related-id" class="doc-input mt-1" value="${SariUtils.escapeHtml(t.relatedId||'')}"></label></div><div class="flex justify-between mt-5 pt-4 border-t">${id?`<button type="button" onclick="TasksModule.removeTask('${id}')" class="sari-btn px-3 py-2 text-red-600">Supprimer</button>`:'<span></span>'}<div class="flex gap-2"><button type="button" onclick="TasksModule.closeModal()" class="sari-btn px-4 py-2 bg-slate-200">Annuler</button><button class="sari-btn px-5 py-2 bg-sari-blue text-white">Enregistrer</button></div></div></form></div>`;if(typeof lucide!=='undefined')lucide.createIcons();},
  async saveTask(e){e.preventDefault();const id=document.getElementById('task-id').value||`task-${crypto.randomUUID()}`;const old=this.state.tasks.find(x=>x.id===id)||{};const task={...old,id,title:document.getElementById('task-title').value,description:document.getElementById('task-description').value,assigneeId:document.getElementById('task-assignee').value,dueDate:document.getElementById('task-due').value,priority:document.getElementById('task-priority').value,stageId:document.getElementById('task-stage').value,relatedType:document.getElementById('task-related-type').value,relatedId:document.getElementById('task-related-id').value,updatedAt:new Date().toISOString(),createdAt:old.createdAt||new Date().toISOString()};await sariDB.save('tasks',task);this.closeModal();this.render();},
  async removeTask(id){if(await DialogManager.confirm('Supprimer cette tâche ?')){await sariDB.delete('tasks',id);this.closeModal();this.render();}},
  async addStage(){const v=await DialogManager.form('Nouvelle étape',[{name:'name',label:'Nom',required:true},{name:'color',label:'Couleur',type:'color',value:'#8B5CF6'}]);if(!v)return;const name=v.name;const id=`stage-${crypto.randomUUID()}`;await sariDB.save('taskStages',{id,label:{fr:name,ar:name,en:name},color:v.color,order:this.state.stages.length+1});this.render();},closeModal(){document.getElementById('task-modal').innerHTML='';}
};
window.TasksModule=TasksModule;
