-- ==============================================================================
-- SARI SYSTÈME – Medical Equipment & Consumables Distribution Management System
-- DATABASE SCHEMA (DDL - Structure Only)
-- Compatible with MySQL 8.0+ / MariaDB / PostgreSQL / SQLite
-- Date: 2026-08-11
-- ==============================================================================

-- Drop existing tables if re-initializing schema (in reverse order of foreign keys)
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `order_items`;
DROP TABLE IF EXISTS `orders`;
DROP TABLE IF EXISTS `products`;
DROP TABLE IF EXISTS `shipments`;
DROP TABLE IF EXISTS `tenders`;
DROP TABLE IF EXISTS `customers`;
DROP TABLE IF EXISTS `suppliers`;
DROP TABLE IF EXISTS `warehouses`;
DROP TABLE IF EXISTS `notifications`;
DROP TABLE IF EXISTS `audit_logs`;
DROP TABLE IF EXISTS `app_settings`;
DROP TABLE IF EXISTS `entity_translations`;
DROP TABLE IF EXISTS `ged_tags`;
DROP TABLE IF EXISTS `ged_modules`;
DROP TABLE IF EXISTS `ged_categories`;
DROP TABLE IF EXISTS `configurable_options`;
DROP TABLE IF EXISTS `report_annotations`;
DROP TABLE IF EXISTS `payment_transactions`;
DROP TABLE IF EXISTS `api_tokens`;
DROP TABLE IF EXISTS `inventory_counts`;
DROP TABLE IF EXISTS `stock_movements`;
DROP TABLE IF EXISTS `product_lots`;
DROP TABLE IF EXISTS `incoterms`;
DROP TABLE IF EXISTS `logistics_statuses`;
DROP TABLE IF EXISTS `product_categories`;
DROP TABLE IF EXISTS `bank_types`;
DROP TABLE IF EXISTS `supplier_types`;
DROP TABLE IF EXISTS `client_types`;
DROP TABLE IF EXISTS `countries`;
DROP TABLE IF EXISTS `g50_payments`;
DROP TABLE IF EXISTS `tax_records`;
DROP TABLE IF EXISTS `document_links`;
DROP TABLE IF EXISTS `purchase_documents`;
DROP TABLE IF EXISTS `bank_accounts`;
DROP TABLE IF EXISTS `banks`;
DROP TABLE IF EXISTS `payment_methods`;
DROP TABLE IF EXISTS `messages`;
DROP TABLE IF EXISTS `conversations`;
DROP TABLE IF EXISTS `sequence_counters`;
DROP TABLE IF EXISTS `document_codes`;
DROP TABLE IF EXISTS `vat_rates`;
DROP TABLE IF EXISTS `users`;

SET FOREIGN_KEY_CHECKS = 1;

-- USERS TABLE (Authentication identities and server-assigned roles)
CREATE TABLE `users` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY,
  `username` VARCHAR(100) NOT NULL UNIQUE,
  `display_name` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL COMMENT 'Salted password hash generated by the authentication service',
  `role` VARCHAR(64) NOT NULL COMMENT 'admin, inventory, import_export, tenders, sales, readonly',
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  `last_login_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_user_role` (`role`),
  INDEX `idx_user_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP users with server-managed role-based access';

-- 1. WAREHOUSES TABLE (Dépôts de Stockage / المخازن)
CREATE TABLE `warehouses` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY,
  `name` VARCHAR(150) NOT NULL,
  `wilaya` VARCHAR(10) NOT NULL COMMENT 'Algerian Wilaya Code (01-58, e.g., 16 for Alger)',
  `address` VARCHAR(255) NOT NULL,
  `type` VARCHAR(100) NOT NULL COMMENT 'Type: Central / Chaine Froid / Régional Consommables',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Algerian Regional Warehouses and Cold Chain Depots';

-- 2. SUPPLIERS TABLE (Fournisseurs Locaux & Internationaux / الموردون)
CREATE TABLE `suppliers` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY,
  `name` VARCHAR(150) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `type` VARCHAR(50) NOT NULL COMMENT 'local, international, manufacturer, distributor',
  `contact_info` VARCHAR(255) NULL,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'DZD' COMMENT 'DZD, EUR, USD, CNY',
  `incoterms` VARCHAR(20) NOT NULL DEFAULT 'FOB' COMMENT 'FOB, CIF, EXW, DDP, CFR, FCA',
  `certifications` VARCHAR(255) NULL COMMENT 'ISO 13485, CE marking, TÜV, MSPRH DZ Homologation',
  `notes` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_supplier_type` (`type`),
  INDEX `idx_supplier_country` (`country`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Medical Equipment Manufacturers & Local Distributors';

-- 3. PRODUCTS TABLE (Dispositifs Médicaux & Consommables / المنتجات الطبية)
CREATE TABLE `products` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY,
  `sku` VARCHAR(100) NOT NULL UNIQUE,
  `barcode` VARCHAR(100) NULL,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(64) NOT NULL COMMENT 'diagnostic, consumables, furniture, sterilization, ppe, surgical',
  `manufacturer` VARCHAR(150) NULL,
  `country_of_origin` VARCHAR(100) NULL,
  `unit` VARCHAR(32) NOT NULL DEFAULT 'piece' COMMENT 'piece, box, carton, pack, liter, set',
  `purchase_price` DECIMAL(15, 2) NOT NULL DEFAULT 0.00 COMMENT 'Purchase price in DZD',
  `selling_price` DECIMAL(15, 2) NOT NULL DEFAULT 0.00 COMMENT 'Selling price in DZD',
  `stock` INT NOT NULL DEFAULT 0,
  `minimum_stock` INT NOT NULL DEFAULT 5,
  `lot_number` VARCHAR(100) NULL COMMENT 'Medical Batch / Lot number for traceability',
  `manufacturing_date` DATE NULL,
  `expiration_date` DATE NULL COMMENT 'Critical for medical consumables expiration tracking',
  `certification_ref` VARCHAR(150) NULL COMMENT 'CE marking or MSPRH DZ registration number',
  `storage_conditions` VARCHAR(255) NULL COMMENT 'Storage conditions e.g., Cold Chain < 25C',
  `warehouse_id` VARCHAR(64) NOT NULL,
  `notes` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_product_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  INDEX `idx_product_category` (`category`),
  INDEX `idx_product_lot` (`lot_number`),
  INDEX `idx_product_expiry` (`expiration_date`),
  INDEX `idx_product_warehouse` (`warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Medical Inventory Catalog & Consumable Traceability';

-- 4. SHIPMENTS TABLE (Expéditions Import / Export / الشحنات والجمارك)
CREATE TABLE `shipments` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY,
  `supplier_id` VARCHAR(64) NOT NULL,
  `supplier_name` VARCHAR(150) NOT NULL,
  `type` VARCHAR(32) NOT NULL DEFAULT 'import' COMMENT 'import, export',
  `status` VARCHAR(64) NOT NULL DEFAULT 'inTransit' COMMENT 'orderPlaced, inTransit, customsClearance, received',
  `currency` VARCHAR(10) NOT NULL DEFAULT 'USD',
  `foreign_amount` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  `exchange_rate` DECIMAL(10, 4) NOT NULL DEFAULT 1.0000,
  `purchase_cost_dzd` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  `freight_cost` DECIMAL(15, 2) NOT NULL DEFAULT 0.00 COMMENT 'Maritime / Air Freight cost in DZD',
  `insurance_cost` DECIMAL(15, 2) NOT NULL DEFAULT 0.00 COMMENT 'Transport Insurance in DZD',
  `customs_cost` DECIMAL(15, 2) NOT NULL DEFAULT 0.00 COMMENT 'Algerian Customs Duty (D10) in DZD',
  `total_landed_cost_dzd` DECIMAL(15, 2) NOT NULL DEFAULT 0.00 COMMENT 'Total Landed DZD Cost',
  `incoterm` VARCHAR(20) NOT NULL DEFAULT 'CIF',
  `expected_arrival` DATE NULL,
  `actual_arrival` DATE NULL,
  `documents_json` JSON NULL COMMENT 'Checklist array of documents (Invoice, PL, BL, D10, CE)',
  `notes` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_shipment_supplier` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  INDEX `idx_shipment_status` (`status`),
  INDEX `idx_shipment_supplier` (`supplier_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='International Import Shipments & Landed Cost Breakdown';

-- 5. TENDERS TABLE (Appels d\'Offres Hospitaliers / المناقصات والعقود)
CREATE TABLE `tenders` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `issuing_organization` VARCHAR(200) NOT NULL COMMENT 'e.g., CHU Mustapha Pacha, DSP Blida, EHS CPMC',
  `category` VARCHAR(64) NOT NULL,
  `estimated_value` DECIMAL(18, 2) NOT NULL DEFAULT 0.00 COMMENT 'Estimated Budget in DZD',
  `submission_deadline` DATE NOT NULL,
  `opening_date` DATE NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'watching' COMMENT 'watching, inPreparation, submitted, underEvaluation, won, lost, cancelled',
  `linked_product_ids_json` JSON NULL COMMENT 'Array of linked product IDs in Bid Preparation Workspace (BPU)',
  `documents_json` JSON NULL COMMENT 'Array of required administrative and technical documents',
  `notes` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_tender_status` (`status`),
  INDEX `idx_tender_deadline` (`submission_deadline`),
  INDEX `idx_tender_org` (`issuing_organization`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Public & Private Algerian Medical Consultations / Tenders';

-- 6. CUSTOMERS TABLE (Clients, Hôpitaux CHU/EHS & Pharmacies / العملاء والمستشفيات)
CREATE TABLE `customers` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY,
  `name` VARCHAR(200) NOT NULL,
  `type` VARCHAR(64) NOT NULL COMMENT 'public_hospital, private_clinic, pharmacy, government, wholesaler',
  `wilaya` VARCHAR(10) NOT NULL COMMENT 'Algerian Wilaya Code (01-58)',
  `contact_info` VARCHAR(255) NULL,
  `tax_id` VARCHAR(150) NULL COMMENT 'Fiscal NIF and Register of Commerce RC numbers',
  `payment_terms` VARCHAR(150) NULL COMMENT 'e.g., Virement Trésor Public - 60 Jours',
  `credit_limit` DECIMAL(18, 2) NOT NULL DEFAULT 10000000.00 COMMENT 'Authorized Credit Limit in DZD',
  `notes` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_customer_type` (`type`),
  INDEX `idx_customer_wilaya` (`wilaya`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Hospitals, Clinics, Pharmacies and Wilaya Health Directorates';

-- 7. ORDERS TABLE (Commandes B2B & Ventes POS / الطلبيات والفواتير)
CREATE TABLE `orders` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY,
  `customer_id` VARCHAR(64) NOT NULL,
  `customer_name` VARCHAR(200) NOT NULL,
  `warehouse_id` VARCHAR(64) NOT NULL,
  `subtotal` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  `discount_percent` DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
  `discount_amount` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  `tax_rate` DECIMAL(5, 4) NOT NULL DEFAULT 0.1900 COMMENT 'Algerian 19% TVA Tax',
  `tax_amount` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  `total` DECIMAL(15, 2) NOT NULL DEFAULT 0.00 COMMENT 'Total TTC in DZD',
  `payment_method` VARCHAR(32) NOT NULL DEFAULT 'bank_transfer' COMMENT 'bank_transfer, check, cash, credit',
  `status` VARCHAR(64) NOT NULL DEFAULT 'delivered' COMMENT 'quoted, confirmed, delivered, invoiced, paid',
  `notes` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_order_customer` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_order_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  INDEX `idx_order_customer` (`customer_id`),
  INDEX `idx_order_status` (`status`),
  INDEX `idx_order_date` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='B2B Orders, Counter Sales, and Printed Invoices / BL';

-- 8. ORDER_ITEMS TABLE (Lignes de Commande Normalisées / بنود الطلبيات)
CREATE TABLE `order_items` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY,
  `order_id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64) NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `qty` INT NOT NULL DEFAULT 1,
  `unit_price` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  `total` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  CONSTRAINT `fk_order_item_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_order_item_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  INDEX `idx_order_item_order` (`order_id`),
  INDEX `idx_order_item_product` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Line Items for Orders and Delivery Notes';

-- 9. NOTIFICATIONS TABLE (Alertes Péremptions & Stock / التنبيهات والإشعارات)
CREATE TABLE `notifications` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY,
  `type` VARCHAR(64) NOT NULL COMMENT 'near_expiry, tender_deadline, shipment, low_stock',
  `title` VARCHAR(255) NOT NULL,
  `message` TEXT NOT NULL,
  `is_read` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_notification_read` (`is_read`),
  INDEX `idx_notification_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='System Alerts for Expiring Consumables and Tender Deadlines';

-- 10. AUDIT_LOGS TABLE (Journal d\'Audit & Traçabilité / سجل النشاطات)
CREATE TABLE `audit_logs` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY,
  `user_name` VARCHAR(100) NOT NULL,
  `user_role` VARCHAR(64) NOT NULL COMMENT 'admin, inventory, import_export, tenders, sales, readonly',
  `action` VARCHAR(100) NOT NULL,
  `module` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_audit_role` (`user_role`),
  INDEX `idx_audit_module` (`module`),
  INDEX `idx_audit_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Immutable Activity Trail of System and Inventory Mutations';

-- 11. APP_SETTINGS TABLE (Configuration Globale & Fiscalité Algérie / الإعدادات)
CREATE TABLE `app_settings` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY,
  `language` VARCHAR(10) NOT NULL DEFAULT 'fr' COMMENT 'fr, ar, en',
  `theme` VARCHAR(32) NOT NULL DEFAULT 'classic' COMMENT 'classic, clinical, sunset, midnight',
  `currency` VARCHAR(10) NOT NULL DEFAULT 'DZD',
  `tax_rate` DECIMAL(5, 4) NOT NULL DEFAULT 0.1900 COMMENT 'Algerian 19% TVA',
  `company_name` VARCHAR(150) NOT NULL DEFAULT 'SARI SYSTÈMES',
  `company_subtitle` VARCHAR(200) NOT NULL DEFAULT 'Distribution Matériel Médical & Consommables Algérie',
  `address` VARCHAR(255) NOT NULL DEFAULT 'Lotissement Medical, Bab Ezzouar, 16024 Alger, Algérie',
  `phone` VARCHAR(150) NOT NULL DEFAULT '+213 21 24 88 90 / +213 550 99 12 34',
  `email` VARCHAR(150) NOT NULL DEFAULT 'contact@sarisysteme.dz',
  `website` VARCHAR(150) NOT NULL DEFAULT 'www.sarisysteme.dz',
  `nif` VARCHAR(100) NOT NULL DEFAULT '001616098765432',
  `rc` VARCHAR(100) NOT NULL DEFAULT '16/00-0987654B19',
  `ai` VARCHAR(100) NOT NULL DEFAULT '1602409876',
  `nis` VARCHAR(100) NOT NULL DEFAULT '001616012345678',
  `bank_rib` VARCHAR(200) NOT NULL DEFAULT 'BNA Agence 001 - RIB 00100161609876543209',
  `custom_translations_json` JSON NULL COMMENT 'Custom trilingual dictionary overrides (FR/AR/EN)',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Global Company Details, Tax Settings and Native Themes';

-- ENTERPRISE CONFIGURATION: VAT, ERP REFERENCES & INTERNAL MESSAGING
CREATE TABLE `vat_rates` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY, `label` VARCHAR(100) NOT NULL,
  `percentage` DECIMAL(6,3) NOT NULL, `is_default` BOOLEAN NOT NULL DEFAULT FALSE,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `document_codes` (
  `code` VARCHAR(10) NOT NULL PRIMARY KEY, `designation` VARCHAR(150) NOT NULL,
  `description` TEXT NULL, `mask` VARCHAR(150) NOT NULL, `example` VARCHAR(150) NULL,
  `mask_type` VARCHAR(32) NOT NULL DEFAULT 'Standard', `sequence_min_digits` INT NOT NULL DEFAULT 5,
  `reset_frequency` VARCHAR(16) NOT NULL DEFAULT 'yearly', `sub_type_options_json` JSON NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sequence_counters` (
  `id` VARCHAR(255) NOT NULL PRIMARY KEY, `document_code` VARCHAR(10) NOT NULL,
  `period_key` VARCHAR(32) NOT NULL, `counter_value` BIGINT NOT NULL DEFAULT 0,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_counter_document_code` FOREIGN KEY (`document_code`) REFERENCES `document_codes` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `conversations` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY, `title` VARCHAR(200) NOT NULL,
  `participant_user_ids_json` JSON NOT NULL, `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `messages` (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY, `conversation_id` VARCHAR(64) NOT NULL,
  `sender_user_id` VARCHAR(64) NOT NULL, `body` TEXT NOT NULL, `read_by_user_ids_json` JSON NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_message_conversation` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_message_sender` FOREIGN KEY (`sender_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  INDEX `idx_message_conversation` (`conversation_id`), INDEX `idx_message_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ERP-wide generated references on existing relational entities.
ALTER TABLE `products` ADD COLUMN `reference_code` VARCHAR(150) NULL UNIQUE AFTER `id`;
ALTER TABLE `suppliers` ADD COLUMN `reference_code` VARCHAR(150) NULL UNIQUE AFTER `id`;
ALTER TABLE `shipments` ADD COLUMN `reference_code` VARCHAR(150) NULL UNIQUE AFTER `id`;
ALTER TABLE `tenders` ADD COLUMN `reference_code` VARCHAR(150) NULL UNIQUE AFTER `id`;
ALTER TABLE `customers` ADD COLUMN `reference_code` VARCHAR(150) NULL UNIQUE AFTER `id`;
ALTER TABLE `orders` ADD COLUMN `reference_code` VARCHAR(150) NULL UNIQUE AFTER `id`;
ALTER TABLE `products` ADD COLUMN `vat_rate_id` VARCHAR(64) NULL,
  ADD COLUMN `discount_percent` DECIMAL(5,2) NOT NULL DEFAULT 0,
  ADD COLUMN `additional_fees` DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN `extended_description` TEXT NULL,
  ADD CONSTRAINT `fk_product_vat_rate` FOREIGN KEY (`vat_rate_id`) REFERENCES `vat_rates` (`id`);

-- PURCHASE / BANKING / FISCAL EXTENSIONS (IndexedDB v5 equivalents)
CREATE TABLE `payment_methods` (`id` VARCHAR(64) PRIMARY KEY, `code` VARCHAR(40) UNIQUE NOT NULL, `label_json` JSON NOT NULL, `is_active` BOOLEAN DEFAULT TRUE);
CREATE TABLE `banks` (`id` VARCHAR(64) PRIMARY KEY, `name` VARCHAR(180) NOT NULL, `swift` VARCHAR(32), `country` VARCHAR(3), `is_active` BOOLEAN DEFAULT TRUE);
CREATE TABLE `bank_accounts` (`id` VARCHAR(64) PRIMARY KEY, `bank_id` VARCHAR(64) NOT NULL, `name` VARCHAR(180) NOT NULL, `iban` VARCHAR(100), `currency` VARCHAR(10) DEFAULT 'DZD', `is_default` BOOLEAN DEFAULT FALSE, `is_active` BOOLEAN DEFAULT TRUE, FOREIGN KEY (`bank_id`) REFERENCES `banks` (`id`));
CREATE TABLE `purchase_documents` (`id` VARCHAR(64) PRIMARY KEY, `reference_code` VARCHAR(150) UNIQUE NOT NULL, `document_type` VARCHAR(32) NOT NULL, `supplier_id` VARCHAR(64), `supplier_name` VARCHAR(180), `status` VARCHAR(32), `currency` VARCHAR(10), `items_json` JSON, `subtotal` DECIMAL(18,2), `tax_amount` DECIMAL(18,2), `total` DECIMAL(18,2), `linked_tender_id` VARCHAR(64), `linked_sales_ids_json` JSON, `verification_hash` VARCHAR(128), `verification_url` VARCHAR(500), `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE `document_links` (`id` VARCHAR(64) PRIMARY KEY, `source_type` VARCHAR(50), `source_id` VARCHAR(64), `target_type` VARCHAR(50), `target_id` VARCHAR(64), `relation` VARCHAR(50), `status_flag` VARCHAR(100), INDEX `idx_document_link_source` (`source_id`), INDEX `idx_document_link_target` (`target_id`));
CREATE TABLE `tax_records` (`id` VARCHAR(64) PRIMARY KEY, `reference_code` VARCHAR(150) UNIQUE, `type` VARCHAR(20), `period` VARCHAR(20), `status` VARCHAR(32), `taxable_revenue` DECIMAL(18,2), `vat_collected` DECIMAL(18,2), `vat_deductible` DECIMAL(18,2), `amount_due` DECIMAL(18,2));
CREATE TABLE `g50_payments` (`id` VARCHAR(64) PRIMARY KEY, `tax_record_id` VARCHAR(64) NOT NULL, `amount` DECIMAL(18,2), `payment_date` DATE, `method` VARCHAR(50), `bank_account_id` VARCHAR(64), FOREIGN KEY (`tax_record_id`) REFERENCES `tax_records` (`id`));

-- CONFIGURABLE MASTER DATA / INVENTORY / INTEGRATION EXTENSIONS
CREATE TABLE `countries` (`id` VARCHAR(3) PRIMARY KEY, `code` VARCHAR(10), `iso2` VARCHAR(2) UNIQUE, `iso3` VARCHAR(3) UNIQUE, `name_json` JSON NOT NULL, `currency` VARCHAR(10), `is_active` BOOLEAN DEFAULT TRUE);
CREATE TABLE `client_types` (`id` VARCHAR(64) PRIMARY KEY, `code` VARCHAR(2), `name_json` JSON NOT NULL, `is_active` BOOLEAN DEFAULT TRUE);
CREATE TABLE `supplier_types` (`id` VARCHAR(64) PRIMARY KEY, `code` VARCHAR(2), `name_json` JSON NOT NULL, `is_active` BOOLEAN DEFAULT TRUE);
CREATE TABLE `bank_types` (`id` VARCHAR(64) PRIMARY KEY, `code` VARCHAR(2), `name_json` JSON NOT NULL, `is_active` BOOLEAN DEFAULT TRUE);
CREATE TABLE `product_categories` (`id` VARCHAR(64) PRIMARY KEY, `code` VARCHAR(2), `name_json` JSON NOT NULL, `is_active` BOOLEAN DEFAULT TRUE);
CREATE TABLE `logistics_statuses` (`id` VARCHAR(64) PRIMARY KEY, `sort_order` INT, `name_json` JSON NOT NULL, `color` VARCHAR(16), `is_active` BOOLEAN DEFAULT TRUE);
CREATE TABLE `incoterms` (`id` VARCHAR(16) PRIMARY KEY, `code` VARCHAR(16) UNIQUE, `name_json` JSON NOT NULL, `is_active` BOOLEAN DEFAULT TRUE);
CREATE TABLE `product_lots` (`id` VARCHAR(64) PRIMARY KEY, `product_id` VARCHAR(64) NOT NULL, `warehouse_id` VARCHAR(64), `lot_number` VARCHAR(100), `quantity` INT DEFAULT 0, `manufacturing_date` DATE, `expiration_date` DATE, `status` VARCHAR(32), FOREIGN KEY (`product_id`) REFERENCES `products` (`id`));
CREATE TABLE `stock_movements` (`id` VARCHAR(64) PRIMARY KEY, `product_id` VARCHAR(64), `lot_id` VARCHAR(64), `warehouse_id` VARCHAR(64), `type` VARCHAR(20), `quantity` INT, `delta` INT, `reason` VARCHAR(255), `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE `inventory_counts` (`id` VARCHAR(64) PRIMARY KEY, `warehouse_id` VARCHAR(64), `count_date` DATE, `status` VARCHAR(32), `lines_json` JSON);
CREATE TABLE `api_tokens` (`id` VARCHAR(64) PRIMARY KEY, `name` VARCHAR(150), `token_hash` VARCHAR(128) NOT NULL, `prefix` VARCHAR(20), `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `revoked_at` TIMESTAMP NULL);
CREATE TABLE `payment_transactions` (`id` VARCHAR(64) PRIMARY KEY, `reference_code` VARCHAR(150) UNIQUE, `partner_type` VARCHAR(32), `partner_id` VARCHAR(64), `document_type` VARCHAR(32), `document_id` VARCHAR(64), `direction` VARCHAR(8), `amount` DECIMAL(18,2), `currency` VARCHAR(10), `payment_method` VARCHAR(64), `bank_account_id` VARCHAR(64), `status` VARCHAR(32), `transaction_date` DATE);
CREATE TABLE `report_annotations` (`id` VARCHAR(64) PRIMARY KEY, `report_tab` VARCHAR(64), `html` TEXT, `updated_by` VARCHAR(64), `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE `entity_translations` (`id` VARCHAR(255) PRIMARY KEY, `entity_key` VARCHAR(180) NOT NULL, `entity_type` VARCHAR(64) NOT NULL, `entity_id` VARCHAR(100) NOT NULL, `field_name` VARCHAR(100) NOT NULL, `language` VARCHAR(10) NOT NULL, `translated_value` TEXT NOT NULL, `source_value` TEXT, `updated_by` VARCHAR(64), `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY `uq_entity_translation` (`entity_type`,`entity_id`,`field_name`,`language`), INDEX `idx_entity_translation_key` (`entity_key`));
CREATE TABLE `ged_categories` (`id` VARCHAR(64) PRIMARY KEY, `code` VARCHAR(64), `name_json` JSON NOT NULL, `sort_order` INT DEFAULT 0, `is_active` BOOLEAN DEFAULT TRUE);
CREATE TABLE `ged_modules` (`id` VARCHAR(64) PRIMARY KEY, `code` VARCHAR(64), `name_json` JSON NOT NULL, `sort_order` INT DEFAULT 0, `is_active` BOOLEAN DEFAULT TRUE);
CREATE TABLE `ged_tags` (`id` VARCHAR(64) PRIMARY KEY, `code` VARCHAR(64), `name_json` JSON NOT NULL, `sort_order` INT DEFAULT 0, `is_active` BOOLEAN DEFAULT TRUE);
CREATE TABLE `configurable_options` (`id` VARCHAR(128) PRIMARY KEY, `list_key` VARCHAR(64) NOT NULL, `option_value` VARCHAR(100) NOT NULL, `name_json` JSON NOT NULL, `sort_order` INT DEFAULT 0, `is_active` BOOLEAN DEFAULT TRUE, INDEX `idx_configurable_option_list` (`list_key`));

-- End of DDL Schema
